load("@rules_proto//proto:defs.bzl", "proto_library")

package(default_visibility = ["//visibility:public"])

proto_library(
    name = "aes_gcm_proto",
    srcs = ["aes_gcm.proto"],
    strip_import_prefix = "/proto/",
)
