"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2024 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.rpc.status_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class AptArtifact(google.protobuf.message.Message):
    """A detailed representation of an Apt artifact. Information in the record
    is derived from the archive's control file.
    See https://www.debian.org/doc/debian-policy/ch-controlfields.html
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _PackageType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _PackageTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[AptArtifact._PackageType.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        PACKAGE_TYPE_UNSPECIFIED: AptArtifact._PackageType.ValueType  # 0
        """Package type is not specified."""
        BINARY: AptArtifact._PackageType.ValueType  # 1
        """Binary package."""
        SOURCE: AptArtifact._PackageType.ValueType  # 2
        """Source package."""

    class PackageType(_PackageType, metaclass=_PackageTypeEnumTypeWrapper):
        """Package type is either binary or source."""

    PACKAGE_TYPE_UNSPECIFIED: AptArtifact.PackageType.ValueType  # 0
    """Package type is not specified."""
    BINARY: AptArtifact.PackageType.ValueType  # 1
    """Binary package."""
    SOURCE: AptArtifact.PackageType.ValueType  # 2
    """Source package."""

    NAME_FIELD_NUMBER: builtins.int
    PACKAGE_NAME_FIELD_NUMBER: builtins.int
    PACKAGE_TYPE_FIELD_NUMBER: builtins.int
    ARCHITECTURE_FIELD_NUMBER: builtins.int
    COMPONENT_FIELD_NUMBER: builtins.int
    CONTROL_FILE_FIELD_NUMBER: builtins.int
    name: builtins.str
    """Output only. The Artifact Registry resource name of the artifact."""
    package_name: builtins.str
    """Output only. The Apt package name of the artifact."""
    package_type: global___AptArtifact.PackageType.ValueType
    """Output only. An artifact is a binary or source package."""
    architecture: builtins.str
    """Output only. Operating system architecture of the artifact."""
    component: builtins.str
    """Output only. Repository component of the artifact."""
    control_file: builtins.bytes
    """Output only. Contents of the artifact's control metadata file."""
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        package_name: builtins.str = ...,
        package_type: global___AptArtifact.PackageType.ValueType = ...,
        architecture: builtins.str = ...,
        component: builtins.str = ...,
        control_file: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["architecture", b"architecture", "component", b"component", "control_file", b"control_file", "name", b"name", "package_name", b"package_name", "package_type", b"package_type"]) -> None: ...

global___AptArtifact = AptArtifact

@typing.final
class ImportAptArtifactsGcsSource(google.protobuf.message.Message):
    """Google Cloud Storage location where the artifacts currently reside."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    URIS_FIELD_NUMBER: builtins.int
    USE_WILDCARDS_FIELD_NUMBER: builtins.int
    use_wildcards: builtins.bool
    """Supports URI wildcards for matching multiple objects from a single URI."""
    @property
    def uris(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Cloud Storage paths URI (e.g., gs://my_bucket//my_object)."""

    def __init__(
        self,
        *,
        uris: collections.abc.Iterable[builtins.str] | None = ...,
        use_wildcards: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["uris", b"uris", "use_wildcards", b"use_wildcards"]) -> None: ...

global___ImportAptArtifactsGcsSource = ImportAptArtifactsGcsSource

@typing.final
class ImportAptArtifactsRequest(google.protobuf.message.Message):
    """The request to import new apt artifacts."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    GCS_SOURCE_FIELD_NUMBER: builtins.int
    PARENT_FIELD_NUMBER: builtins.int
    parent: builtins.str
    """The name of the parent resource where the artifacts will be imported."""
    @property
    def gcs_source(self) -> global___ImportAptArtifactsGcsSource:
        """Google Cloud Storage location where input content is located."""

    def __init__(
        self,
        *,
        gcs_source: global___ImportAptArtifactsGcsSource | None = ...,
        parent: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["gcs_source", b"gcs_source", "source", b"source"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["gcs_source", b"gcs_source", "parent", b"parent", "source", b"source"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["source", b"source"]) -> typing.Literal["gcs_source"] | None: ...

global___ImportAptArtifactsRequest = ImportAptArtifactsRequest

@typing.final
class ImportAptArtifactsErrorInfo(google.protobuf.message.Message):
    """Error information explaining why a package was not imported."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    GCS_SOURCE_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    @property
    def gcs_source(self) -> global___ImportAptArtifactsGcsSource:
        """Google Cloud Storage location requested."""

    @property
    def error(self) -> google.rpc.status_pb2.Status:
        """The detailed error status."""

    def __init__(
        self,
        *,
        gcs_source: global___ImportAptArtifactsGcsSource | None = ...,
        error: google.rpc.status_pb2.Status | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["error", b"error", "gcs_source", b"gcs_source", "source", b"source"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["error", b"error", "gcs_source", b"gcs_source", "source", b"source"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["source", b"source"]) -> typing.Literal["gcs_source"] | None: ...

global___ImportAptArtifactsErrorInfo = ImportAptArtifactsErrorInfo

@typing.final
class ImportAptArtifactsResponse(google.protobuf.message.Message):
    """The response message from importing APT artifacts."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    APT_ARTIFACTS_FIELD_NUMBER: builtins.int
    ERRORS_FIELD_NUMBER: builtins.int
    @property
    def apt_artifacts(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___AptArtifact]:
        """The Apt artifacts imported."""

    @property
    def errors(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ImportAptArtifactsErrorInfo]:
        """Detailed error info for packages that were not imported."""

    def __init__(
        self,
        *,
        apt_artifacts: collections.abc.Iterable[global___AptArtifact] | None = ...,
        errors: collections.abc.Iterable[global___ImportAptArtifactsErrorInfo] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["apt_artifacts", b"apt_artifacts", "errors", b"errors"]) -> None: ...

global___ImportAptArtifactsResponse = ImportAptArtifactsResponse

@typing.final
class ImportAptArtifactsMetadata(google.protobuf.message.Message):
    """The operation metadata for importing artifacts."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___ImportAptArtifactsMetadata = ImportAptArtifactsMetadata
