"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2024 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.timestamp_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class DockerImage(google.protobuf.message.Message):
    """DockerImage represents a docker artifact.
    The following fields are returned as untyped metadata in the Version
    resource, using camelcase keys (i.e. metadata.imageSizeBytes):
    * imageSizeBytes
    * mediaType
    * buildTime
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    URI_FIELD_NUMBER: builtins.int
    TAGS_FIELD_NUMBER: builtins.int
    IMAGE_SIZE_BYTES_FIELD_NUMBER: builtins.int
    UPLOAD_TIME_FIELD_NUMBER: builtins.int
    MEDIA_TYPE_FIELD_NUMBER: builtins.int
    BUILD_TIME_FIELD_NUMBER: builtins.int
    UPDATE_TIME_FIELD_NUMBER: builtins.int
    name: builtins.str
    """Required. registry_location, project_id, repository_name and image id forms
    a unique image
    name:`projects/<project_id>/locations/<location>/repository/<repository_name>/dockerImages/<docker_image>`.
    For example,
    "projects/test-project/locations/us-west4/repositories/test-repo/dockerImages/
    nginx@sha256:e9954c1fc875017be1c3e36eca16be2d9e9bccc4bf072163515467d6a823c7cf",
    where "us-west4" is the registry_location, "test-project" is the
    project_id, "test-repo" is the repository_name and
    "nginx@sha256:e9954c1fc875017be1c3e36eca16be2d9e9bccc4bf072163515467d6a823c7cf"
    is the image's digest.
    """
    uri: builtins.str
    """Required. URL to access the image.
    Example:
    us-west4-docker.pkg.dev/test-project/test-repo/nginx@sha256:e9954c1fc875017be1c3e36eca16be2d9e9bccc4bf072163515467d6a823c7cf
    """
    image_size_bytes: builtins.int
    """Calculated size of the image.
    This field is returned as the 'metadata.imageSizeBytes' field in the
    Version resource.
    """
    media_type: builtins.str
    """Media type of this image, e.g.
    "application/vnd.docker.distribution.manifest.v2+json".
    This field is returned as the 'metadata.mediaType' field in the
    Version resource.
    """
    @property
    def tags(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Tags attached to this image."""

    @property
    def upload_time(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Time the image was uploaded."""

    @property
    def build_time(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """The time this image was built.
        This field is returned as the 'metadata.buildTime' field in the
        Version resource.
        The build time is returned to the client as an RFC 3339 string, which can
        be easily used with the JavaScript Date constructor.
        """

    @property
    def update_time(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Output only. The time when the docker image was last updated."""

    def __init__(
        self,
        *,
        name: builtins.str = ...,
        uri: builtins.str = ...,
        tags: collections.abc.Iterable[builtins.str] | None = ...,
        image_size_bytes: builtins.int = ...,
        upload_time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        media_type: builtins.str = ...,
        build_time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        update_time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["build_time", b"build_time", "update_time", b"update_time", "upload_time", b"upload_time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["build_time", b"build_time", "image_size_bytes", b"image_size_bytes", "media_type", b"media_type", "name", b"name", "tags", b"tags", "update_time", b"update_time", "upload_time", b"upload_time", "uri", b"uri"]) -> None: ...

global___DockerImage = DockerImage

@typing.final
class ListDockerImagesRequest(google.protobuf.message.Message):
    """The request to list docker images."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PARENT_FIELD_NUMBER: builtins.int
    PAGE_SIZE_FIELD_NUMBER: builtins.int
    PAGE_TOKEN_FIELD_NUMBER: builtins.int
    ORDER_BY_FIELD_NUMBER: builtins.int
    parent: builtins.str
    """Required. The name of the parent resource whose docker images will be
    listed.
    """
    page_size: builtins.int
    """The maximum number of artifacts to return. Maximum page size is 1,000."""
    page_token: builtins.str
    """The next_page_token value returned from a previous list request, if any."""
    order_by: builtins.str
    """The field to order the results by."""
    def __init__(
        self,
        *,
        parent: builtins.str = ...,
        page_size: builtins.int = ...,
        page_token: builtins.str = ...,
        order_by: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["order_by", b"order_by", "page_size", b"page_size", "page_token", b"page_token", "parent", b"parent"]) -> None: ...

global___ListDockerImagesRequest = ListDockerImagesRequest

@typing.final
class ListDockerImagesResponse(google.protobuf.message.Message):
    """The response from listing docker images."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DOCKER_IMAGES_FIELD_NUMBER: builtins.int
    NEXT_PAGE_TOKEN_FIELD_NUMBER: builtins.int
    next_page_token: builtins.str
    """The token to retrieve the next page of artifacts, or empty if there are no
    more artifacts to return.
    """
    @property
    def docker_images(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___DockerImage]:
        """The docker images returned."""

    def __init__(
        self,
        *,
        docker_images: collections.abc.Iterable[global___DockerImage] | None = ...,
        next_page_token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["docker_images", b"docker_images", "next_page_token", b"next_page_token"]) -> None: ...

global___ListDockerImagesResponse = ListDockerImagesResponse

@typing.final
class GetDockerImageRequest(google.protobuf.message.Message):
    """The request to get docker images."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    """Required. The name of the docker images."""
    def __init__(
        self,
        *,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name"]) -> None: ...

global___GetDockerImageRequest = GetDockerImageRequest

@typing.final
class MavenArtifact(google.protobuf.message.Message):
    """MavenArtifact represents a maven artifact."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    POM_URI_FIELD_NUMBER: builtins.int
    GROUP_ID_FIELD_NUMBER: builtins.int
    ARTIFACT_ID_FIELD_NUMBER: builtins.int
    VERSION_FIELD_NUMBER: builtins.int
    CREATE_TIME_FIELD_NUMBER: builtins.int
    UPDATE_TIME_FIELD_NUMBER: builtins.int
    name: builtins.str
    """Required. registry_location, project_id, repository_name and maven_artifact
    forms a unique artifact For example,
    "projects/test-project/locations/us-west4/repositories/test-repo/mavenArtifacts/
    com.google.guava:guava:31.0-jre",
    where "us-west4" is the registry_location, "test-project" is the
    project_id, "test-repo" is the repository_name and
    "com.google.guava:guava:31.0-jre"
    is the maven artifact.
    """
    pom_uri: builtins.str
    """Required. URL to access the pom file of the artifact.
    Example:
    us-west4-maven.pkg.dev/test-project/test-repo/com/google/guava/guava/31.0/guava-31.0.pom
    """
    group_id: builtins.str
    """Group ID for the artifact.
    Example:
    com.google.guava
    """
    artifact_id: builtins.str
    """Artifact ID for the artifact."""
    version: builtins.str
    """Version of this artifact."""
    @property
    def create_time(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Output only. Time the artifact was created."""

    @property
    def update_time(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Output only. Time the artifact was updated."""

    def __init__(
        self,
        *,
        name: builtins.str = ...,
        pom_uri: builtins.str = ...,
        group_id: builtins.str = ...,
        artifact_id: builtins.str = ...,
        version: builtins.str = ...,
        create_time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        update_time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["create_time", b"create_time", "update_time", b"update_time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["artifact_id", b"artifact_id", "create_time", b"create_time", "group_id", b"group_id", "name", b"name", "pom_uri", b"pom_uri", "update_time", b"update_time", "version", b"version"]) -> None: ...

global___MavenArtifact = MavenArtifact

@typing.final
class ListMavenArtifactsRequest(google.protobuf.message.Message):
    """The request to list maven artifacts."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PARENT_FIELD_NUMBER: builtins.int
    PAGE_SIZE_FIELD_NUMBER: builtins.int
    PAGE_TOKEN_FIELD_NUMBER: builtins.int
    parent: builtins.str
    """Required. The name of the parent resource whose maven artifacts will be
    listed.
    """
    page_size: builtins.int
    """The maximum number of artifacts to return. Maximum page size is 1,000."""
    page_token: builtins.str
    """The next_page_token value returned from a previous list request, if any."""
    def __init__(
        self,
        *,
        parent: builtins.str = ...,
        page_size: builtins.int = ...,
        page_token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["page_size", b"page_size", "page_token", b"page_token", "parent", b"parent"]) -> None: ...

global___ListMavenArtifactsRequest = ListMavenArtifactsRequest

@typing.final
class ListMavenArtifactsResponse(google.protobuf.message.Message):
    """The response from listing maven artifacts."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MAVEN_ARTIFACTS_FIELD_NUMBER: builtins.int
    NEXT_PAGE_TOKEN_FIELD_NUMBER: builtins.int
    next_page_token: builtins.str
    """The token to retrieve the next page of artifacts, or empty if there are no
    more artifacts to return.
    """
    @property
    def maven_artifacts(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___MavenArtifact]:
        """The maven artifacts returned."""

    def __init__(
        self,
        *,
        maven_artifacts: collections.abc.Iterable[global___MavenArtifact] | None = ...,
        next_page_token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["maven_artifacts", b"maven_artifacts", "next_page_token", b"next_page_token"]) -> None: ...

global___ListMavenArtifactsResponse = ListMavenArtifactsResponse

@typing.final
class GetMavenArtifactRequest(google.protobuf.message.Message):
    """The request to get maven artifacts."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    """Required. The name of the maven artifact."""
    def __init__(
        self,
        *,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name"]) -> None: ...

global___GetMavenArtifactRequest = GetMavenArtifactRequest

@typing.final
class NpmPackage(google.protobuf.message.Message):
    """NpmPackage represents an npm artifact."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    PACKAGE_NAME_FIELD_NUMBER: builtins.int
    VERSION_FIELD_NUMBER: builtins.int
    TAGS_FIELD_NUMBER: builtins.int
    CREATE_TIME_FIELD_NUMBER: builtins.int
    UPDATE_TIME_FIELD_NUMBER: builtins.int
    name: builtins.str
    """Required. registry_location, project_id, repository_name and npm_package
    forms a unique package For example,
    "projects/test-project/locations/us-west4/repositories/test-repo/npmPackages/
    npm_test:1.0.0",
    where "us-west4" is the registry_location, "test-project" is the
    project_id, "test-repo" is the repository_name and
    npm_test:1.0.0" is the npm package.
    """
    package_name: builtins.str
    """Package for the artifact."""
    version: builtins.str
    """Version of this package."""
    @property
    def tags(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Tags attached to this package."""

    @property
    def create_time(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Output only. Time the package was created."""

    @property
    def update_time(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Output only. Time the package was updated."""

    def __init__(
        self,
        *,
        name: builtins.str = ...,
        package_name: builtins.str = ...,
        version: builtins.str = ...,
        tags: collections.abc.Iterable[builtins.str] | None = ...,
        create_time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        update_time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["create_time", b"create_time", "update_time", b"update_time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["create_time", b"create_time", "name", b"name", "package_name", b"package_name", "tags", b"tags", "update_time", b"update_time", "version", b"version"]) -> None: ...

global___NpmPackage = NpmPackage

@typing.final
class ListNpmPackagesRequest(google.protobuf.message.Message):
    """The request to list npm packages."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PARENT_FIELD_NUMBER: builtins.int
    PAGE_SIZE_FIELD_NUMBER: builtins.int
    PAGE_TOKEN_FIELD_NUMBER: builtins.int
    parent: builtins.str
    """Required. The name of the parent resource whose npm packages will be
    listed.
    """
    page_size: builtins.int
    """The maximum number of artifacts to return. Maximum page size is 1,000."""
    page_token: builtins.str
    """The next_page_token value returned from a previous list request, if any."""
    def __init__(
        self,
        *,
        parent: builtins.str = ...,
        page_size: builtins.int = ...,
        page_token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["page_size", b"page_size", "page_token", b"page_token", "parent", b"parent"]) -> None: ...

global___ListNpmPackagesRequest = ListNpmPackagesRequest

@typing.final
class ListNpmPackagesResponse(google.protobuf.message.Message):
    """The response from listing npm packages."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NPM_PACKAGES_FIELD_NUMBER: builtins.int
    NEXT_PAGE_TOKEN_FIELD_NUMBER: builtins.int
    next_page_token: builtins.str
    """The token to retrieve the next page of artifacts, or empty if there are no
    more artifacts to return.
    """
    @property
    def npm_packages(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___NpmPackage]:
        """The npm packages returned."""

    def __init__(
        self,
        *,
        npm_packages: collections.abc.Iterable[global___NpmPackage] | None = ...,
        next_page_token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["next_page_token", b"next_page_token", "npm_packages", b"npm_packages"]) -> None: ...

global___ListNpmPackagesResponse = ListNpmPackagesResponse

@typing.final
class GetNpmPackageRequest(google.protobuf.message.Message):
    """The request to get npm packages."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    """Required. The name of the npm package."""
    def __init__(
        self,
        *,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name"]) -> None: ...

global___GetNpmPackageRequest = GetNpmPackageRequest

@typing.final
class PythonPackage(google.protobuf.message.Message):
    """PythonPackage represents a python artifact."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    URI_FIELD_NUMBER: builtins.int
    PACKAGE_NAME_FIELD_NUMBER: builtins.int
    VERSION_FIELD_NUMBER: builtins.int
    CREATE_TIME_FIELD_NUMBER: builtins.int
    UPDATE_TIME_FIELD_NUMBER: builtins.int
    name: builtins.str
    """Required. registry_location, project_id, repository_name and python_package
    forms a unique package
    name:`projects/<project_id>/locations/<location>/repository/<repository_name>/pythonPackages/<python_package>`.
    For example,
    "projects/test-project/locations/us-west4/repositories/test-repo/pythonPackages/
    python_package:1.0.0",
    where "us-west4" is the registry_location, "test-project" is the
    project_id, "test-repo" is the repository_name and
    python_package:1.0.0" is the python package.
    """
    uri: builtins.str
    """Required. URL to access the package.
    Example:
    us-west4-python.pkg.dev/test-project/test-repo/python_package/file-name-1.0.0.tar.gz
    """
    package_name: builtins.str
    """Package for the artifact."""
    version: builtins.str
    """Version of this package."""
    @property
    def create_time(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Output only. Time the package was created."""

    @property
    def update_time(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Output only. Time the package was updated."""

    def __init__(
        self,
        *,
        name: builtins.str = ...,
        uri: builtins.str = ...,
        package_name: builtins.str = ...,
        version: builtins.str = ...,
        create_time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        update_time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["create_time", b"create_time", "update_time", b"update_time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["create_time", b"create_time", "name", b"name", "package_name", b"package_name", "update_time", b"update_time", "uri", b"uri", "version", b"version"]) -> None: ...

global___PythonPackage = PythonPackage

@typing.final
class ListPythonPackagesRequest(google.protobuf.message.Message):
    """The request to list python packages."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PARENT_FIELD_NUMBER: builtins.int
    PAGE_SIZE_FIELD_NUMBER: builtins.int
    PAGE_TOKEN_FIELD_NUMBER: builtins.int
    parent: builtins.str
    """Required. The name of the parent resource whose python packages will be
    listed.
    """
    page_size: builtins.int
    """The maximum number of artifacts to return. Maximum page size is 1,000."""
    page_token: builtins.str
    """The next_page_token value returned from a previous list request, if any."""
    def __init__(
        self,
        *,
        parent: builtins.str = ...,
        page_size: builtins.int = ...,
        page_token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["page_size", b"page_size", "page_token", b"page_token", "parent", b"parent"]) -> None: ...

global___ListPythonPackagesRequest = ListPythonPackagesRequest

@typing.final
class ListPythonPackagesResponse(google.protobuf.message.Message):
    """The response from listing python packages."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PYTHON_PACKAGES_FIELD_NUMBER: builtins.int
    NEXT_PAGE_TOKEN_FIELD_NUMBER: builtins.int
    next_page_token: builtins.str
    """The token to retrieve the next page of artifacts, or empty if there are no
    more artifacts to return.
    """
    @property
    def python_packages(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PythonPackage]:
        """The python packages returned."""

    def __init__(
        self,
        *,
        python_packages: collections.abc.Iterable[global___PythonPackage] | None = ...,
        next_page_token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["next_page_token", b"next_page_token", "python_packages", b"python_packages"]) -> None: ...

global___ListPythonPackagesResponse = ListPythonPackagesResponse

@typing.final
class GetPythonPackageRequest(google.protobuf.message.Message):
    """The request to get python packages."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    """Required. The name of the python package."""
    def __init__(
        self,
        *,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name"]) -> None: ...

global___GetPythonPackageRequest = GetPythonPackageRequest
