"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2024 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.field_mask_pb2
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.timestamp_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Package(google.protobuf.message.Message):
    """Packages are named collections of versions."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class AnnotationsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    NAME_FIELD_NUMBER: builtins.int
    DISPLAY_NAME_FIELD_NUMBER: builtins.int
    CREATE_TIME_FIELD_NUMBER: builtins.int
    UPDATE_TIME_FIELD_NUMBER: builtins.int
    ANNOTATIONS_FIELD_NUMBER: builtins.int
    name: builtins.str
    """The name of the package, for example:
    `projects/p1/locations/us-central1/repositories/repo1/packages/pkg1`.
    If the package ID part contains slashes, the slashes are escaped.
    """
    display_name: builtins.str
    """The display name of the package."""
    @property
    def create_time(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """The time when the package was created."""

    @property
    def update_time(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """The time when the package was last updated. This includes publishing a new
        version of the package.
        """

    @property
    def annotations(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]:
        """Optional. Client specified annotations."""

    def __init__(
        self,
        *,
        name: builtins.str = ...,
        display_name: builtins.str = ...,
        create_time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        update_time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        annotations: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["create_time", b"create_time", "update_time", b"update_time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["annotations", b"annotations", "create_time", b"create_time", "display_name", b"display_name", "name", b"name", "update_time", b"update_time"]) -> None: ...

global___Package = Package

@typing.final
class ListPackagesRequest(google.protobuf.message.Message):
    """The request to list packages."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PARENT_FIELD_NUMBER: builtins.int
    PAGE_SIZE_FIELD_NUMBER: builtins.int
    PAGE_TOKEN_FIELD_NUMBER: builtins.int
    FILTER_FIELD_NUMBER: builtins.int
    ORDER_BY_FIELD_NUMBER: builtins.int
    parent: builtins.str
    """Required. The name of the parent resource whose packages will be listed."""
    page_size: builtins.int
    """The maximum number of packages to return. Maximum page size is 1,000."""
    page_token: builtins.str
    """The next_page_token value returned from a previous list request, if any."""
    filter: builtins.str
    """Optional. An expression for filtering the results of the request. Filter
    rules are case insensitive. The fields eligible for filtering are:

      * `name`
      * `annotations`

    Examples of using a filter:

     To filter the results of your request to packages with the name
     `my-package` in project `my-project` in the `us-central` region, in
     repository `my-repo`, append the following filter expression to your
     request:

      * `name="projects/my-project/locations/us-central1/repositories/my-repo/packages/my-package"`

     You can also use wildcards to match any number of characters before or
     after the value:

      * `name="projects/my-project/locations/us-central1/repositories/my-repo/packages/my-*"`
      * `name="projects/my-project/locations/us-central1/repositories/my-repo/packages/*package"`
      * `name="projects/my-project/locations/us-central1/repositories/my-repo/packages/*pack*"`

     To filter the results of your request to packages with the annotation
     key-value pair [`external_link`: `external_link_value`], append the
     following filter expression to your request":

      * `"annotations.external_link:external_link_value"`

     To filter the results just for a specific annotation key `external_link`,
     append the following filter expression to your request:

      * `"annotations.external_link"`

     If the annotation key or value contains special characters, you can escape
     them by surrounding the value with backticks. For example, to filter the
     results of your request to packages with the annotation key-value pair
     [`external.link`:`https://example.com/my-package`], append the following
     filter expression to your request:

      * `` "annotations.`external.link`:`https://example.com/my-package`" ``

     You can also filter with annotations with a wildcard to
     match any number of characters before or after the value:

      * `` "annotations.*_link:`*example.com*`" ``
    """
    order_by: builtins.str
    """Optional. The field to order the results by."""
    def __init__(
        self,
        *,
        parent: builtins.str = ...,
        page_size: builtins.int = ...,
        page_token: builtins.str = ...,
        filter: builtins.str = ...,
        order_by: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["filter", b"filter", "order_by", b"order_by", "page_size", b"page_size", "page_token", b"page_token", "parent", b"parent"]) -> None: ...

global___ListPackagesRequest = ListPackagesRequest

@typing.final
class ListPackagesResponse(google.protobuf.message.Message):
    """The response from listing packages."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PACKAGES_FIELD_NUMBER: builtins.int
    NEXT_PAGE_TOKEN_FIELD_NUMBER: builtins.int
    next_page_token: builtins.str
    """The token to retrieve the next page of packages, or empty if there are no
    more packages to return.
    """
    @property
    def packages(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Package]:
        """The packages returned."""

    def __init__(
        self,
        *,
        packages: collections.abc.Iterable[global___Package] | None = ...,
        next_page_token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["next_page_token", b"next_page_token", "packages", b"packages"]) -> None: ...

global___ListPackagesResponse = ListPackagesResponse

@typing.final
class GetPackageRequest(google.protobuf.message.Message):
    """The request to retrieve a package."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    """Required. The name of the package to retrieve."""
    def __init__(
        self,
        *,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name"]) -> None: ...

global___GetPackageRequest = GetPackageRequest

@typing.final
class DeletePackageRequest(google.protobuf.message.Message):
    """The request to delete a package."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    """Required. The name of the package to delete."""
    def __init__(
        self,
        *,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name"]) -> None: ...

global___DeletePackageRequest = DeletePackageRequest

@typing.final
class UpdatePackageRequest(google.protobuf.message.Message):
    """The request to update a package."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PACKAGE_FIELD_NUMBER: builtins.int
    UPDATE_MASK_FIELD_NUMBER: builtins.int
    @property
    def package(self) -> global___Package:
        """The package that replaces the resource on the server."""

    @property
    def update_mask(self) -> google.protobuf.field_mask_pb2.FieldMask:
        """The update mask applies to the resource. For the `FieldMask` definition,
        see
        https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#fieldmask
        """

    def __init__(
        self,
        *,
        package: global___Package | None = ...,
        update_mask: google.protobuf.field_mask_pb2.FieldMask | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["package", b"package", "update_mask", b"update_mask"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["package", b"package", "update_mask", b"update_mask"]) -> None: ...

global___UpdatePackageRequest = UpdatePackageRequest
