"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2024 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.duration_pb2
import google.protobuf.field_mask_pb2
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class UpstreamPolicy(google.protobuf.message.Message):
    """Artifact policy configuration for the repository contents."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    REPOSITORY_FIELD_NUMBER: builtins.int
    PRIORITY_FIELD_NUMBER: builtins.int
    id: builtins.str
    """The user-provided ID of the upstream policy."""
    repository: builtins.str
    """A reference to the repository resource, for example:
    `projects/p1/locations/us-central1/repositories/repo1`.
    """
    priority: builtins.int
    """Entries with a greater priority value take precedence in the pull order."""
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        repository: builtins.str = ...,
        priority: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["id", b"id", "priority", b"priority", "repository", b"repository"]) -> None: ...

global___UpstreamPolicy = UpstreamPolicy

@typing.final
class CleanupPolicyCondition(google.protobuf.message.Message):
    """CleanupPolicyCondition is a set of conditions attached to a CleanupPolicy.
    If multiple entries are set, all must be satisfied for the condition to be
    satisfied.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _TagState:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _TagStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[CleanupPolicyCondition._TagState.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        TAG_STATE_UNSPECIFIED: CleanupPolicyCondition._TagState.ValueType  # 0
        """Tag status not specified."""
        TAGGED: CleanupPolicyCondition._TagState.ValueType  # 1
        """Applies to tagged versions only."""
        UNTAGGED: CleanupPolicyCondition._TagState.ValueType  # 2
        """Applies to untagged versions only."""
        ANY: CleanupPolicyCondition._TagState.ValueType  # 3
        """Applies to all versions."""

    class TagState(_TagState, metaclass=_TagStateEnumTypeWrapper):
        """Statuses applying to versions."""

    TAG_STATE_UNSPECIFIED: CleanupPolicyCondition.TagState.ValueType  # 0
    """Tag status not specified."""
    TAGGED: CleanupPolicyCondition.TagState.ValueType  # 1
    """Applies to tagged versions only."""
    UNTAGGED: CleanupPolicyCondition.TagState.ValueType  # 2
    """Applies to untagged versions only."""
    ANY: CleanupPolicyCondition.TagState.ValueType  # 3
    """Applies to all versions."""

    TAG_STATE_FIELD_NUMBER: builtins.int
    TAG_PREFIXES_FIELD_NUMBER: builtins.int
    VERSION_NAME_PREFIXES_FIELD_NUMBER: builtins.int
    PACKAGE_NAME_PREFIXES_FIELD_NUMBER: builtins.int
    OLDER_THAN_FIELD_NUMBER: builtins.int
    NEWER_THAN_FIELD_NUMBER: builtins.int
    tag_state: global___CleanupPolicyCondition.TagState.ValueType
    """Match versions by tag status."""
    @property
    def tag_prefixes(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Match versions by tag prefix. Applied on any prefix match."""

    @property
    def version_name_prefixes(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Match versions by version name prefix. Applied on any prefix match."""

    @property
    def package_name_prefixes(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Match versions by package prefix. Applied on any prefix match."""

    @property
    def older_than(self) -> google.protobuf.duration_pb2.Duration:
        """Match versions older than a duration."""

    @property
    def newer_than(self) -> google.protobuf.duration_pb2.Duration:
        """Match versions newer than a duration."""

    def __init__(
        self,
        *,
        tag_state: global___CleanupPolicyCondition.TagState.ValueType | None = ...,
        tag_prefixes: collections.abc.Iterable[builtins.str] | None = ...,
        version_name_prefixes: collections.abc.Iterable[builtins.str] | None = ...,
        package_name_prefixes: collections.abc.Iterable[builtins.str] | None = ...,
        older_than: google.protobuf.duration_pb2.Duration | None = ...,
        newer_than: google.protobuf.duration_pb2.Duration | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_newer_than", b"_newer_than", "_older_than", b"_older_than", "_tag_state", b"_tag_state", "newer_than", b"newer_than", "older_than", b"older_than", "tag_state", b"tag_state"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_newer_than", b"_newer_than", "_older_than", b"_older_than", "_tag_state", b"_tag_state", "newer_than", b"newer_than", "older_than", b"older_than", "package_name_prefixes", b"package_name_prefixes", "tag_prefixes", b"tag_prefixes", "tag_state", b"tag_state", "version_name_prefixes", b"version_name_prefixes"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_newer_than", b"_newer_than"]) -> typing.Literal["newer_than"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_older_than", b"_older_than"]) -> typing.Literal["older_than"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_tag_state", b"_tag_state"]) -> typing.Literal["tag_state"] | None: ...

global___CleanupPolicyCondition = CleanupPolicyCondition

@typing.final
class CleanupPolicyMostRecentVersions(google.protobuf.message.Message):
    """CleanupPolicyMostRecentVersions is an alternate condition of a CleanupPolicy
    for retaining a minimum number of versions.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PACKAGE_NAME_PREFIXES_FIELD_NUMBER: builtins.int
    KEEP_COUNT_FIELD_NUMBER: builtins.int
    keep_count: builtins.int
    """Minimum number of versions to keep."""
    @property
    def package_name_prefixes(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """List of package name prefixes that will apply this rule."""

    def __init__(
        self,
        *,
        package_name_prefixes: collections.abc.Iterable[builtins.str] | None = ...,
        keep_count: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_keep_count", b"_keep_count", "keep_count", b"keep_count"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_keep_count", b"_keep_count", "keep_count", b"keep_count", "package_name_prefixes", b"package_name_prefixes"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_keep_count", b"_keep_count"]) -> typing.Literal["keep_count"] | None: ...

global___CleanupPolicyMostRecentVersions = CleanupPolicyMostRecentVersions

@typing.final
class CleanupPolicy(google.protobuf.message.Message):
    """Artifact policy configuration for repository cleanup policies."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Action:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _ActionEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[CleanupPolicy._Action.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        ACTION_UNSPECIFIED: CleanupPolicy._Action.ValueType  # 0
        """Action not specified."""
        DELETE: CleanupPolicy._Action.ValueType  # 1
        """Delete action."""
        KEEP: CleanupPolicy._Action.ValueType  # 2
        """Keep action."""

    class Action(_Action, metaclass=_ActionEnumTypeWrapper):
        """Action type for a cleanup policy."""

    ACTION_UNSPECIFIED: CleanupPolicy.Action.ValueType  # 0
    """Action not specified."""
    DELETE: CleanupPolicy.Action.ValueType  # 1
    """Delete action."""
    KEEP: CleanupPolicy.Action.ValueType  # 2
    """Keep action."""

    CONDITION_FIELD_NUMBER: builtins.int
    MOST_RECENT_VERSIONS_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    ACTION_FIELD_NUMBER: builtins.int
    id: builtins.str
    """The user-provided ID of the cleanup policy."""
    action: global___CleanupPolicy.Action.ValueType
    """Policy action."""
    @property
    def condition(self) -> global___CleanupPolicyCondition:
        """Policy condition for matching versions."""

    @property
    def most_recent_versions(self) -> global___CleanupPolicyMostRecentVersions:
        """Policy condition for retaining a minimum number of versions. May only be
        specified with a Keep action.
        """

    def __init__(
        self,
        *,
        condition: global___CleanupPolicyCondition | None = ...,
        most_recent_versions: global___CleanupPolicyMostRecentVersions | None = ...,
        id: builtins.str = ...,
        action: global___CleanupPolicy.Action.ValueType = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["condition", b"condition", "condition_type", b"condition_type", "most_recent_versions", b"most_recent_versions"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["action", b"action", "condition", b"condition", "condition_type", b"condition_type", "id", b"id", "most_recent_versions", b"most_recent_versions"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["condition_type", b"condition_type"]) -> typing.Literal["condition", "most_recent_versions"] | None: ...

global___CleanupPolicy = CleanupPolicy

@typing.final
class VirtualRepositoryConfig(google.protobuf.message.Message):
    """Virtual repository configuration."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    UPSTREAM_POLICIES_FIELD_NUMBER: builtins.int
    @property
    def upstream_policies(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___UpstreamPolicy]:
        """Policies that configure the upstream artifacts distributed by the Virtual
        Repository. Upstream policies cannot be set on a standard repository.
        """

    def __init__(
        self,
        *,
        upstream_policies: collections.abc.Iterable[global___UpstreamPolicy] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["upstream_policies", b"upstream_policies"]) -> None: ...

global___VirtualRepositoryConfig = VirtualRepositoryConfig

@typing.final
class RemoteRepositoryConfig(google.protobuf.message.Message):
    """Remote repository configuration."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class UpstreamCredentials(google.protobuf.message.Message):
        """The credentials to access the remote repository."""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        @typing.final
        class UsernamePasswordCredentials(google.protobuf.message.Message):
            """Username and password credentials."""

            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            USERNAME_FIELD_NUMBER: builtins.int
            PASSWORD_SECRET_VERSION_FIELD_NUMBER: builtins.int
            username: builtins.str
            """The username to access the remote repository."""
            password_secret_version: builtins.str
            """The Secret Manager key version that holds the password to access the
            remote repository. Must be in the format of
            `projects/{project}/secrets/{secret}/versions/{version}`.
            """
            def __init__(
                self,
                *,
                username: builtins.str = ...,
                password_secret_version: builtins.str = ...,
            ) -> None: ...
            def ClearField(self, field_name: typing.Literal["password_secret_version", b"password_secret_version", "username", b"username"]) -> None: ...

        USERNAME_PASSWORD_CREDENTIALS_FIELD_NUMBER: builtins.int
        @property
        def username_password_credentials(self) -> global___RemoteRepositoryConfig.UpstreamCredentials.UsernamePasswordCredentials:
            """Use username and password to access the remote repository."""

        def __init__(
            self,
            *,
            username_password_credentials: global___RemoteRepositoryConfig.UpstreamCredentials.UsernamePasswordCredentials | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["credentials", b"credentials", "username_password_credentials", b"username_password_credentials"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["credentials", b"credentials", "username_password_credentials", b"username_password_credentials"]) -> None: ...
        def WhichOneof(self, oneof_group: typing.Literal["credentials", b"credentials"]) -> typing.Literal["username_password_credentials"] | None: ...

    @typing.final
    class DockerRepository(google.protobuf.message.Message):
        """Configuration for a Docker remote repository."""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        class _PublicRepository:
            ValueType = typing.NewType("ValueType", builtins.int)
            V: typing_extensions.TypeAlias = ValueType

        class _PublicRepositoryEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[RemoteRepositoryConfig.DockerRepository._PublicRepository.ValueType], builtins.type):
            DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
            PUBLIC_REPOSITORY_UNSPECIFIED: RemoteRepositoryConfig.DockerRepository._PublicRepository.ValueType  # 0
            """Unspecified repository."""
            DOCKER_HUB: RemoteRepositoryConfig.DockerRepository._PublicRepository.ValueType  # 1
            """Docker Hub."""

        class PublicRepository(_PublicRepository, metaclass=_PublicRepositoryEnumTypeWrapper):
            """Predefined list of publicly available Docker repositories like Docker
            Hub.
            """

        PUBLIC_REPOSITORY_UNSPECIFIED: RemoteRepositoryConfig.DockerRepository.PublicRepository.ValueType  # 0
        """Unspecified repository."""
        DOCKER_HUB: RemoteRepositoryConfig.DockerRepository.PublicRepository.ValueType  # 1
        """Docker Hub."""

        @typing.final
        class CustomRepository(google.protobuf.message.Message):
            """Customer-specified publicly available remote repository."""

            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            URI_FIELD_NUMBER: builtins.int
            uri: builtins.str
            """An http/https uri reference to the custom remote repository, for ex:
            "https://registry-1.docker.io".
            """
            def __init__(
                self,
                *,
                uri: builtins.str = ...,
            ) -> None: ...
            def ClearField(self, field_name: typing.Literal["uri", b"uri"]) -> None: ...

        PUBLIC_REPOSITORY_FIELD_NUMBER: builtins.int
        CUSTOM_REPOSITORY_FIELD_NUMBER: builtins.int
        public_repository: global___RemoteRepositoryConfig.DockerRepository.PublicRepository.ValueType
        """One of the publicly available Docker repositories supported by Artifact
        Registry.
        """
        @property
        def custom_repository(self) -> global___RemoteRepositoryConfig.DockerRepository.CustomRepository:
            """Customer-specified remote repository."""

        def __init__(
            self,
            *,
            public_repository: global___RemoteRepositoryConfig.DockerRepository.PublicRepository.ValueType = ...,
            custom_repository: global___RemoteRepositoryConfig.DockerRepository.CustomRepository | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["custom_repository", b"custom_repository", "public_repository", b"public_repository", "upstream", b"upstream"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["custom_repository", b"custom_repository", "public_repository", b"public_repository", "upstream", b"upstream"]) -> None: ...
        def WhichOneof(self, oneof_group: typing.Literal["upstream", b"upstream"]) -> typing.Literal["public_repository", "custom_repository"] | None: ...

    @typing.final
    class MavenRepository(google.protobuf.message.Message):
        """Configuration for a Maven remote repository."""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        class _PublicRepository:
            ValueType = typing.NewType("ValueType", builtins.int)
            V: typing_extensions.TypeAlias = ValueType

        class _PublicRepositoryEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[RemoteRepositoryConfig.MavenRepository._PublicRepository.ValueType], builtins.type):
            DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
            PUBLIC_REPOSITORY_UNSPECIFIED: RemoteRepositoryConfig.MavenRepository._PublicRepository.ValueType  # 0
            """Unspecified repository."""
            MAVEN_CENTRAL: RemoteRepositoryConfig.MavenRepository._PublicRepository.ValueType  # 1
            """Maven Central."""

        class PublicRepository(_PublicRepository, metaclass=_PublicRepositoryEnumTypeWrapper):
            """Predefined list of publicly available Maven repositories like Maven
            Central.
            """

        PUBLIC_REPOSITORY_UNSPECIFIED: RemoteRepositoryConfig.MavenRepository.PublicRepository.ValueType  # 0
        """Unspecified repository."""
        MAVEN_CENTRAL: RemoteRepositoryConfig.MavenRepository.PublicRepository.ValueType  # 1
        """Maven Central."""

        @typing.final
        class CustomRepository(google.protobuf.message.Message):
            """Customer-specified publicly available remote repository."""

            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            URI_FIELD_NUMBER: builtins.int
            uri: builtins.str
            """An http/https uri reference to the upstream remote repository, for ex:
            "https://my.maven.registry/".
            """
            def __init__(
                self,
                *,
                uri: builtins.str = ...,
            ) -> None: ...
            def ClearField(self, field_name: typing.Literal["uri", b"uri"]) -> None: ...

        PUBLIC_REPOSITORY_FIELD_NUMBER: builtins.int
        CUSTOM_REPOSITORY_FIELD_NUMBER: builtins.int
        public_repository: global___RemoteRepositoryConfig.MavenRepository.PublicRepository.ValueType
        """One of the publicly available Maven repositories supported by Artifact
        Registry.
        """
        @property
        def custom_repository(self) -> global___RemoteRepositoryConfig.MavenRepository.CustomRepository:
            """Customer-specified remote repository."""

        def __init__(
            self,
            *,
            public_repository: global___RemoteRepositoryConfig.MavenRepository.PublicRepository.ValueType = ...,
            custom_repository: global___RemoteRepositoryConfig.MavenRepository.CustomRepository | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["custom_repository", b"custom_repository", "public_repository", b"public_repository", "upstream", b"upstream"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["custom_repository", b"custom_repository", "public_repository", b"public_repository", "upstream", b"upstream"]) -> None: ...
        def WhichOneof(self, oneof_group: typing.Literal["upstream", b"upstream"]) -> typing.Literal["public_repository", "custom_repository"] | None: ...

    @typing.final
    class NpmRepository(google.protobuf.message.Message):
        """Configuration for a Npm remote repository."""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        class _PublicRepository:
            ValueType = typing.NewType("ValueType", builtins.int)
            V: typing_extensions.TypeAlias = ValueType

        class _PublicRepositoryEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[RemoteRepositoryConfig.NpmRepository._PublicRepository.ValueType], builtins.type):
            DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
            PUBLIC_REPOSITORY_UNSPECIFIED: RemoteRepositoryConfig.NpmRepository._PublicRepository.ValueType  # 0
            """Unspecified repository."""
            NPMJS: RemoteRepositoryConfig.NpmRepository._PublicRepository.ValueType  # 1
            """npmjs."""

        class PublicRepository(_PublicRepository, metaclass=_PublicRepositoryEnumTypeWrapper):
            """Predefined list of publicly available NPM repositories like npmjs."""

        PUBLIC_REPOSITORY_UNSPECIFIED: RemoteRepositoryConfig.NpmRepository.PublicRepository.ValueType  # 0
        """Unspecified repository."""
        NPMJS: RemoteRepositoryConfig.NpmRepository.PublicRepository.ValueType  # 1
        """npmjs."""

        @typing.final
        class CustomRepository(google.protobuf.message.Message):
            """Customer-specified publicly available remote repository."""

            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            URI_FIELD_NUMBER: builtins.int
            uri: builtins.str
            """An http/https uri reference to the upstream remote repository, for ex:
            "https://my.npm.registry/".
            """
            def __init__(
                self,
                *,
                uri: builtins.str = ...,
            ) -> None: ...
            def ClearField(self, field_name: typing.Literal["uri", b"uri"]) -> None: ...

        PUBLIC_REPOSITORY_FIELD_NUMBER: builtins.int
        CUSTOM_REPOSITORY_FIELD_NUMBER: builtins.int
        public_repository: global___RemoteRepositoryConfig.NpmRepository.PublicRepository.ValueType
        """One of the publicly available Npm repositories supported by Artifact
        Registry.
        """
        @property
        def custom_repository(self) -> global___RemoteRepositoryConfig.NpmRepository.CustomRepository:
            """Customer-specified remote repository."""

        def __init__(
            self,
            *,
            public_repository: global___RemoteRepositoryConfig.NpmRepository.PublicRepository.ValueType = ...,
            custom_repository: global___RemoteRepositoryConfig.NpmRepository.CustomRepository | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["custom_repository", b"custom_repository", "public_repository", b"public_repository", "upstream", b"upstream"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["custom_repository", b"custom_repository", "public_repository", b"public_repository", "upstream", b"upstream"]) -> None: ...
        def WhichOneof(self, oneof_group: typing.Literal["upstream", b"upstream"]) -> typing.Literal["public_repository", "custom_repository"] | None: ...

    @typing.final
    class PythonRepository(google.protobuf.message.Message):
        """Configuration for a Python remote repository."""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        class _PublicRepository:
            ValueType = typing.NewType("ValueType", builtins.int)
            V: typing_extensions.TypeAlias = ValueType

        class _PublicRepositoryEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[RemoteRepositoryConfig.PythonRepository._PublicRepository.ValueType], builtins.type):
            DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
            PUBLIC_REPOSITORY_UNSPECIFIED: RemoteRepositoryConfig.PythonRepository._PublicRepository.ValueType  # 0
            """Unspecified repository."""
            PYPI: RemoteRepositoryConfig.PythonRepository._PublicRepository.ValueType  # 1
            """PyPI."""

        class PublicRepository(_PublicRepository, metaclass=_PublicRepositoryEnumTypeWrapper):
            """Predefined list of publicly available Python repositories like PyPI.org."""

        PUBLIC_REPOSITORY_UNSPECIFIED: RemoteRepositoryConfig.PythonRepository.PublicRepository.ValueType  # 0
        """Unspecified repository."""
        PYPI: RemoteRepositoryConfig.PythonRepository.PublicRepository.ValueType  # 1
        """PyPI."""

        @typing.final
        class CustomRepository(google.protobuf.message.Message):
            """Customer-specified publicly available remote repository."""

            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            URI_FIELD_NUMBER: builtins.int
            uri: builtins.str
            """An http/https uri reference to the upstream remote repository, for ex:
            "https://my.python.registry/".
            """
            def __init__(
                self,
                *,
                uri: builtins.str = ...,
            ) -> None: ...
            def ClearField(self, field_name: typing.Literal["uri", b"uri"]) -> None: ...

        PUBLIC_REPOSITORY_FIELD_NUMBER: builtins.int
        CUSTOM_REPOSITORY_FIELD_NUMBER: builtins.int
        public_repository: global___RemoteRepositoryConfig.PythonRepository.PublicRepository.ValueType
        """One of the publicly available Python repositories supported by Artifact
        Registry.
        """
        @property
        def custom_repository(self) -> global___RemoteRepositoryConfig.PythonRepository.CustomRepository:
            """Customer-specified remote repository."""

        def __init__(
            self,
            *,
            public_repository: global___RemoteRepositoryConfig.PythonRepository.PublicRepository.ValueType = ...,
            custom_repository: global___RemoteRepositoryConfig.PythonRepository.CustomRepository | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["custom_repository", b"custom_repository", "public_repository", b"public_repository", "upstream", b"upstream"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["custom_repository", b"custom_repository", "public_repository", b"public_repository", "upstream", b"upstream"]) -> None: ...
        def WhichOneof(self, oneof_group: typing.Literal["upstream", b"upstream"]) -> typing.Literal["public_repository", "custom_repository"] | None: ...

    @typing.final
    class AptRepository(google.protobuf.message.Message):
        """Configuration for an Apt remote repository."""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        @typing.final
        class PublicRepository(google.protobuf.message.Message):
            """Publicly available Apt repositories constructed from a common repository
            base and a custom repository path.
            """

            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            class _RepositoryBase:
                ValueType = typing.NewType("ValueType", builtins.int)
                V: typing_extensions.TypeAlias = ValueType

            class _RepositoryBaseEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[RemoteRepositoryConfig.AptRepository.PublicRepository._RepositoryBase.ValueType], builtins.type):
                DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
                REPOSITORY_BASE_UNSPECIFIED: RemoteRepositoryConfig.AptRepository.PublicRepository._RepositoryBase.ValueType  # 0
                """Unspecified repository base."""
                DEBIAN: RemoteRepositoryConfig.AptRepository.PublicRepository._RepositoryBase.ValueType  # 1
                """Debian."""
                UBUNTU: RemoteRepositoryConfig.AptRepository.PublicRepository._RepositoryBase.ValueType  # 2
                """Ubuntu LTS/Pro."""
                DEBIAN_SNAPSHOT: RemoteRepositoryConfig.AptRepository.PublicRepository._RepositoryBase.ValueType  # 3
                """Archived Debian."""

            class RepositoryBase(_RepositoryBase, metaclass=_RepositoryBaseEnumTypeWrapper):
                """Predefined list of publicly available repository bases for Apt."""

            REPOSITORY_BASE_UNSPECIFIED: RemoteRepositoryConfig.AptRepository.PublicRepository.RepositoryBase.ValueType  # 0
            """Unspecified repository base."""
            DEBIAN: RemoteRepositoryConfig.AptRepository.PublicRepository.RepositoryBase.ValueType  # 1
            """Debian."""
            UBUNTU: RemoteRepositoryConfig.AptRepository.PublicRepository.RepositoryBase.ValueType  # 2
            """Ubuntu LTS/Pro."""
            DEBIAN_SNAPSHOT: RemoteRepositoryConfig.AptRepository.PublicRepository.RepositoryBase.ValueType  # 3
            """Archived Debian."""

            REPOSITORY_BASE_FIELD_NUMBER: builtins.int
            REPOSITORY_PATH_FIELD_NUMBER: builtins.int
            repository_base: global___RemoteRepositoryConfig.AptRepository.PublicRepository.RepositoryBase.ValueType
            """A common public repository base for Apt."""
            repository_path: builtins.str
            """A custom field to define a path to a specific repository from the base."""
            def __init__(
                self,
                *,
                repository_base: global___RemoteRepositoryConfig.AptRepository.PublicRepository.RepositoryBase.ValueType = ...,
                repository_path: builtins.str = ...,
            ) -> None: ...
            def ClearField(self, field_name: typing.Literal["repository_base", b"repository_base", "repository_path", b"repository_path"]) -> None: ...

        @typing.final
        class CustomRepository(google.protobuf.message.Message):
            """Customer-specified publicly available remote repository."""

            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            URI_FIELD_NUMBER: builtins.int
            uri: builtins.str
            """An http/https uri reference to the upstream remote repository, for ex:
            "https://my.apt.registry/".
            """
            def __init__(
                self,
                *,
                uri: builtins.str = ...,
            ) -> None: ...
            def ClearField(self, field_name: typing.Literal["uri", b"uri"]) -> None: ...

        PUBLIC_REPOSITORY_FIELD_NUMBER: builtins.int
        CUSTOM_REPOSITORY_FIELD_NUMBER: builtins.int
        @property
        def public_repository(self) -> global___RemoteRepositoryConfig.AptRepository.PublicRepository:
            """One of the publicly available Apt repositories supported by Artifact
            Registry.
            """

        @property
        def custom_repository(self) -> global___RemoteRepositoryConfig.AptRepository.CustomRepository:
            """Customer-specified remote repository."""

        def __init__(
            self,
            *,
            public_repository: global___RemoteRepositoryConfig.AptRepository.PublicRepository | None = ...,
            custom_repository: global___RemoteRepositoryConfig.AptRepository.CustomRepository | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["custom_repository", b"custom_repository", "public_repository", b"public_repository", "upstream", b"upstream"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["custom_repository", b"custom_repository", "public_repository", b"public_repository", "upstream", b"upstream"]) -> None: ...
        def WhichOneof(self, oneof_group: typing.Literal["upstream", b"upstream"]) -> typing.Literal["public_repository", "custom_repository"] | None: ...

    @typing.final
    class YumRepository(google.protobuf.message.Message):
        """Configuration for a Yum remote repository."""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        @typing.final
        class PublicRepository(google.protobuf.message.Message):
            """Publicly available Yum repositories constructed from a common repository
            base and a custom repository path.
            """

            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            class _RepositoryBase:
                ValueType = typing.NewType("ValueType", builtins.int)
                V: typing_extensions.TypeAlias = ValueType

            class _RepositoryBaseEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[RemoteRepositoryConfig.YumRepository.PublicRepository._RepositoryBase.ValueType], builtins.type):
                DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
                REPOSITORY_BASE_UNSPECIFIED: RemoteRepositoryConfig.YumRepository.PublicRepository._RepositoryBase.ValueType  # 0
                """Unspecified repository base."""
                CENTOS: RemoteRepositoryConfig.YumRepository.PublicRepository._RepositoryBase.ValueType  # 1
                """CentOS."""
                CENTOS_DEBUG: RemoteRepositoryConfig.YumRepository.PublicRepository._RepositoryBase.ValueType  # 2
                """CentOS Debug."""
                CENTOS_VAULT: RemoteRepositoryConfig.YumRepository.PublicRepository._RepositoryBase.ValueType  # 3
                """CentOS Vault."""
                CENTOS_STREAM: RemoteRepositoryConfig.YumRepository.PublicRepository._RepositoryBase.ValueType  # 4
                """CentOS Stream."""
                ROCKY: RemoteRepositoryConfig.YumRepository.PublicRepository._RepositoryBase.ValueType  # 5
                """Rocky."""
                EPEL: RemoteRepositoryConfig.YumRepository.PublicRepository._RepositoryBase.ValueType  # 6
                """Fedora Extra Packages for Enterprise Linux (EPEL)."""

            class RepositoryBase(_RepositoryBase, metaclass=_RepositoryBaseEnumTypeWrapper):
                """Predefined list of publicly available repository bases for Yum."""

            REPOSITORY_BASE_UNSPECIFIED: RemoteRepositoryConfig.YumRepository.PublicRepository.RepositoryBase.ValueType  # 0
            """Unspecified repository base."""
            CENTOS: RemoteRepositoryConfig.YumRepository.PublicRepository.RepositoryBase.ValueType  # 1
            """CentOS."""
            CENTOS_DEBUG: RemoteRepositoryConfig.YumRepository.PublicRepository.RepositoryBase.ValueType  # 2
            """CentOS Debug."""
            CENTOS_VAULT: RemoteRepositoryConfig.YumRepository.PublicRepository.RepositoryBase.ValueType  # 3
            """CentOS Vault."""
            CENTOS_STREAM: RemoteRepositoryConfig.YumRepository.PublicRepository.RepositoryBase.ValueType  # 4
            """CentOS Stream."""
            ROCKY: RemoteRepositoryConfig.YumRepository.PublicRepository.RepositoryBase.ValueType  # 5
            """Rocky."""
            EPEL: RemoteRepositoryConfig.YumRepository.PublicRepository.RepositoryBase.ValueType  # 6
            """Fedora Extra Packages for Enterprise Linux (EPEL)."""

            REPOSITORY_BASE_FIELD_NUMBER: builtins.int
            REPOSITORY_PATH_FIELD_NUMBER: builtins.int
            repository_base: global___RemoteRepositoryConfig.YumRepository.PublicRepository.RepositoryBase.ValueType
            """A common public repository base for Yum."""
            repository_path: builtins.str
            """A custom field to define a path to a specific repository from the base."""
            def __init__(
                self,
                *,
                repository_base: global___RemoteRepositoryConfig.YumRepository.PublicRepository.RepositoryBase.ValueType = ...,
                repository_path: builtins.str = ...,
            ) -> None: ...
            def ClearField(self, field_name: typing.Literal["repository_base", b"repository_base", "repository_path", b"repository_path"]) -> None: ...

        @typing.final
        class CustomRepository(google.protobuf.message.Message):
            """Customer-specified publicly available remote repository."""

            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            URI_FIELD_NUMBER: builtins.int
            uri: builtins.str
            """An http/https uri reference to the upstream remote repository, for ex:
            "https://my.yum.registry/".
            """
            def __init__(
                self,
                *,
                uri: builtins.str = ...,
            ) -> None: ...
            def ClearField(self, field_name: typing.Literal["uri", b"uri"]) -> None: ...

        PUBLIC_REPOSITORY_FIELD_NUMBER: builtins.int
        CUSTOM_REPOSITORY_FIELD_NUMBER: builtins.int
        @property
        def public_repository(self) -> global___RemoteRepositoryConfig.YumRepository.PublicRepository:
            """One of the publicly available Yum repositories supported by Artifact
            Registry.
            """

        @property
        def custom_repository(self) -> global___RemoteRepositoryConfig.YumRepository.CustomRepository:
            """Customer-specified remote repository."""

        def __init__(
            self,
            *,
            public_repository: global___RemoteRepositoryConfig.YumRepository.PublicRepository | None = ...,
            custom_repository: global___RemoteRepositoryConfig.YumRepository.CustomRepository | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["custom_repository", b"custom_repository", "public_repository", b"public_repository", "upstream", b"upstream"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["custom_repository", b"custom_repository", "public_repository", b"public_repository", "upstream", b"upstream"]) -> None: ...
        def WhichOneof(self, oneof_group: typing.Literal["upstream", b"upstream"]) -> typing.Literal["public_repository", "custom_repository"] | None: ...

    @typing.final
    class CommonRemoteRepository(google.protobuf.message.Message):
        """Common remote repository settings type."""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        URI_FIELD_NUMBER: builtins.int
        uri: builtins.str
        """Required. A common public repository base for remote repository."""
        def __init__(
            self,
            *,
            uri: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["uri", b"uri"]) -> None: ...

    DOCKER_REPOSITORY_FIELD_NUMBER: builtins.int
    MAVEN_REPOSITORY_FIELD_NUMBER: builtins.int
    NPM_REPOSITORY_FIELD_NUMBER: builtins.int
    PYTHON_REPOSITORY_FIELD_NUMBER: builtins.int
    APT_REPOSITORY_FIELD_NUMBER: builtins.int
    YUM_REPOSITORY_FIELD_NUMBER: builtins.int
    COMMON_REPOSITORY_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    UPSTREAM_CREDENTIALS_FIELD_NUMBER: builtins.int
    DISABLE_UPSTREAM_VALIDATION_FIELD_NUMBER: builtins.int
    description: builtins.str
    """The description of the remote source."""
    disable_upstream_validation: builtins.bool
    """Input only. A create/update remote repo option to avoid making a HEAD/GET
    request to validate a remote repo and any supplied upstream credentials.
    """
    @property
    def docker_repository(self) -> global___RemoteRepositoryConfig.DockerRepository:
        """Specific settings for a Docker remote repository."""

    @property
    def maven_repository(self) -> global___RemoteRepositoryConfig.MavenRepository:
        """Specific settings for a Maven remote repository."""

    @property
    def npm_repository(self) -> global___RemoteRepositoryConfig.NpmRepository:
        """Specific settings for an Npm remote repository."""

    @property
    def python_repository(self) -> global___RemoteRepositoryConfig.PythonRepository:
        """Specific settings for a Python remote repository."""

    @property
    def apt_repository(self) -> global___RemoteRepositoryConfig.AptRepository:
        """Specific settings for an Apt remote repository."""

    @property
    def yum_repository(self) -> global___RemoteRepositoryConfig.YumRepository:
        """Specific settings for a Yum remote repository."""

    @property
    def common_repository(self) -> global___RemoteRepositoryConfig.CommonRemoteRepository:
        """Common remote repository settings.
        Used as the remote repository upstream URL.
        """

    @property
    def upstream_credentials(self) -> global___RemoteRepositoryConfig.UpstreamCredentials:
        """Optional. The credentials used to access the remote repository."""

    def __init__(
        self,
        *,
        docker_repository: global___RemoteRepositoryConfig.DockerRepository | None = ...,
        maven_repository: global___RemoteRepositoryConfig.MavenRepository | None = ...,
        npm_repository: global___RemoteRepositoryConfig.NpmRepository | None = ...,
        python_repository: global___RemoteRepositoryConfig.PythonRepository | None = ...,
        apt_repository: global___RemoteRepositoryConfig.AptRepository | None = ...,
        yum_repository: global___RemoteRepositoryConfig.YumRepository | None = ...,
        common_repository: global___RemoteRepositoryConfig.CommonRemoteRepository | None = ...,
        description: builtins.str = ...,
        upstream_credentials: global___RemoteRepositoryConfig.UpstreamCredentials | None = ...,
        disable_upstream_validation: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["apt_repository", b"apt_repository", "common_repository", b"common_repository", "docker_repository", b"docker_repository", "maven_repository", b"maven_repository", "npm_repository", b"npm_repository", "python_repository", b"python_repository", "remote_source", b"remote_source", "upstream_credentials", b"upstream_credentials", "yum_repository", b"yum_repository"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["apt_repository", b"apt_repository", "common_repository", b"common_repository", "description", b"description", "disable_upstream_validation", b"disable_upstream_validation", "docker_repository", b"docker_repository", "maven_repository", b"maven_repository", "npm_repository", b"npm_repository", "python_repository", b"python_repository", "remote_source", b"remote_source", "upstream_credentials", b"upstream_credentials", "yum_repository", b"yum_repository"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["remote_source", b"remote_source"]) -> typing.Literal["docker_repository", "maven_repository", "npm_repository", "python_repository", "apt_repository", "yum_repository", "common_repository"] | None: ...

global___RemoteRepositoryConfig = RemoteRepositoryConfig

@typing.final
class Repository(google.protobuf.message.Message):
    """A Repository for storing artifacts with a specific format."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Format:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _FormatEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Repository._Format.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        FORMAT_UNSPECIFIED: Repository._Format.ValueType  # 0
        """Unspecified package format."""
        DOCKER: Repository._Format.ValueType  # 1
        """Docker package format."""
        MAVEN: Repository._Format.ValueType  # 2
        """Maven package format."""
        NPM: Repository._Format.ValueType  # 3
        """NPM package format."""
        APT: Repository._Format.ValueType  # 5
        """APT package format."""
        YUM: Repository._Format.ValueType  # 6
        """YUM package format."""
        PYTHON: Repository._Format.ValueType  # 8
        """Python package format."""
        KFP: Repository._Format.ValueType  # 9
        """Kubeflow Pipelines package format."""
        GO: Repository._Format.ValueType  # 10
        """Go package format."""
        GENERIC: Repository._Format.ValueType  # 11
        """Generic package format."""

    class Format(_Format, metaclass=_FormatEnumTypeWrapper):
        """A package format."""

    FORMAT_UNSPECIFIED: Repository.Format.ValueType  # 0
    """Unspecified package format."""
    DOCKER: Repository.Format.ValueType  # 1
    """Docker package format."""
    MAVEN: Repository.Format.ValueType  # 2
    """Maven package format."""
    NPM: Repository.Format.ValueType  # 3
    """NPM package format."""
    APT: Repository.Format.ValueType  # 5
    """APT package format."""
    YUM: Repository.Format.ValueType  # 6
    """YUM package format."""
    PYTHON: Repository.Format.ValueType  # 8
    """Python package format."""
    KFP: Repository.Format.ValueType  # 9
    """Kubeflow Pipelines package format."""
    GO: Repository.Format.ValueType  # 10
    """Go package format."""
    GENERIC: Repository.Format.ValueType  # 11
    """Generic package format."""

    class _Mode:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _ModeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Repository._Mode.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        MODE_UNSPECIFIED: Repository._Mode.ValueType  # 0
        """Unspecified mode."""
        STANDARD_REPOSITORY: Repository._Mode.ValueType  # 1
        """A standard repository storing artifacts."""
        VIRTUAL_REPOSITORY: Repository._Mode.ValueType  # 2
        """A virtual repository to serve artifacts from one or more sources."""
        REMOTE_REPOSITORY: Repository._Mode.ValueType  # 3
        """A remote repository to serve artifacts from a remote source."""

    class Mode(_Mode, metaclass=_ModeEnumTypeWrapper):
        """The mode configures the repository to serve artifacts from different
        sources.
        """

    MODE_UNSPECIFIED: Repository.Mode.ValueType  # 0
    """Unspecified mode."""
    STANDARD_REPOSITORY: Repository.Mode.ValueType  # 1
    """A standard repository storing artifacts."""
    VIRTUAL_REPOSITORY: Repository.Mode.ValueType  # 2
    """A virtual repository to serve artifacts from one or more sources."""
    REMOTE_REPOSITORY: Repository.Mode.ValueType  # 3
    """A remote repository to serve artifacts from a remote source."""

    @typing.final
    class MavenRepositoryConfig(google.protobuf.message.Message):
        """MavenRepositoryConfig is maven related repository details.
        Provides additional configuration details for repositories of the maven
        format type.
        """

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        class _VersionPolicy:
            ValueType = typing.NewType("ValueType", builtins.int)
            V: typing_extensions.TypeAlias = ValueType

        class _VersionPolicyEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Repository.MavenRepositoryConfig._VersionPolicy.ValueType], builtins.type):
            DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
            VERSION_POLICY_UNSPECIFIED: Repository.MavenRepositoryConfig._VersionPolicy.ValueType  # 0
            """VERSION_POLICY_UNSPECIFIED - the version policy is not defined.
            When the version policy is not defined, no validation is performed
            for the versions.
            """
            RELEASE: Repository.MavenRepositoryConfig._VersionPolicy.ValueType  # 1
            """RELEASE - repository will accept only Release versions."""
            SNAPSHOT: Repository.MavenRepositoryConfig._VersionPolicy.ValueType  # 2
            """SNAPSHOT - repository will accept only Snapshot versions."""

        class VersionPolicy(_VersionPolicy, metaclass=_VersionPolicyEnumTypeWrapper):
            """VersionPolicy is the version policy for the repository."""

        VERSION_POLICY_UNSPECIFIED: Repository.MavenRepositoryConfig.VersionPolicy.ValueType  # 0
        """VERSION_POLICY_UNSPECIFIED - the version policy is not defined.
        When the version policy is not defined, no validation is performed
        for the versions.
        """
        RELEASE: Repository.MavenRepositoryConfig.VersionPolicy.ValueType  # 1
        """RELEASE - repository will accept only Release versions."""
        SNAPSHOT: Repository.MavenRepositoryConfig.VersionPolicy.ValueType  # 2
        """SNAPSHOT - repository will accept only Snapshot versions."""

        ALLOW_SNAPSHOT_OVERWRITES_FIELD_NUMBER: builtins.int
        VERSION_POLICY_FIELD_NUMBER: builtins.int
        allow_snapshot_overwrites: builtins.bool
        """The repository with this flag will allow publishing
        the same snapshot versions.
        """
        version_policy: global___Repository.MavenRepositoryConfig.VersionPolicy.ValueType
        """Version policy defines the versions that the registry will accept."""
        def __init__(
            self,
            *,
            allow_snapshot_overwrites: builtins.bool = ...,
            version_policy: global___Repository.MavenRepositoryConfig.VersionPolicy.ValueType = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["allow_snapshot_overwrites", b"allow_snapshot_overwrites", "version_policy", b"version_policy"]) -> None: ...

    @typing.final
    class DockerRepositoryConfig(google.protobuf.message.Message):
        """DockerRepositoryConfig is docker related repository details.
        Provides additional configuration details for repositories of the docker
        format type.
        """

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        IMMUTABLE_TAGS_FIELD_NUMBER: builtins.int
        immutable_tags: builtins.bool
        """The repository which enabled this flag prevents all tags from being
        modified, moved or deleted. This does not prevent tags from being
        created.
        """
        def __init__(
            self,
            *,
            immutable_tags: builtins.bool = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["immutable_tags", b"immutable_tags"]) -> None: ...

    @typing.final
    class VulnerabilityScanningConfig(google.protobuf.message.Message):
        """Config on whether to perform vulnerability scanning for resources in this
        repository, as well as output fields describing current state.
        """

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        class _EnablementConfig:
            ValueType = typing.NewType("ValueType", builtins.int)
            V: typing_extensions.TypeAlias = ValueType

        class _EnablementConfigEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Repository.VulnerabilityScanningConfig._EnablementConfig.ValueType], builtins.type):
            DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
            ENABLEMENT_CONFIG_UNSPECIFIED: Repository.VulnerabilityScanningConfig._EnablementConfig.ValueType  # 0
            """Not set. This will be treated as INHERITED."""
            INHERITED: Repository.VulnerabilityScanningConfig._EnablementConfig.ValueType  # 1
            """Scanning is Enabled, but dependent on API enablement."""
            DISABLED: Repository.VulnerabilityScanningConfig._EnablementConfig.ValueType  # 2
            """No automatic vulnerability scanning will be performed for this
            repository.
            """

        class EnablementConfig(_EnablementConfig, metaclass=_EnablementConfigEnumTypeWrapper):
            """Config for vulnerability scanning of resources in this repository."""

        ENABLEMENT_CONFIG_UNSPECIFIED: Repository.VulnerabilityScanningConfig.EnablementConfig.ValueType  # 0
        """Not set. This will be treated as INHERITED."""
        INHERITED: Repository.VulnerabilityScanningConfig.EnablementConfig.ValueType  # 1
        """Scanning is Enabled, but dependent on API enablement."""
        DISABLED: Repository.VulnerabilityScanningConfig.EnablementConfig.ValueType  # 2
        """No automatic vulnerability scanning will be performed for this
        repository.
        """

        class _EnablementState:
            ValueType = typing.NewType("ValueType", builtins.int)
            V: typing_extensions.TypeAlias = ValueType

        class _EnablementStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Repository.VulnerabilityScanningConfig._EnablementState.ValueType], builtins.type):
            DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
            ENABLEMENT_STATE_UNSPECIFIED: Repository.VulnerabilityScanningConfig._EnablementState.ValueType  # 0
            """Enablement state is unclear."""
            SCANNING_UNSUPPORTED: Repository.VulnerabilityScanningConfig._EnablementState.ValueType  # 1
            """Repository does not support vulnerability scanning."""
            SCANNING_DISABLED: Repository.VulnerabilityScanningConfig._EnablementState.ValueType  # 2
            """Vulnerability scanning is disabled for this repository."""
            SCANNING_ACTIVE: Repository.VulnerabilityScanningConfig._EnablementState.ValueType  # 3
            """Vulnerability scanning is active for this repository."""

        class EnablementState(_EnablementState, metaclass=_EnablementStateEnumTypeWrapper):
            """Describes the state of vulnerability scanning in this repository,
            including both repository enablement and API enablement.
            """

        ENABLEMENT_STATE_UNSPECIFIED: Repository.VulnerabilityScanningConfig.EnablementState.ValueType  # 0
        """Enablement state is unclear."""
        SCANNING_UNSUPPORTED: Repository.VulnerabilityScanningConfig.EnablementState.ValueType  # 1
        """Repository does not support vulnerability scanning."""
        SCANNING_DISABLED: Repository.VulnerabilityScanningConfig.EnablementState.ValueType  # 2
        """Vulnerability scanning is disabled for this repository."""
        SCANNING_ACTIVE: Repository.VulnerabilityScanningConfig.EnablementState.ValueType  # 3
        """Vulnerability scanning is active for this repository."""

        ENABLEMENT_CONFIG_FIELD_NUMBER: builtins.int
        LAST_ENABLE_TIME_FIELD_NUMBER: builtins.int
        ENABLEMENT_STATE_FIELD_NUMBER: builtins.int
        ENABLEMENT_STATE_REASON_FIELD_NUMBER: builtins.int
        enablement_config: global___Repository.VulnerabilityScanningConfig.EnablementConfig.ValueType
        """Optional. Config for whether this repository has vulnerability scanning
        disabled.
        """
        enablement_state: global___Repository.VulnerabilityScanningConfig.EnablementState.ValueType
        """Output only. State of feature enablement, combining repository enablement
        config and API enablement state.
        """
        enablement_state_reason: builtins.str
        """Output only. Reason for the repository state."""
        @property
        def last_enable_time(self) -> google.protobuf.timestamp_pb2.Timestamp:
            """Output only. The last time this repository config was enabled."""

        def __init__(
            self,
            *,
            enablement_config: global___Repository.VulnerabilityScanningConfig.EnablementConfig.ValueType = ...,
            last_enable_time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
            enablement_state: global___Repository.VulnerabilityScanningConfig.EnablementState.ValueType = ...,
            enablement_state_reason: builtins.str = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["last_enable_time", b"last_enable_time"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["enablement_config", b"enablement_config", "enablement_state", b"enablement_state", "enablement_state_reason", b"enablement_state_reason", "last_enable_time", b"last_enable_time"]) -> None: ...

    @typing.final
    class LabelsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    @typing.final
    class CleanupPoliciesEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> global___CleanupPolicy: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: global___CleanupPolicy | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    MAVEN_CONFIG_FIELD_NUMBER: builtins.int
    DOCKER_CONFIG_FIELD_NUMBER: builtins.int
    VIRTUAL_REPOSITORY_CONFIG_FIELD_NUMBER: builtins.int
    REMOTE_REPOSITORY_CONFIG_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    FORMAT_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    LABELS_FIELD_NUMBER: builtins.int
    CREATE_TIME_FIELD_NUMBER: builtins.int
    UPDATE_TIME_FIELD_NUMBER: builtins.int
    KMS_KEY_NAME_FIELD_NUMBER: builtins.int
    MODE_FIELD_NUMBER: builtins.int
    CLEANUP_POLICIES_FIELD_NUMBER: builtins.int
    SIZE_BYTES_FIELD_NUMBER: builtins.int
    SATISFIES_PZS_FIELD_NUMBER: builtins.int
    CLEANUP_POLICY_DRY_RUN_FIELD_NUMBER: builtins.int
    VULNERABILITY_SCANNING_CONFIG_FIELD_NUMBER: builtins.int
    DISALLOW_UNSPECIFIED_MODE_FIELD_NUMBER: builtins.int
    SATISFIES_PZI_FIELD_NUMBER: builtins.int
    name: builtins.str
    """The name of the repository, for example:
    `projects/p1/locations/us-central1/repositories/repo1`. For each location
    in a project, repository names must be unique.
    """
    format: global___Repository.Format.ValueType
    """Optional. The format of packages that are stored in the repository."""
    description: builtins.str
    """The user-provided description of the repository."""
    kms_key_name: builtins.str
    """The Cloud KMS resource name of the customer managed encryption key that's
    used to encrypt the contents of the Repository. Has the form:
    `projects/my-project/locations/my-region/keyRings/my-kr/cryptoKeys/my-key`.
    This value may not be changed after the Repository has been created.
    """
    mode: global___Repository.Mode.ValueType
    """Optional. The mode of the repository."""
    size_bytes: builtins.int
    """Output only. The size, in bytes, of all artifact storage in this
    repository. Repositories that are generally available or in public preview
     use this to calculate storage costs.
    """
    satisfies_pzs: builtins.bool
    """Output only. If set, the repository satisfies physical zone separation."""
    cleanup_policy_dry_run: builtins.bool
    """Optional. If true, the cleanup pipeline is prevented from deleting versions
    in this repository.
    """
    disallow_unspecified_mode: builtins.bool
    """Optional. If this is true, an unspecified repo type will be treated as
    error rather than defaulting to standard.
    """
    satisfies_pzi: builtins.bool
    """Output only. If set, the repository satisfies physical zone isolation."""
    @property
    def maven_config(self) -> global___Repository.MavenRepositoryConfig:
        """Maven repository config contains repository level configuration
        for the repositories of maven type.
        """

    @property
    def docker_config(self) -> global___Repository.DockerRepositoryConfig:
        """Docker repository config contains repository level configuration
        for the repositories of docker type.
        """

    @property
    def virtual_repository_config(self) -> global___VirtualRepositoryConfig:
        """Configuration specific for a Virtual Repository."""

    @property
    def remote_repository_config(self) -> global___RemoteRepositoryConfig:
        """Configuration specific for a Remote Repository."""

    @property
    def labels(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]:
        """Labels with user-defined metadata.
        This field may contain up to 64 entries. Label keys and values may be no
        longer than 63 characters. Label keys must begin with a lowercase letter
        and may only contain lowercase letters, numeric characters, underscores,
        and dashes.
        """

    @property
    def create_time(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Output only. The time when the repository was created."""

    @property
    def update_time(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Output only. The time when the repository was last updated."""

    @property
    def cleanup_policies(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___CleanupPolicy]:
        """Optional. Cleanup policies for this repository. Cleanup policies indicate
        when certain package versions can be automatically deleted. Map keys are
        policy IDs supplied by users during policy creation. They must unique
        within a repository and be under 128 characters in length.
        """

    @property
    def vulnerability_scanning_config(self) -> global___Repository.VulnerabilityScanningConfig:
        """Optional. Config and state for vulnerability scanning of resources within
        this Repository.
        """

    def __init__(
        self,
        *,
        maven_config: global___Repository.MavenRepositoryConfig | None = ...,
        docker_config: global___Repository.DockerRepositoryConfig | None = ...,
        virtual_repository_config: global___VirtualRepositoryConfig | None = ...,
        remote_repository_config: global___RemoteRepositoryConfig | None = ...,
        name: builtins.str = ...,
        format: global___Repository.Format.ValueType = ...,
        description: builtins.str = ...,
        labels: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        create_time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        update_time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        kms_key_name: builtins.str = ...,
        mode: global___Repository.Mode.ValueType = ...,
        cleanup_policies: collections.abc.Mapping[builtins.str, global___CleanupPolicy] | None = ...,
        size_bytes: builtins.int = ...,
        satisfies_pzs: builtins.bool = ...,
        cleanup_policy_dry_run: builtins.bool = ...,
        vulnerability_scanning_config: global___Repository.VulnerabilityScanningConfig | None = ...,
        disallow_unspecified_mode: builtins.bool = ...,
        satisfies_pzi: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["create_time", b"create_time", "docker_config", b"docker_config", "format_config", b"format_config", "maven_config", b"maven_config", "mode_config", b"mode_config", "remote_repository_config", b"remote_repository_config", "update_time", b"update_time", "virtual_repository_config", b"virtual_repository_config", "vulnerability_scanning_config", b"vulnerability_scanning_config"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["cleanup_policies", b"cleanup_policies", "cleanup_policy_dry_run", b"cleanup_policy_dry_run", "create_time", b"create_time", "description", b"description", "disallow_unspecified_mode", b"disallow_unspecified_mode", "docker_config", b"docker_config", "format", b"format", "format_config", b"format_config", "kms_key_name", b"kms_key_name", "labels", b"labels", "maven_config", b"maven_config", "mode", b"mode", "mode_config", b"mode_config", "name", b"name", "remote_repository_config", b"remote_repository_config", "satisfies_pzi", b"satisfies_pzi", "satisfies_pzs", b"satisfies_pzs", "size_bytes", b"size_bytes", "update_time", b"update_time", "virtual_repository_config", b"virtual_repository_config", "vulnerability_scanning_config", b"vulnerability_scanning_config"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["format_config", b"format_config"]) -> typing.Literal["maven_config", "docker_config"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["mode_config", b"mode_config"]) -> typing.Literal["virtual_repository_config", "remote_repository_config"] | None: ...

global___Repository = Repository

@typing.final
class ListRepositoriesRequest(google.protobuf.message.Message):
    """The request to list repositories."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PARENT_FIELD_NUMBER: builtins.int
    PAGE_SIZE_FIELD_NUMBER: builtins.int
    PAGE_TOKEN_FIELD_NUMBER: builtins.int
    FILTER_FIELD_NUMBER: builtins.int
    ORDER_BY_FIELD_NUMBER: builtins.int
    parent: builtins.str
    """Required. The name of the parent resource whose repositories will be
    listed.
    """
    page_size: builtins.int
    """The maximum number of repositories to return. Maximum page size is 1,000."""
    page_token: builtins.str
    """The next_page_token value returned from a previous list request, if any."""
    filter: builtins.str
    """Optional. An expression for filtering the results of the request. Filter
    rules are case insensitive. The fields eligible for filtering are:

      * `name`

     Examples of using a filter:

    To filter the results of your request to repositories with the name
    `my-repo` in project `my-project` in the `us-central` region, append the
    following filter expression to your request:

      * `name="projects/my-project/locations/us-central1/repositories/my-repo"`

     You can also use wildcards to match any number of characters before or
     after the value:

      * `name="projects/my-project/locations/us-central1/repositories/my-*"`
      * `name="projects/my-project/locations/us-central1/repositories/*repo"`
      * `name="projects/my-project/locations/us-central1/repositories/*repo*"`
    """
    order_by: builtins.str
    """Optional. The field to order the results by."""
    def __init__(
        self,
        *,
        parent: builtins.str = ...,
        page_size: builtins.int = ...,
        page_token: builtins.str = ...,
        filter: builtins.str = ...,
        order_by: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["filter", b"filter", "order_by", b"order_by", "page_size", b"page_size", "page_token", b"page_token", "parent", b"parent"]) -> None: ...

global___ListRepositoriesRequest = ListRepositoriesRequest

@typing.final
class ListRepositoriesResponse(google.protobuf.message.Message):
    """The response from listing repositories."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REPOSITORIES_FIELD_NUMBER: builtins.int
    NEXT_PAGE_TOKEN_FIELD_NUMBER: builtins.int
    next_page_token: builtins.str
    """The token to retrieve the next page of repositories, or empty if there are
    no more repositories to return.
    """
    @property
    def repositories(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Repository]:
        """The repositories returned."""

    def __init__(
        self,
        *,
        repositories: collections.abc.Iterable[global___Repository] | None = ...,
        next_page_token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["next_page_token", b"next_page_token", "repositories", b"repositories"]) -> None: ...

global___ListRepositoriesResponse = ListRepositoriesResponse

@typing.final
class GetRepositoryRequest(google.protobuf.message.Message):
    """The request to retrieve a repository."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    """Required. The name of the repository to retrieve."""
    def __init__(
        self,
        *,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name"]) -> None: ...

global___GetRepositoryRequest = GetRepositoryRequest

@typing.final
class CreateRepositoryRequest(google.protobuf.message.Message):
    """The request to create a new repository."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PARENT_FIELD_NUMBER: builtins.int
    REPOSITORY_ID_FIELD_NUMBER: builtins.int
    REPOSITORY_FIELD_NUMBER: builtins.int
    parent: builtins.str
    """Required. The name of the parent resource where the repository will be
    created.
    """
    repository_id: builtins.str
    """Required. The repository id to use for this repository."""
    @property
    def repository(self) -> global___Repository:
        """Required. The repository to be created."""

    def __init__(
        self,
        *,
        parent: builtins.str = ...,
        repository_id: builtins.str = ...,
        repository: global___Repository | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["repository", b"repository"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["parent", b"parent", "repository", b"repository", "repository_id", b"repository_id"]) -> None: ...

global___CreateRepositoryRequest = CreateRepositoryRequest

@typing.final
class UpdateRepositoryRequest(google.protobuf.message.Message):
    """The request to update a repository."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REPOSITORY_FIELD_NUMBER: builtins.int
    UPDATE_MASK_FIELD_NUMBER: builtins.int
    @property
    def repository(self) -> global___Repository:
        """The repository that replaces the resource on the server."""

    @property
    def update_mask(self) -> google.protobuf.field_mask_pb2.FieldMask:
        """The update mask applies to the resource. For the `FieldMask` definition,
        see
        https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#fieldmask
        """

    def __init__(
        self,
        *,
        repository: global___Repository | None = ...,
        update_mask: google.protobuf.field_mask_pb2.FieldMask | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["repository", b"repository", "update_mask", b"update_mask"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["repository", b"repository", "update_mask", b"update_mask"]) -> None: ...

global___UpdateRepositoryRequest = UpdateRepositoryRequest

@typing.final
class DeleteRepositoryRequest(google.protobuf.message.Message):
    """The request to delete a repository."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    """Required. The name of the repository to delete."""
    def __init__(
        self,
        *,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name"]) -> None: ...

global___DeleteRepositoryRequest = DeleteRepositoryRequest
