"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2024 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.field_mask_pb2
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ProjectSettings(google.protobuf.message.Message):
    """The Artifact Registry settings that apply to a Project."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _RedirectionState:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _RedirectionStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ProjectSettings._RedirectionState.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        REDIRECTION_STATE_UNSPECIFIED: ProjectSettings._RedirectionState.ValueType  # 0
        """No redirection status has been set."""
        REDIRECTION_FROM_GCR_IO_DISABLED: ProjectSettings._RedirectionState.ValueType  # 1
        """Redirection is disabled."""
        REDIRECTION_FROM_GCR_IO_ENABLED: ProjectSettings._RedirectionState.ValueType  # 2
        """Redirection is enabled."""
        REDIRECTION_FROM_GCR_IO_FINALIZED: ProjectSettings._RedirectionState.ValueType  # 3
        """Redirection is enabled, and has been finalized so cannot be reverted."""
        REDIRECTION_FROM_GCR_IO_ENABLED_AND_COPYING: ProjectSettings._RedirectionState.ValueType  # 5
        """Redirection is enabled and missing images are copied from GCR"""
        REDIRECTION_FROM_GCR_IO_PARTIAL_AND_COPYING: ProjectSettings._RedirectionState.ValueType  # 6
        """Redirection is partially enabled and missing images are copied from GCR"""

    class RedirectionState(_RedirectionState, metaclass=_RedirectionStateEnumTypeWrapper):
        """The possible redirection states for legacy repositories."""

    REDIRECTION_STATE_UNSPECIFIED: ProjectSettings.RedirectionState.ValueType  # 0
    """No redirection status has been set."""
    REDIRECTION_FROM_GCR_IO_DISABLED: ProjectSettings.RedirectionState.ValueType  # 1
    """Redirection is disabled."""
    REDIRECTION_FROM_GCR_IO_ENABLED: ProjectSettings.RedirectionState.ValueType  # 2
    """Redirection is enabled."""
    REDIRECTION_FROM_GCR_IO_FINALIZED: ProjectSettings.RedirectionState.ValueType  # 3
    """Redirection is enabled, and has been finalized so cannot be reverted."""
    REDIRECTION_FROM_GCR_IO_ENABLED_AND_COPYING: ProjectSettings.RedirectionState.ValueType  # 5
    """Redirection is enabled and missing images are copied from GCR"""
    REDIRECTION_FROM_GCR_IO_PARTIAL_AND_COPYING: ProjectSettings.RedirectionState.ValueType  # 6
    """Redirection is partially enabled and missing images are copied from GCR"""

    NAME_FIELD_NUMBER: builtins.int
    LEGACY_REDIRECTION_STATE_FIELD_NUMBER: builtins.int
    PULL_PERCENT_FIELD_NUMBER: builtins.int
    name: builtins.str
    """The name of the project's settings.

    Always of the form:
    projects/{project-id}/projectSettings

    In update request: never set
    In response: always set
    """
    legacy_redirection_state: global___ProjectSettings.RedirectionState.ValueType
    """The redirection state of the legacy repositories in this project."""
    pull_percent: builtins.int
    """The percentage of pull traffic to redirect from GCR to AR when using
    partial redirection.
    """
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        legacy_redirection_state: global___ProjectSettings.RedirectionState.ValueType = ...,
        pull_percent: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["legacy_redirection_state", b"legacy_redirection_state", "name", b"name", "pull_percent", b"pull_percent"]) -> None: ...

global___ProjectSettings = ProjectSettings

@typing.final
class GetProjectSettingsRequest(google.protobuf.message.Message):
    """Gets the redirection status for a project."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    """Required. The name of the projectSettings resource."""
    def __init__(
        self,
        *,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name"]) -> None: ...

global___GetProjectSettingsRequest = GetProjectSettingsRequest

@typing.final
class UpdateProjectSettingsRequest(google.protobuf.message.Message):
    """Sets the settings of the project."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PROJECT_SETTINGS_FIELD_NUMBER: builtins.int
    UPDATE_MASK_FIELD_NUMBER: builtins.int
    @property
    def project_settings(self) -> global___ProjectSettings:
        """The project settings."""

    @property
    def update_mask(self) -> google.protobuf.field_mask_pb2.FieldMask:
        """Field mask to support partial updates."""

    def __init__(
        self,
        *,
        project_settings: global___ProjectSettings | None = ...,
        update_mask: google.protobuf.field_mask_pb2.FieldMask | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["project_settings", b"project_settings", "update_mask", b"update_mask"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["project_settings", b"project_settings", "update_mask", b"update_mask"]) -> None: ...

global___UpdateProjectSettingsRequest = UpdateProjectSettingsRequest
