"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2024 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.field_mask_pb2
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Tag(google.protobuf.message.Message):
    """Tags point to a version and represent an alternative name that can be used
    to access the version.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    VERSION_FIELD_NUMBER: builtins.int
    name: builtins.str
    """The name of the tag, for example:
    "projects/p1/locations/us-central1/repositories/repo1/packages/pkg1/tags/tag1".
    If the package part contains slashes, the slashes are escaped.
    The tag part can only have characters in [a-zA-Z0-9\\-._~:@], anything else
    must be URL encoded.
    """
    version: builtins.str
    """The name of the version the tag refers to, for example:
    `projects/p1/locations/us-central1/repositories/repo1/packages/pkg1/versions/sha256:5243811`
    If the package or version ID parts contain slashes, the slashes are
    escaped.
    """
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        version: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name", "version", b"version"]) -> None: ...

global___Tag = Tag

@typing.final
class ListTagsRequest(google.protobuf.message.Message):
    """The request to list tags."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PARENT_FIELD_NUMBER: builtins.int
    FILTER_FIELD_NUMBER: builtins.int
    PAGE_SIZE_FIELD_NUMBER: builtins.int
    PAGE_TOKEN_FIELD_NUMBER: builtins.int
    parent: builtins.str
    """The name of the parent package whose tags will be listed.
    For example:
    `projects/p1/locations/us-central1/repositories/repo1/packages/pkg1`.
    """
    filter: builtins.str
    """An expression for filtering the results of the request. Filter rules are
    case insensitive. The fields eligible for filtering are:

      * `name`
      * `version`

     Examples of using a filter:

     To filter the results of your request to tags with the name `my-tag` in
     package `my-package` in repository `my-repo` in project "`y-project` in
     the us-central region, append the following filter expression to your
     request:

      * `name="projects/my-project/locations/us-central1/repositories/my-repo/packages/my-package/tags/my-tag"`

     You can also use wildcards to match any number of characters before or
     after the value:

      * `name="projects/my-project/locations/us-central1/repositories/my-repo/packages/my-package/tags/my*"`
      * `name="projects/my-project/locations/us-central1/repositories/my-repo/packages/my-package/tags/*tag"`
      * `name="projects/my-project/locations/us-central1/repositories/my-repo/packages/my-package/tags/*tag*"`

     To filter the results of your request to tags applied to the version
     `1.0` in package `my-package`, append the following filter expression to
     your request:

      * `version="projects/my-project/locations/us-central1/repositories/my-repo/packages/my-package/versions/1.0"`
    """
    page_size: builtins.int
    """The maximum number of tags to return. Maximum page size is 1,000."""
    page_token: builtins.str
    """The next_page_token value returned from a previous list request, if any."""
    def __init__(
        self,
        *,
        parent: builtins.str = ...,
        filter: builtins.str = ...,
        page_size: builtins.int = ...,
        page_token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["filter", b"filter", "page_size", b"page_size", "page_token", b"page_token", "parent", b"parent"]) -> None: ...

global___ListTagsRequest = ListTagsRequest

@typing.final
class ListTagsResponse(google.protobuf.message.Message):
    """The response from listing tags."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TAGS_FIELD_NUMBER: builtins.int
    NEXT_PAGE_TOKEN_FIELD_NUMBER: builtins.int
    next_page_token: builtins.str
    """The token to retrieve the next page of tags, or empty if there are no
    more tags to return.
    """
    @property
    def tags(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Tag]:
        """The tags returned."""

    def __init__(
        self,
        *,
        tags: collections.abc.Iterable[global___Tag] | None = ...,
        next_page_token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["next_page_token", b"next_page_token", "tags", b"tags"]) -> None: ...

global___ListTagsResponse = ListTagsResponse

@typing.final
class GetTagRequest(google.protobuf.message.Message):
    """The request to retrieve a tag."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    """The name of the tag to retrieve."""
    def __init__(
        self,
        *,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name"]) -> None: ...

global___GetTagRequest = GetTagRequest

@typing.final
class CreateTagRequest(google.protobuf.message.Message):
    """The request to create a new tag."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PARENT_FIELD_NUMBER: builtins.int
    TAG_ID_FIELD_NUMBER: builtins.int
    TAG_FIELD_NUMBER: builtins.int
    parent: builtins.str
    """The name of the parent resource where the tag will be created."""
    tag_id: builtins.str
    """The tag id to use for this repository."""
    @property
    def tag(self) -> global___Tag:
        """The tag to be created."""

    def __init__(
        self,
        *,
        parent: builtins.str = ...,
        tag_id: builtins.str = ...,
        tag: global___Tag | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["tag", b"tag"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["parent", b"parent", "tag", b"tag", "tag_id", b"tag_id"]) -> None: ...

global___CreateTagRequest = CreateTagRequest

@typing.final
class UpdateTagRequest(google.protobuf.message.Message):
    """The request to create or update a tag."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TAG_FIELD_NUMBER: builtins.int
    UPDATE_MASK_FIELD_NUMBER: builtins.int
    @property
    def tag(self) -> global___Tag:
        """The tag that replaces the resource on the server."""

    @property
    def update_mask(self) -> google.protobuf.field_mask_pb2.FieldMask:
        """The update mask applies to the resource. For the `FieldMask` definition,
        see
        https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#fieldmask
        """

    def __init__(
        self,
        *,
        tag: global___Tag | None = ...,
        update_mask: google.protobuf.field_mask_pb2.FieldMask | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["tag", b"tag", "update_mask", b"update_mask"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["tag", b"tag", "update_mask", b"update_mask"]) -> None: ...

global___UpdateTagRequest = UpdateTagRequest

@typing.final
class DeleteTagRequest(google.protobuf.message.Message):
    """The request to delete a tag."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    """The name of the tag to delete."""
    def __init__(
        self,
        *,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name"]) -> None: ...

global___DeleteTagRequest = DeleteTagRequest
