# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from osprey.rpc.pigeon.tests.v1 import tests_pb2 as osprey_dot_rpc_dot_pigeon_dot_tests_dot_v1_dot_tests__pb2


class TestServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ScalarRoutingValue = channel.unary_unary(
                '/osprey.rpc.pigeon.tests.v1.TestService/ScalarRoutingValue',
                request_serializer=osprey_dot_rpc_dot_pigeon_dot_tests_dot_v1_dot_tests__pb2.ScalarRoutingValueRequest.SerializeToString,
                response_deserializer=osprey_dot_rpc_dot_pigeon_dot_tests_dot_v1_dot_tests__pb2.ScalarRoutingValueResponse.FromString,
                )
        self.ListRoutingValue = channel.unary_unary(
                '/osprey.rpc.pigeon.tests.v1.TestService/ListRoutingValue',
                request_serializer=osprey_dot_rpc_dot_pigeon_dot_tests_dot_v1_dot_tests__pb2.ListRoutingValueRequest.SerializeToString,
                response_deserializer=osprey_dot_rpc_dot_pigeon_dot_tests_dot_v1_dot_tests__pb2.ListRoutingValueResponse.FromString,
                )
        self.MapRoutingValue = channel.unary_unary(
                '/osprey.rpc.pigeon.tests.v1.TestService/MapRoutingValue',
                request_serializer=osprey_dot_rpc_dot_pigeon_dot_tests_dot_v1_dot_tests__pb2.MapRoutingValueRequest.SerializeToString,
                response_deserializer=osprey_dot_rpc_dot_pigeon_dot_tests_dot_v1_dot_tests__pb2.MapRoutingValueResponse.FromString,
                )
        self.MapMessageRoutingValue = channel.unary_unary(
                '/osprey.rpc.pigeon.tests.v1.TestService/MapMessageRoutingValue',
                request_serializer=osprey_dot_rpc_dot_pigeon_dot_tests_dot_v1_dot_tests__pb2.MapMessageRoutingValueRequest.SerializeToString,
                response_deserializer=osprey_dot_rpc_dot_pigeon_dot_tests_dot_v1_dot_tests__pb2.MapMessageRoutingValueResponse.FromString,
                )


class TestServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ScalarRoutingValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRoutingValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MapRoutingValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MapMessageRoutingValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TestServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ScalarRoutingValue': grpc.unary_unary_rpc_method_handler(
                    servicer.ScalarRoutingValue,
                    request_deserializer=osprey_dot_rpc_dot_pigeon_dot_tests_dot_v1_dot_tests__pb2.ScalarRoutingValueRequest.FromString,
                    response_serializer=osprey_dot_rpc_dot_pigeon_dot_tests_dot_v1_dot_tests__pb2.ScalarRoutingValueResponse.SerializeToString,
            ),
            'ListRoutingValue': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRoutingValue,
                    request_deserializer=osprey_dot_rpc_dot_pigeon_dot_tests_dot_v1_dot_tests__pb2.ListRoutingValueRequest.FromString,
                    response_serializer=osprey_dot_rpc_dot_pigeon_dot_tests_dot_v1_dot_tests__pb2.ListRoutingValueResponse.SerializeToString,
            ),
            'MapRoutingValue': grpc.unary_unary_rpc_method_handler(
                    servicer.MapRoutingValue,
                    request_deserializer=osprey_dot_rpc_dot_pigeon_dot_tests_dot_v1_dot_tests__pb2.MapRoutingValueRequest.FromString,
                    response_serializer=osprey_dot_rpc_dot_pigeon_dot_tests_dot_v1_dot_tests__pb2.MapRoutingValueResponse.SerializeToString,
            ),
            'MapMessageRoutingValue': grpc.unary_unary_rpc_method_handler(
                    servicer.MapMessageRoutingValue,
                    request_deserializer=osprey_dot_rpc_dot_pigeon_dot_tests_dot_v1_dot_tests__pb2.MapMessageRoutingValueRequest.FromString,
                    response_serializer=osprey_dot_rpc_dot_pigeon_dot_tests_dot_v1_dot_tests__pb2.MapMessageRoutingValueResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'osprey.rpc.pigeon.tests.v1.TestService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TestService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ScalarRoutingValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/osprey.rpc.pigeon.tests.v1.TestService/ScalarRoutingValue',
            osprey_dot_rpc_dot_pigeon_dot_tests_dot_v1_dot_tests__pb2.ScalarRoutingValueRequest.SerializeToString,
            osprey_dot_rpc_dot_pigeon_dot_tests_dot_v1_dot_tests__pb2.ScalarRoutingValueResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListRoutingValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/osprey.rpc.pigeon.tests.v1.TestService/ListRoutingValue',
            osprey_dot_rpc_dot_pigeon_dot_tests_dot_v1_dot_tests__pb2.ListRoutingValueRequest.SerializeToString,
            osprey_dot_rpc_dot_pigeon_dot_tests_dot_v1_dot_tests__pb2.ListRoutingValueResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MapRoutingValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/osprey.rpc.pigeon.tests.v1.TestService/MapRoutingValue',
            osprey_dot_rpc_dot_pigeon_dot_tests_dot_v1_dot_tests__pb2.MapRoutingValueRequest.SerializeToString,
            osprey_dot_rpc_dot_pigeon_dot_tests_dot_v1_dot_tests__pb2.MapRoutingValueResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def MapMessageRoutingValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/osprey.rpc.pigeon.tests.v1.TestService/MapMessageRoutingValue',
            osprey_dot_rpc_dot_pigeon_dot_tests_dot_v1_dot_tests__pb2.MapMessageRoutingValueRequest.SerializeToString,
            osprey_dot_rpc_dot_pigeon_dot_tests_dot_v1_dot_tests__pb2.MapMessageRoutingValueResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
