"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2025 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.field_mask_pb2
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Folder(google.protobuf.message.Message):
    """A folder in an organization's resource hierarchy, used to
    organize that organization's resources.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _State:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _StateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Folder._State.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        STATE_UNSPECIFIED: Folder._State.ValueType  # 0
        """Unspecified state."""
        ACTIVE: Folder._State.ValueType  # 1
        """The normal and active state."""
        DELETE_REQUESTED: Folder._State.ValueType  # 2
        """The folder has been marked for deletion by the user."""

    class State(_State, metaclass=_StateEnumTypeWrapper):
        """Folder lifecycle states."""

    STATE_UNSPECIFIED: Folder.State.ValueType  # 0
    """Unspecified state."""
    ACTIVE: Folder.State.ValueType  # 1
    """The normal and active state."""
    DELETE_REQUESTED: Folder.State.ValueType  # 2
    """The folder has been marked for deletion by the user."""

    NAME_FIELD_NUMBER: builtins.int
    PARENT_FIELD_NUMBER: builtins.int
    DISPLAY_NAME_FIELD_NUMBER: builtins.int
    STATE_FIELD_NUMBER: builtins.int
    CREATE_TIME_FIELD_NUMBER: builtins.int
    UPDATE_TIME_FIELD_NUMBER: builtins.int
    DELETE_TIME_FIELD_NUMBER: builtins.int
    ETAG_FIELD_NUMBER: builtins.int
    name: builtins.str
    """Output only. The resource name of the folder.
    Its format is `folders/{folder_id}`, for example: "folders/1234".
    """
    parent: builtins.str
    """Required. The folder's parent's resource name.
    Updates to the folder's parent must be performed using
    [MoveFolder][google.cloud.resourcemanager.v3.Folders.MoveFolder].
    """
    display_name: builtins.str
    """The folder's display name.
    A folder's display name must be unique amongst its siblings. For example,
    no two folders with the same parent can share the same display name.
    The display name must start and end with a letter or digit, may contain
    letters, digits, spaces, hyphens and underscores and can be no longer
    than 30 characters. This is captured by the regular expression:
    `[\\p{L}\\p{N}]([\\p{L}\\p{N}_- ]{0,28}[\\p{L}\\p{N}])?`.
    """
    state: global___Folder.State.ValueType
    """Output only. The lifecycle state of the folder.
    Updates to the state must be performed using
    [DeleteFolder][google.cloud.resourcemanager.v3.Folders.DeleteFolder] and
    [UndeleteFolder][google.cloud.resourcemanager.v3.Folders.UndeleteFolder].
    """
    etag: builtins.str
    """Output only. A checksum computed by the server based on the current value
    of the folder resource. This may be sent on update and delete requests to
    ensure the client has an up-to-date value before proceeding.
    """
    @property
    def create_time(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Output only. Timestamp when the folder was created."""

    @property
    def update_time(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Output only. Timestamp when the folder was last modified."""

    @property
    def delete_time(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Output only. Timestamp when the folder was requested to be deleted."""

    def __init__(
        self,
        *,
        name: builtins.str = ...,
        parent: builtins.str = ...,
        display_name: builtins.str = ...,
        state: global___Folder.State.ValueType = ...,
        create_time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        update_time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        delete_time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        etag: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["create_time", b"create_time", "delete_time", b"delete_time", "update_time", b"update_time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["create_time", b"create_time", "delete_time", b"delete_time", "display_name", b"display_name", "etag", b"etag", "name", b"name", "parent", b"parent", "state", b"state", "update_time", b"update_time"]) -> None: ...

global___Folder = Folder

@typing.final
class GetFolderRequest(google.protobuf.message.Message):
    """The GetFolder request message."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    """Required. The resource name of the folder to retrieve.
    Must be of the form `folders/{folder_id}`.
    """
    def __init__(
        self,
        *,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name"]) -> None: ...

global___GetFolderRequest = GetFolderRequest

@typing.final
class ListFoldersRequest(google.protobuf.message.Message):
    """The ListFolders request message."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PARENT_FIELD_NUMBER: builtins.int
    PAGE_SIZE_FIELD_NUMBER: builtins.int
    PAGE_TOKEN_FIELD_NUMBER: builtins.int
    SHOW_DELETED_FIELD_NUMBER: builtins.int
    parent: builtins.str
    """Required. The name of the parent resource whose folders are being listed.
    Only children of this parent resource are listed; descendants are not
    listed.

    If the parent is a folder, use the value `folders/{folder_id}`. If the
    parent is an organization, use the value `organizations/{org_id}`.

    Access to this method is controlled by checking the
    `resourcemanager.folders.list` permission on the `parent`.
    """
    page_size: builtins.int
    """Optional. The maximum number of folders to return in the response. The
    server can return fewer folders than requested. If unspecified, server
    picks an appropriate default.
    """
    page_token: builtins.str
    """Optional. A pagination token returned from a previous call to `ListFolders`
    that indicates where this listing should continue from.
    """
    show_deleted: builtins.bool
    """Optional. Controls whether folders in the
    [DELETE_REQUESTED][google.cloud.resourcemanager.v3.Folder.State.DELETE_REQUESTED]
    state should be returned. Defaults to false.
    """
    def __init__(
        self,
        *,
        parent: builtins.str = ...,
        page_size: builtins.int = ...,
        page_token: builtins.str = ...,
        show_deleted: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["page_size", b"page_size", "page_token", b"page_token", "parent", b"parent", "show_deleted", b"show_deleted"]) -> None: ...

global___ListFoldersRequest = ListFoldersRequest

@typing.final
class ListFoldersResponse(google.protobuf.message.Message):
    """The ListFolders response message."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FOLDERS_FIELD_NUMBER: builtins.int
    NEXT_PAGE_TOKEN_FIELD_NUMBER: builtins.int
    next_page_token: builtins.str
    """A pagination token returned from a previous call to `ListFolders`
    that indicates from where listing should continue.
    """
    @property
    def folders(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Folder]:
        """A possibly paginated list of folders that are direct descendants of
        the specified parent resource.
        """

    def __init__(
        self,
        *,
        folders: collections.abc.Iterable[global___Folder] | None = ...,
        next_page_token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["folders", b"folders", "next_page_token", b"next_page_token"]) -> None: ...

global___ListFoldersResponse = ListFoldersResponse

@typing.final
class SearchFoldersRequest(google.protobuf.message.Message):
    """The request message for searching folders."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PAGE_SIZE_FIELD_NUMBER: builtins.int
    PAGE_TOKEN_FIELD_NUMBER: builtins.int
    QUERY_FIELD_NUMBER: builtins.int
    page_size: builtins.int
    """Optional. The maximum number of folders to return in the response. The
    server can return fewer folders than requested. If unspecified, server
    picks an appropriate default.
    """
    page_token: builtins.str
    """Optional. A pagination token returned from a previous call to
    `SearchFolders` that indicates from where search should continue.
    """
    query: builtins.str
    """Optional. Search criteria used to select the folders to return.
    If no search criteria is specified then all accessible folders will be
    returned.

    Query expressions can be used to restrict results based upon displayName,
    state and parent, where the operators `=` (`:`) `NOT`, `AND` and `OR`
    can be used along with the suffix wildcard symbol `*`.

    The `displayName` field in a query expression should use escaped quotes
    for values that include whitespace to prevent unexpected behavior.

    ```
    | Field                   | Description                            |
    |-------------------------|----------------------------------------|
    | displayName             | Filters by displayName.                |
    | parent                  | Filters by parent (for example: folders/123). |
    | state, lifecycleState   | Filters by state.                      |
    ```

    Some example queries are:

    * Query `displayName=Test*` returns Folder resources whose display name
    starts with "Test".
    * Query `state=ACTIVE` returns Folder resources with
    `state` set to `ACTIVE`.
    * Query `parent=folders/123` returns Folder resources that have
    `folders/123` as a parent resource.
    * Query `parent=folders/123 AND state=ACTIVE` returns active
    Folder resources that have `folders/123` as a parent resource.
    * Query `displayName=\\\\"Test String\\\\"` returns Folder resources with
    display names that include both "Test" and "String".
    """
    def __init__(
        self,
        *,
        page_size: builtins.int = ...,
        page_token: builtins.str = ...,
        query: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["page_size", b"page_size", "page_token", b"page_token", "query", b"query"]) -> None: ...

global___SearchFoldersRequest = SearchFoldersRequest

@typing.final
class SearchFoldersResponse(google.protobuf.message.Message):
    """The response message for searching folders."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FOLDERS_FIELD_NUMBER: builtins.int
    NEXT_PAGE_TOKEN_FIELD_NUMBER: builtins.int
    next_page_token: builtins.str
    """A pagination token returned from a previous call to `SearchFolders`
    that indicates from where searching should continue.
    """
    @property
    def folders(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Folder]:
        """A possibly paginated folder search results.
        the specified parent resource.
        """

    def __init__(
        self,
        *,
        folders: collections.abc.Iterable[global___Folder] | None = ...,
        next_page_token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["folders", b"folders", "next_page_token", b"next_page_token"]) -> None: ...

global___SearchFoldersResponse = SearchFoldersResponse

@typing.final
class CreateFolderRequest(google.protobuf.message.Message):
    """The CreateFolder request message."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FOLDER_FIELD_NUMBER: builtins.int
    @property
    def folder(self) -> global___Folder:
        """Required. The folder being created, only the display name and parent will
        be consulted. All other fields will be ignored.
        """

    def __init__(
        self,
        *,
        folder: global___Folder | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["folder", b"folder"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["folder", b"folder"]) -> None: ...

global___CreateFolderRequest = CreateFolderRequest

@typing.final
class CreateFolderMetadata(google.protobuf.message.Message):
    """Metadata pertaining to the Folder creation process."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DISPLAY_NAME_FIELD_NUMBER: builtins.int
    PARENT_FIELD_NUMBER: builtins.int
    display_name: builtins.str
    """The display name of the folder."""
    parent: builtins.str
    """The resource name of the folder or organization we are creating the folder
    under.
    """
    def __init__(
        self,
        *,
        display_name: builtins.str = ...,
        parent: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["display_name", b"display_name", "parent", b"parent"]) -> None: ...

global___CreateFolderMetadata = CreateFolderMetadata

@typing.final
class UpdateFolderRequest(google.protobuf.message.Message):
    """The request sent to the
    [UpdateFolder][google.cloud.resourcemanager.v3.Folder.UpdateFolder]
    method.

    Only the `display_name` field can be changed. All other fields will be
    ignored. Use the
    [MoveFolder][google.cloud.resourcemanager.v3.Folders.MoveFolder] method to
    change the `parent` field.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FOLDER_FIELD_NUMBER: builtins.int
    UPDATE_MASK_FIELD_NUMBER: builtins.int
    @property
    def folder(self) -> global___Folder:
        """Required. The new definition of the Folder. It must include the `name`
        field, which cannot be changed.
        """

    @property
    def update_mask(self) -> google.protobuf.field_mask_pb2.FieldMask:
        """Required. Fields to be updated.
        Only the `display_name` can be updated.
        """

    def __init__(
        self,
        *,
        folder: global___Folder | None = ...,
        update_mask: google.protobuf.field_mask_pb2.FieldMask | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["folder", b"folder", "update_mask", b"update_mask"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["folder", b"folder", "update_mask", b"update_mask"]) -> None: ...

global___UpdateFolderRequest = UpdateFolderRequest

@typing.final
class UpdateFolderMetadata(google.protobuf.message.Message):
    """A status object which is used as the `metadata` field for the Operation
    returned by UpdateFolder.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___UpdateFolderMetadata = UpdateFolderMetadata

@typing.final
class MoveFolderRequest(google.protobuf.message.Message):
    """The MoveFolder request message."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    DESTINATION_PARENT_FIELD_NUMBER: builtins.int
    name: builtins.str
    """Required. The resource name of the Folder to move.
    Must be of the form folders/{folder_id}
    """
    destination_parent: builtins.str
    """Required. The resource name of the folder or organization which should be
    the folder's new parent. Must be of the form `folders/{folder_id}` or
    `organizations/{org_id}`.
    """
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        destination_parent: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["destination_parent", b"destination_parent", "name", b"name"]) -> None: ...

global___MoveFolderRequest = MoveFolderRequest

@typing.final
class MoveFolderMetadata(google.protobuf.message.Message):
    """Metadata pertaining to the folder move process."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DISPLAY_NAME_FIELD_NUMBER: builtins.int
    SOURCE_PARENT_FIELD_NUMBER: builtins.int
    DESTINATION_PARENT_FIELD_NUMBER: builtins.int
    display_name: builtins.str
    """The display name of the folder."""
    source_parent: builtins.str
    """The resource name of the folder's parent."""
    destination_parent: builtins.str
    """The resource name of the folder or organization to move the folder to."""
    def __init__(
        self,
        *,
        display_name: builtins.str = ...,
        source_parent: builtins.str = ...,
        destination_parent: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["destination_parent", b"destination_parent", "display_name", b"display_name", "source_parent", b"source_parent"]) -> None: ...

global___MoveFolderMetadata = MoveFolderMetadata

@typing.final
class DeleteFolderRequest(google.protobuf.message.Message):
    """The DeleteFolder request message."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    """Required. The resource name of the folder to be deleted.
    Must be of the form `folders/{folder_id}`.
    """
    def __init__(
        self,
        *,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name"]) -> None: ...

global___DeleteFolderRequest = DeleteFolderRequest

@typing.final
class DeleteFolderMetadata(google.protobuf.message.Message):
    """A status object which is used as the `metadata` field for the `Operation`
    returned by `DeleteFolder`.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___DeleteFolderMetadata = DeleteFolderMetadata

@typing.final
class UndeleteFolderRequest(google.protobuf.message.Message):
    """The UndeleteFolder request message."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    """Required. The resource name of the folder to undelete.
    Must be of the form `folders/{folder_id}`.
    """
    def __init__(
        self,
        *,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name"]) -> None: ...

global___UndeleteFolderRequest = UndeleteFolderRequest

@typing.final
class UndeleteFolderMetadata(google.protobuf.message.Message):
    """A status object which is used as the `metadata` field for the `Operation`
    returned by `UndeleteFolder`.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___UndeleteFolderMetadata = UndeleteFolderMetadata
