"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2025 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.field_mask_pb2
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Project(google.protobuf.message.Message):
    """A project is a high-level Google Cloud entity. It is a
    container for ACLs, APIs, App Engine Apps, VMs, and other
    Google Cloud Platform resources.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _State:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _StateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Project._State.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        STATE_UNSPECIFIED: Project._State.ValueType  # 0
        """Unspecified state.  This is only used/useful for distinguishing
        unset values.
        """
        ACTIVE: Project._State.ValueType  # 1
        """The normal and active state."""
        DELETE_REQUESTED: Project._State.ValueType  # 2
        """The project has been marked for deletion by the user
        (by invoking
        [DeleteProject][google.cloud.resourcemanager.v3.Projects.DeleteProject])
        or by the system (Google Cloud Platform).
        This can generally be reversed by invoking [UndeleteProject]
        [google.cloud.resourcemanager.v3.Projects.UndeleteProject].
        """

    class State(_State, metaclass=_StateEnumTypeWrapper):
        """Project lifecycle states."""

    STATE_UNSPECIFIED: Project.State.ValueType  # 0
    """Unspecified state.  This is only used/useful for distinguishing
    unset values.
    """
    ACTIVE: Project.State.ValueType  # 1
    """The normal and active state."""
    DELETE_REQUESTED: Project.State.ValueType  # 2
    """The project has been marked for deletion by the user
    (by invoking
    [DeleteProject][google.cloud.resourcemanager.v3.Projects.DeleteProject])
    or by the system (Google Cloud Platform).
    This can generally be reversed by invoking [UndeleteProject]
    [google.cloud.resourcemanager.v3.Projects.UndeleteProject].
    """

    @typing.final
    class LabelsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    NAME_FIELD_NUMBER: builtins.int
    PARENT_FIELD_NUMBER: builtins.int
    PROJECT_ID_FIELD_NUMBER: builtins.int
    STATE_FIELD_NUMBER: builtins.int
    DISPLAY_NAME_FIELD_NUMBER: builtins.int
    CREATE_TIME_FIELD_NUMBER: builtins.int
    UPDATE_TIME_FIELD_NUMBER: builtins.int
    DELETE_TIME_FIELD_NUMBER: builtins.int
    ETAG_FIELD_NUMBER: builtins.int
    LABELS_FIELD_NUMBER: builtins.int
    name: builtins.str
    """Output only. The unique resource name of the project. It is an int64
    generated number prefixed by "projects/".

    Example: `projects/415104041262`
    """
    parent: builtins.str
    """Optional. A reference to a parent Resource. eg., `organizations/123` or
    `folders/876`.
    """
    project_id: builtins.str
    """Immutable. The unique, user-assigned id of the project.
    It must be 6 to 30 lowercase ASCII letters, digits, or hyphens.
    It must start with a letter.
    Trailing hyphens are prohibited.

    Example: `tokyo-rain-123`
    """
    state: global___Project.State.ValueType
    """Output only. The project lifecycle state."""
    display_name: builtins.str
    """Optional. A user-assigned display name of the project.
    When present it must be between 4 to 30 characters.
    Allowed characters are: lowercase and uppercase letters, numbers,
    hyphen, single-quote, double-quote, space, and exclamation point.

    Example: `My Project`
    """
    etag: builtins.str
    """Output only. A checksum computed by the server based on the current value
    of the Project resource. This may be sent on update and delete requests to
    ensure the client has an up-to-date value before proceeding.
    """
    @property
    def create_time(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Output only. Creation time."""

    @property
    def update_time(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Output only. The most recent time this resource was modified."""

    @property
    def delete_time(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Output only. The time at which this resource was requested for deletion."""

    @property
    def labels(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]:
        """Optional. The labels associated with this project.

        Label keys must be between 1 and 63 characters long and must conform
        to the following regular expression: \\[a-z\\](\\[-a-z0-9\\]*\\[a-z0-9\\])?.

        Label values must be between 0 and 63 characters long and must conform
        to the regular expression (\\[a-z\\](\\[-a-z0-9\\]*\\[a-z0-9\\])?)?.

        No more than 64 labels can be associated with a given resource.

        Clients should store labels in a representation such as JSON that does not
        depend on specific characters being disallowed.

        Example: `"myBusinessDimension" : "businessValue"`
        """

    def __init__(
        self,
        *,
        name: builtins.str = ...,
        parent: builtins.str = ...,
        project_id: builtins.str = ...,
        state: global___Project.State.ValueType = ...,
        display_name: builtins.str = ...,
        create_time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        update_time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        delete_time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        etag: builtins.str = ...,
        labels: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["create_time", b"create_time", "delete_time", b"delete_time", "update_time", b"update_time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["create_time", b"create_time", "delete_time", b"delete_time", "display_name", b"display_name", "etag", b"etag", "labels", b"labels", "name", b"name", "parent", b"parent", "project_id", b"project_id", "state", b"state", "update_time", b"update_time"]) -> None: ...

global___Project = Project

@typing.final
class GetProjectRequest(google.protobuf.message.Message):
    """The request sent to the
    [GetProject][google.cloud.resourcemanager.v3.Projects.GetProject]
    method.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    """Required. The name of the project (for example, `projects/415104041262`)."""
    def __init__(
        self,
        *,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name"]) -> None: ...

global___GetProjectRequest = GetProjectRequest

@typing.final
class ListProjectsRequest(google.protobuf.message.Message):
    """The request sent to the
    [ListProjects][google.cloud.resourcemanager.v3.Projects.ListProjects]
    method.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PARENT_FIELD_NUMBER: builtins.int
    PAGE_TOKEN_FIELD_NUMBER: builtins.int
    PAGE_SIZE_FIELD_NUMBER: builtins.int
    SHOW_DELETED_FIELD_NUMBER: builtins.int
    parent: builtins.str
    """Required. The name of the parent resource whose projects are being listed.
    Only children of this parent resource are listed; descendants are not
    listed.

    If the parent is a folder, use the value `folders/{folder_id}`. If the
    parent is an organization, use the value `organizations/{org_id}`.
    """
    page_token: builtins.str
    """Optional. A pagination token returned from a previous call to
    [ListProjects] [google.cloud.resourcemanager.v3.Projects.ListProjects] that
    indicates from where listing should continue.
    """
    page_size: builtins.int
    """Optional. The maximum number of projects to return in the response.
    The server can return fewer projects than requested.
    If unspecified, server picks an appropriate default.
    """
    show_deleted: builtins.bool
    """Optional. Indicate that projects in the `DELETE_REQUESTED` state should
    also be returned. Normally only `ACTIVE` projects are returned.
    """
    def __init__(
        self,
        *,
        parent: builtins.str = ...,
        page_token: builtins.str = ...,
        page_size: builtins.int = ...,
        show_deleted: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["page_size", b"page_size", "page_token", b"page_token", "parent", b"parent", "show_deleted", b"show_deleted"]) -> None: ...

global___ListProjectsRequest = ListProjectsRequest

@typing.final
class ListProjectsResponse(google.protobuf.message.Message):
    """A page of the response received from the
    [ListProjects][google.cloud.resourcemanager.v3.Projects.ListProjects]
    method.

    A paginated response where more pages are available has
    `next_page_token` set. This token can be used in a subsequent request to
    retrieve the next request page.

    NOTE: A response may contain fewer elements than the request `page_size` and
    still have a `next_page_token`.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PROJECTS_FIELD_NUMBER: builtins.int
    NEXT_PAGE_TOKEN_FIELD_NUMBER: builtins.int
    next_page_token: builtins.str
    """Pagination token.

    If the result set is too large to fit in a single response, this token
    is returned. It encodes the position of the current result cursor.
    Feeding this value into a new list request with the `page_token` parameter
    gives the next page of the results.

    When `next_page_token` is not filled in, there is no next page and
    the list returned is the last page in the result set.

    Pagination tokens have a limited lifetime.
    """
    @property
    def projects(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Project]:
        """The list of Projects under the parent. This list can be paginated."""

    def __init__(
        self,
        *,
        projects: collections.abc.Iterable[global___Project] | None = ...,
        next_page_token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["next_page_token", b"next_page_token", "projects", b"projects"]) -> None: ...

global___ListProjectsResponse = ListProjectsResponse

@typing.final
class SearchProjectsRequest(google.protobuf.message.Message):
    """The request sent to the
    [SearchProjects][google.cloud.resourcemanager.v3.Projects.SearchProjects]
    method.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    QUERY_FIELD_NUMBER: builtins.int
    PAGE_TOKEN_FIELD_NUMBER: builtins.int
    PAGE_SIZE_FIELD_NUMBER: builtins.int
    query: builtins.str
    """Optional. A query string for searching for projects that the caller has
    `resourcemanager.projects.get` permission to. If multiple fields are
    included in the query, then it will return results that match any of the
    fields. Some eligible fields are:

    - **`displayName`, `name`**: Filters by displayName.
    - **`parent`**: Project's parent (for example: `folders/123`,
    `organizations/*`). Prefer `parent` field over `parent.type` and
    `parent.id`.
    - **`parent.type`**: Parent's type: `folder` or `organization`.
    - **`parent.id`**: Parent's id number (for example: `123`).
    - **`id`, `projectId`**: Filters by projectId.
    - **`state`, `lifecycleState`**: Filters by state.
    - **`labels`**: Filters by label name or value.
    - **`labels.<key>` (where `<key>` is the name of a label)**: Filters by label
    name.

    Search expressions are case insensitive.

    Some examples queries:


    - **`name:how*`**: The project's name starts with "how".
    - **`name:Howl`**: The project's name is `Howl` or `howl`.
    - **`name:HOWL`**: Equivalent to above.
    - **`NAME:howl`**: Equivalent to above.
    - **`labels.color:*`**: The project has the label `color`.
    - **`labels.color:red`**:  The project's label `color` has the value `red`.
    - **`labels.color:red labels.size:big`**: The project's label `color` has
    the value `red` or its label `size` has the value `big`.

    If no query is specified, the call will return projects for which the user
    has the `resourcemanager.projects.get` permission.
    """
    page_token: builtins.str
    """Optional. A pagination token returned from a previous call to
    [ListProjects] [google.cloud.resourcemanager.v3.Projects.ListProjects] that
    indicates from where listing should continue.
    """
    page_size: builtins.int
    """Optional. The maximum number of projects to return in the response.
    The server can return fewer projects than requested.
    If unspecified, server picks an appropriate default.
    """
    def __init__(
        self,
        *,
        query: builtins.str = ...,
        page_token: builtins.str = ...,
        page_size: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["page_size", b"page_size", "page_token", b"page_token", "query", b"query"]) -> None: ...

global___SearchProjectsRequest = SearchProjectsRequest

@typing.final
class SearchProjectsResponse(google.protobuf.message.Message):
    """A page of the response received from the
    [SearchProjects][google.cloud.resourcemanager.v3.Projects.SearchProjects]
    method.

    A paginated response where more pages are available has
    `next_page_token` set. This token can be used in a subsequent request to
    retrieve the next request page.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PROJECTS_FIELD_NUMBER: builtins.int
    NEXT_PAGE_TOKEN_FIELD_NUMBER: builtins.int
    next_page_token: builtins.str
    """Pagination token.

    If the result set is too large to fit in a single response, this token
    is returned. It encodes the position of the current result cursor.
    Feeding this value into a new list request with the `page_token` parameter
    gives the next page of the results.

    When `next_page_token` is not filled in, there is no next page and
    the list returned is the last page in the result set.

    Pagination tokens have a limited lifetime.
    """
    @property
    def projects(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Project]:
        """The list of Projects that matched the list filter query. This list can
        be paginated.
        """

    def __init__(
        self,
        *,
        projects: collections.abc.Iterable[global___Project] | None = ...,
        next_page_token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["next_page_token", b"next_page_token", "projects", b"projects"]) -> None: ...

global___SearchProjectsResponse = SearchProjectsResponse

@typing.final
class CreateProjectRequest(google.protobuf.message.Message):
    """The request sent to the
    [CreateProject][google.cloud.resourcemanager.v3.Projects.CreateProject]
    method.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PROJECT_FIELD_NUMBER: builtins.int
    @property
    def project(self) -> global___Project:
        """Required. The Project to create.

        Project ID is required. If the requested ID is unavailable, the request
        fails.

        If the `parent` field is set, the `resourcemanager.projects.create`
        permission is checked on the parent resource. If no parent is set and
        the authorization credentials belong to an Organization, the parent
        will be set to that Organization.
        """

    def __init__(
        self,
        *,
        project: global___Project | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["project", b"project"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["project", b"project"]) -> None: ...

global___CreateProjectRequest = CreateProjectRequest

@typing.final
class CreateProjectMetadata(google.protobuf.message.Message):
    """A status object which is used as the `metadata` field for the Operation
    returned by CreateProject. It provides insight for when significant phases of
    Project creation have completed.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CREATE_TIME_FIELD_NUMBER: builtins.int
    GETTABLE_FIELD_NUMBER: builtins.int
    READY_FIELD_NUMBER: builtins.int
    gettable: builtins.bool
    """True if the project can be retrieved using `GetProject`. No other
    operations on the project are guaranteed to work until the project creation
    is complete.
    """
    ready: builtins.bool
    """True if the project creation process is complete."""
    @property
    def create_time(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Creation time of the project creation workflow."""

    def __init__(
        self,
        *,
        create_time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        gettable: builtins.bool = ...,
        ready: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["create_time", b"create_time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["create_time", b"create_time", "gettable", b"gettable", "ready", b"ready"]) -> None: ...

global___CreateProjectMetadata = CreateProjectMetadata

@typing.final
class UpdateProjectRequest(google.protobuf.message.Message):
    """The request sent to the
    [UpdateProject][google.cloud.resourcemanager.v3.Projects.UpdateProject]
    method.

    Only the `display_name` and `labels` fields can be change. Use the
    [MoveProject][google.cloud.resourcemanager.v3.Projects.MoveProject] method to
    change the `parent` field.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PROJECT_FIELD_NUMBER: builtins.int
    UPDATE_MASK_FIELD_NUMBER: builtins.int
    @property
    def project(self) -> global___Project:
        """Required. The new definition of the project."""

    @property
    def update_mask(self) -> google.protobuf.field_mask_pb2.FieldMask:
        """Optional. An update mask to selectively update fields."""

    def __init__(
        self,
        *,
        project: global___Project | None = ...,
        update_mask: google.protobuf.field_mask_pb2.FieldMask | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["project", b"project", "update_mask", b"update_mask"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["project", b"project", "update_mask", b"update_mask"]) -> None: ...

global___UpdateProjectRequest = UpdateProjectRequest

@typing.final
class UpdateProjectMetadata(google.protobuf.message.Message):
    """A status object which is used as the `metadata` field for the Operation
    returned by UpdateProject.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___UpdateProjectMetadata = UpdateProjectMetadata

@typing.final
class MoveProjectRequest(google.protobuf.message.Message):
    """The request sent to
    [MoveProject][google.cloud.resourcemanager.v3.Projects.MoveProject]
    method.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    DESTINATION_PARENT_FIELD_NUMBER: builtins.int
    name: builtins.str
    """Required. The name of the project to move."""
    destination_parent: builtins.str
    """Required. The new parent to move the Project under."""
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        destination_parent: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["destination_parent", b"destination_parent", "name", b"name"]) -> None: ...

global___MoveProjectRequest = MoveProjectRequest

@typing.final
class MoveProjectMetadata(google.protobuf.message.Message):
    """A status object which is used as the `metadata` field for the Operation
    returned by MoveProject.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___MoveProjectMetadata = MoveProjectMetadata

@typing.final
class DeleteProjectRequest(google.protobuf.message.Message):
    """[DeleteProject][google.cloud.resourcemanager.v3.Projects.DeleteProject]
    method.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    """Required. The name of the Project (for example, `projects/415104041262`)."""
    def __init__(
        self,
        *,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name"]) -> None: ...

global___DeleteProjectRequest = DeleteProjectRequest

@typing.final
class DeleteProjectMetadata(google.protobuf.message.Message):
    """A status object which is used as the `metadata` field for the Operation
    returned by `DeleteProject`.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___DeleteProjectMetadata = DeleteProjectMetadata

@typing.final
class UndeleteProjectRequest(google.protobuf.message.Message):
    """The request sent to the [UndeleteProject]
    [google.cloud.resourcemanager.v3.Projects.UndeleteProject]
    method.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    """Required. The name of the project (for example, `projects/415104041262`).

    Required.
    """
    def __init__(
        self,
        *,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name"]) -> None: ...

global___UndeleteProjectRequest = UndeleteProjectRequest

@typing.final
class UndeleteProjectMetadata(google.protobuf.message.Message):
    """A status object which is used as the `metadata` field for the Operation
    returned by `UndeleteProject`.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___UndeleteProjectMetadata = UndeleteProjectMetadata
