# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.cloud.resourcemanager.v3 import tag_values_pb2 as google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__values__pb2
from google.iam.v1 import iam_policy_pb2 as google_dot_iam_dot_v1_dot_iam__policy__pb2
from google.iam.v1 import policy_pb2 as google_dot_iam_dot_v1_dot_policy__pb2
from google.longrunning import operations_pb2 as google_dot_longrunning_dot_operations__pb2


class TagValuesStub(object):
    """Allow users to create and manage tag values.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListTagValues = channel.unary_unary(
                '/google.cloud.resourcemanager.v3.TagValues/ListTagValues',
                request_serializer=google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__values__pb2.ListTagValuesRequest.SerializeToString,
                response_deserializer=google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__values__pb2.ListTagValuesResponse.FromString,
                )
        self.GetTagValue = channel.unary_unary(
                '/google.cloud.resourcemanager.v3.TagValues/GetTagValue',
                request_serializer=google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__values__pb2.GetTagValueRequest.SerializeToString,
                response_deserializer=google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__values__pb2.TagValue.FromString,
                )
        self.GetNamespacedTagValue = channel.unary_unary(
                '/google.cloud.resourcemanager.v3.TagValues/GetNamespacedTagValue',
                request_serializer=google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__values__pb2.GetNamespacedTagValueRequest.SerializeToString,
                response_deserializer=google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__values__pb2.TagValue.FromString,
                )
        self.CreateTagValue = channel.unary_unary(
                '/google.cloud.resourcemanager.v3.TagValues/CreateTagValue',
                request_serializer=google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__values__pb2.CreateTagValueRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                )
        self.UpdateTagValue = channel.unary_unary(
                '/google.cloud.resourcemanager.v3.TagValues/UpdateTagValue',
                request_serializer=google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__values__pb2.UpdateTagValueRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                )
        self.DeleteTagValue = channel.unary_unary(
                '/google.cloud.resourcemanager.v3.TagValues/DeleteTagValue',
                request_serializer=google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__values__pb2.DeleteTagValueRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                )
        self.GetIamPolicy = channel.unary_unary(
                '/google.cloud.resourcemanager.v3.TagValues/GetIamPolicy',
                request_serializer=google_dot_iam_dot_v1_dot_iam__policy__pb2.GetIamPolicyRequest.SerializeToString,
                response_deserializer=google_dot_iam_dot_v1_dot_policy__pb2.Policy.FromString,
                )
        self.SetIamPolicy = channel.unary_unary(
                '/google.cloud.resourcemanager.v3.TagValues/SetIamPolicy',
                request_serializer=google_dot_iam_dot_v1_dot_iam__policy__pb2.SetIamPolicyRequest.SerializeToString,
                response_deserializer=google_dot_iam_dot_v1_dot_policy__pb2.Policy.FromString,
                )
        self.TestIamPermissions = channel.unary_unary(
                '/google.cloud.resourcemanager.v3.TagValues/TestIamPermissions',
                request_serializer=google_dot_iam_dot_v1_dot_iam__policy__pb2.TestIamPermissionsRequest.SerializeToString,
                response_deserializer=google_dot_iam_dot_v1_dot_iam__policy__pb2.TestIamPermissionsResponse.FromString,
                )


class TagValuesServicer(object):
    """Allow users to create and manage tag values.
    """

    def ListTagValues(self, request, context):
        """Lists all TagValues for a specific TagKey.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTagValue(self, request, context):
        """Retrieves a TagValue. This method will return `PERMISSION_DENIED` if the
        value does not exist or the user does not have permission to view it.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNamespacedTagValue(self, request, context):
        """Retrieves a TagValue by its namespaced name.
        This method will return `PERMISSION_DENIED` if the value does not exist
        or the user does not have permission to view it.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTagValue(self, request, context):
        """Creates a TagValue as a child of the specified TagKey. If a another
        request with the same parameters is sent while the original request is in
        process the second request will receive an error. A maximum of 1000
        TagValues can exist under a TagKey at any given time.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTagValue(self, request, context):
        """Updates the attributes of the TagValue resource.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTagValue(self, request, context):
        """Deletes a TagValue. The TagValue cannot have any bindings when it is
        deleted.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIamPolicy(self, request, context):
        """Gets the access control policy for a TagValue. The returned policy may be
        empty if no such policy or resource exists. The `resource` field should
        be the TagValue's resource name. For example: `tagValues/1234`.
        The caller must have the
        `cloudresourcemanager.googleapis.com/tagValues.getIamPolicy` permission on
        the identified TagValue to get the access control policy.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetIamPolicy(self, request, context):
        """Sets the access control policy on a TagValue, replacing any existing
        policy. The `resource` field should be the TagValue's resource name.
        For example: `tagValues/1234`.
        The caller must have `resourcemanager.tagValues.setIamPolicy` permission
        on the identified tagValue.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TestIamPermissions(self, request, context):
        """Returns permissions that a caller has on the specified TagValue.
        The `resource` field should be the TagValue's resource name. For example:
        `tagValues/1234`.

        There are no permissions required for making this API call.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TagValuesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListTagValues': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTagValues,
                    request_deserializer=google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__values__pb2.ListTagValuesRequest.FromString,
                    response_serializer=google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__values__pb2.ListTagValuesResponse.SerializeToString,
            ),
            'GetTagValue': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTagValue,
                    request_deserializer=google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__values__pb2.GetTagValueRequest.FromString,
                    response_serializer=google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__values__pb2.TagValue.SerializeToString,
            ),
            'GetNamespacedTagValue': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNamespacedTagValue,
                    request_deserializer=google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__values__pb2.GetNamespacedTagValueRequest.FromString,
                    response_serializer=google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__values__pb2.TagValue.SerializeToString,
            ),
            'CreateTagValue': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTagValue,
                    request_deserializer=google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__values__pb2.CreateTagValueRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'UpdateTagValue': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTagValue,
                    request_deserializer=google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__values__pb2.UpdateTagValueRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'DeleteTagValue': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTagValue,
                    request_deserializer=google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__values__pb2.DeleteTagValueRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'GetIamPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIamPolicy,
                    request_deserializer=google_dot_iam_dot_v1_dot_iam__policy__pb2.GetIamPolicyRequest.FromString,
                    response_serializer=google_dot_iam_dot_v1_dot_policy__pb2.Policy.SerializeToString,
            ),
            'SetIamPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.SetIamPolicy,
                    request_deserializer=google_dot_iam_dot_v1_dot_iam__policy__pb2.SetIamPolicyRequest.FromString,
                    response_serializer=google_dot_iam_dot_v1_dot_policy__pb2.Policy.SerializeToString,
            ),
            'TestIamPermissions': grpc.unary_unary_rpc_method_handler(
                    servicer.TestIamPermissions,
                    request_deserializer=google_dot_iam_dot_v1_dot_iam__policy__pb2.TestIamPermissionsRequest.FromString,
                    response_serializer=google_dot_iam_dot_v1_dot_iam__policy__pb2.TestIamPermissionsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'google.cloud.resourcemanager.v3.TagValues', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TagValues(object):
    """Allow users to create and manage tag values.
    """

    @staticmethod
    def ListTagValues(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.resourcemanager.v3.TagValues/ListTagValues',
            google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__values__pb2.ListTagValuesRequest.SerializeToString,
            google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__values__pb2.ListTagValuesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTagValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.resourcemanager.v3.TagValues/GetTagValue',
            google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__values__pb2.GetTagValueRequest.SerializeToString,
            google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__values__pb2.TagValue.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetNamespacedTagValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.resourcemanager.v3.TagValues/GetNamespacedTagValue',
            google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__values__pb2.GetNamespacedTagValueRequest.SerializeToString,
            google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__values__pb2.TagValue.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateTagValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.resourcemanager.v3.TagValues/CreateTagValue',
            google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__values__pb2.CreateTagValueRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateTagValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.resourcemanager.v3.TagValues/UpdateTagValue',
            google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__values__pb2.UpdateTagValueRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteTagValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.resourcemanager.v3.TagValues/DeleteTagValue',
            google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__values__pb2.DeleteTagValueRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetIamPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.resourcemanager.v3.TagValues/GetIamPolicy',
            google_dot_iam_dot_v1_dot_iam__policy__pb2.GetIamPolicyRequest.SerializeToString,
            google_dot_iam_dot_v1_dot_policy__pb2.Policy.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetIamPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.resourcemanager.v3.TagValues/SetIamPolicy',
            google_dot_iam_dot_v1_dot_iam__policy__pb2.SetIamPolicyRequest.SerializeToString,
            google_dot_iam_dot_v1_dot_policy__pb2.Policy.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TestIamPermissions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.resourcemanager.v3.TagValues/TestIamPermissions',
            google_dot_iam_dot_v1_dot_iam__policy__pb2.TestIamPermissionsRequest.SerializeToString,
            google_dot_iam_dot_v1_dot_iam__policy__pb2.TestIamPermissionsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
