# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.cloud.resourcemanager.v3 import tag_holds_pb2 as google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__holds__pb2
from google.longrunning import operations_pb2 as google_dot_longrunning_dot_operations__pb2


class TagHoldsStub(object):
    """Allow users to create and manage TagHolds for TagValues. TagHolds represent
    the use of a Tag Value that is not captured by TagBindings but
    should still block TagValue deletion (such as a reference in a policy
    condition). This service provides isolated failure domains by cloud location
    so that TagHolds can be managed in the same location as their usage.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateTagHold = channel.unary_unary(
                '/google.cloud.resourcemanager.v3.TagHolds/CreateTagHold',
                request_serializer=google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__holds__pb2.CreateTagHoldRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                )
        self.DeleteTagHold = channel.unary_unary(
                '/google.cloud.resourcemanager.v3.TagHolds/DeleteTagHold',
                request_serializer=google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__holds__pb2.DeleteTagHoldRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                )
        self.ListTagHolds = channel.unary_unary(
                '/google.cloud.resourcemanager.v3.TagHolds/ListTagHolds',
                request_serializer=google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__holds__pb2.ListTagHoldsRequest.SerializeToString,
                response_deserializer=google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__holds__pb2.ListTagHoldsResponse.FromString,
                )


class TagHoldsServicer(object):
    """Allow users to create and manage TagHolds for TagValues. TagHolds represent
    the use of a Tag Value that is not captured by TagBindings but
    should still block TagValue deletion (such as a reference in a policy
    condition). This service provides isolated failure domains by cloud location
    so that TagHolds can be managed in the same location as their usage.
    """

    def CreateTagHold(self, request, context):
        """Creates a TagHold. Returns ALREADY_EXISTS if a TagHold with the same
        resource and origin exists under the same TagValue.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTagHold(self, request, context):
        """Deletes a TagHold.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTagHolds(self, request, context):
        """Lists TagHolds under a TagValue.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TagHoldsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateTagHold': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTagHold,
                    request_deserializer=google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__holds__pb2.CreateTagHoldRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'DeleteTagHold': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTagHold,
                    request_deserializer=google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__holds__pb2.DeleteTagHoldRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'ListTagHolds': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTagHolds,
                    request_deserializer=google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__holds__pb2.ListTagHoldsRequest.FromString,
                    response_serializer=google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__holds__pb2.ListTagHoldsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'google.cloud.resourcemanager.v3.TagHolds', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TagHolds(object):
    """Allow users to create and manage TagHolds for TagValues. TagHolds represent
    the use of a Tag Value that is not captured by TagBindings but
    should still block TagValue deletion (such as a reference in a policy
    condition). This service provides isolated failure domains by cloud location
    so that TagHolds can be managed in the same location as their usage.
    """

    @staticmethod
    def CreateTagHold(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.resourcemanager.v3.TagHolds/CreateTagHold',
            google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__holds__pb2.CreateTagHoldRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteTagHold(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.resourcemanager.v3.TagHolds/DeleteTagHold',
            google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__holds__pb2.DeleteTagHoldRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListTagHolds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.resourcemanager.v3.TagHolds/ListTagHolds',
            google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__holds__pb2.ListTagHoldsRequest.SerializeToString,
            google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__holds__pb2.ListTagHoldsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
