# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.cloud.resourcemanager.v3 import tag_keys_pb2 as google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__keys__pb2
from google.iam.v1 import iam_policy_pb2 as google_dot_iam_dot_v1_dot_iam__policy__pb2
from google.iam.v1 import policy_pb2 as google_dot_iam_dot_v1_dot_policy__pb2
from google.longrunning import operations_pb2 as google_dot_longrunning_dot_operations__pb2


class TagKeysStub(object):
    """Allow users to create and manage tag keys.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListTagKeys = channel.unary_unary(
                '/google.cloud.resourcemanager.v3.TagKeys/ListTagKeys',
                request_serializer=google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__keys__pb2.ListTagKeysRequest.SerializeToString,
                response_deserializer=google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__keys__pb2.ListTagKeysResponse.FromString,
                )
        self.GetTagKey = channel.unary_unary(
                '/google.cloud.resourcemanager.v3.TagKeys/GetTagKey',
                request_serializer=google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__keys__pb2.GetTagKeyRequest.SerializeToString,
                response_deserializer=google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__keys__pb2.TagKey.FromString,
                )
        self.GetNamespacedTagKey = channel.unary_unary(
                '/google.cloud.resourcemanager.v3.TagKeys/GetNamespacedTagKey',
                request_serializer=google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__keys__pb2.GetNamespacedTagKeyRequest.SerializeToString,
                response_deserializer=google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__keys__pb2.TagKey.FromString,
                )
        self.CreateTagKey = channel.unary_unary(
                '/google.cloud.resourcemanager.v3.TagKeys/CreateTagKey',
                request_serializer=google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__keys__pb2.CreateTagKeyRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                )
        self.UpdateTagKey = channel.unary_unary(
                '/google.cloud.resourcemanager.v3.TagKeys/UpdateTagKey',
                request_serializer=google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__keys__pb2.UpdateTagKeyRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                )
        self.DeleteTagKey = channel.unary_unary(
                '/google.cloud.resourcemanager.v3.TagKeys/DeleteTagKey',
                request_serializer=google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__keys__pb2.DeleteTagKeyRequest.SerializeToString,
                response_deserializer=google_dot_longrunning_dot_operations__pb2.Operation.FromString,
                )
        self.GetIamPolicy = channel.unary_unary(
                '/google.cloud.resourcemanager.v3.TagKeys/GetIamPolicy',
                request_serializer=google_dot_iam_dot_v1_dot_iam__policy__pb2.GetIamPolicyRequest.SerializeToString,
                response_deserializer=google_dot_iam_dot_v1_dot_policy__pb2.Policy.FromString,
                )
        self.SetIamPolicy = channel.unary_unary(
                '/google.cloud.resourcemanager.v3.TagKeys/SetIamPolicy',
                request_serializer=google_dot_iam_dot_v1_dot_iam__policy__pb2.SetIamPolicyRequest.SerializeToString,
                response_deserializer=google_dot_iam_dot_v1_dot_policy__pb2.Policy.FromString,
                )
        self.TestIamPermissions = channel.unary_unary(
                '/google.cloud.resourcemanager.v3.TagKeys/TestIamPermissions',
                request_serializer=google_dot_iam_dot_v1_dot_iam__policy__pb2.TestIamPermissionsRequest.SerializeToString,
                response_deserializer=google_dot_iam_dot_v1_dot_iam__policy__pb2.TestIamPermissionsResponse.FromString,
                )


class TagKeysServicer(object):
    """Allow users to create and manage tag keys.
    """

    def ListTagKeys(self, request, context):
        """Lists all TagKeys for a parent resource.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTagKey(self, request, context):
        """Retrieves a TagKey. This method will return `PERMISSION_DENIED` if the
        key does not exist or the user does not have permission to view it.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNamespacedTagKey(self, request, context):
        """Retrieves a TagKey by its namespaced name.
        This method will return `PERMISSION_DENIED` if the key does not exist
        or the user does not have permission to view it.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTagKey(self, request, context):
        """Creates a new TagKey. If another request with the same parameters is
        sent while the original request is in process, the second request
        will receive an error. A maximum of 1000 TagKeys can exist under a parent
        at any given time.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTagKey(self, request, context):
        """Updates the attributes of the TagKey resource.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTagKey(self, request, context):
        """Deletes a TagKey. The TagKey cannot be deleted if it has any child
        TagValues.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIamPolicy(self, request, context):
        """Gets the access control policy for a TagKey. The returned policy may be
        empty if no such policy or resource exists. The `resource` field should
        be the TagKey's resource name. For example, "tagKeys/1234".
        The caller must have
        `cloudresourcemanager.googleapis.com/tagKeys.getIamPolicy` permission on
        the specified TagKey.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetIamPolicy(self, request, context):
        """Sets the access control policy on a TagKey, replacing any existing
        policy. The `resource` field should be the TagKey's resource name.
        For example, "tagKeys/1234".
        The caller must have `resourcemanager.tagKeys.setIamPolicy` permission
        on the identified tagValue.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TestIamPermissions(self, request, context):
        """Returns permissions that a caller has on the specified TagKey.
        The `resource` field should be the TagKey's resource name.
        For example, "tagKeys/1234".

        There are no permissions required for making this API call.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TagKeysServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListTagKeys': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTagKeys,
                    request_deserializer=google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__keys__pb2.ListTagKeysRequest.FromString,
                    response_serializer=google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__keys__pb2.ListTagKeysResponse.SerializeToString,
            ),
            'GetTagKey': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTagKey,
                    request_deserializer=google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__keys__pb2.GetTagKeyRequest.FromString,
                    response_serializer=google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__keys__pb2.TagKey.SerializeToString,
            ),
            'GetNamespacedTagKey': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNamespacedTagKey,
                    request_deserializer=google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__keys__pb2.GetNamespacedTagKeyRequest.FromString,
                    response_serializer=google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__keys__pb2.TagKey.SerializeToString,
            ),
            'CreateTagKey': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTagKey,
                    request_deserializer=google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__keys__pb2.CreateTagKeyRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'UpdateTagKey': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTagKey,
                    request_deserializer=google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__keys__pb2.UpdateTagKeyRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'DeleteTagKey': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTagKey,
                    request_deserializer=google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__keys__pb2.DeleteTagKeyRequest.FromString,
                    response_serializer=google_dot_longrunning_dot_operations__pb2.Operation.SerializeToString,
            ),
            'GetIamPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIamPolicy,
                    request_deserializer=google_dot_iam_dot_v1_dot_iam__policy__pb2.GetIamPolicyRequest.FromString,
                    response_serializer=google_dot_iam_dot_v1_dot_policy__pb2.Policy.SerializeToString,
            ),
            'SetIamPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.SetIamPolicy,
                    request_deserializer=google_dot_iam_dot_v1_dot_iam__policy__pb2.SetIamPolicyRequest.FromString,
                    response_serializer=google_dot_iam_dot_v1_dot_policy__pb2.Policy.SerializeToString,
            ),
            'TestIamPermissions': grpc.unary_unary_rpc_method_handler(
                    servicer.TestIamPermissions,
                    request_deserializer=google_dot_iam_dot_v1_dot_iam__policy__pb2.TestIamPermissionsRequest.FromString,
                    response_serializer=google_dot_iam_dot_v1_dot_iam__policy__pb2.TestIamPermissionsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'google.cloud.resourcemanager.v3.TagKeys', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TagKeys(object):
    """Allow users to create and manage tag keys.
    """

    @staticmethod
    def ListTagKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.resourcemanager.v3.TagKeys/ListTagKeys',
            google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__keys__pb2.ListTagKeysRequest.SerializeToString,
            google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__keys__pb2.ListTagKeysResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTagKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.resourcemanager.v3.TagKeys/GetTagKey',
            google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__keys__pb2.GetTagKeyRequest.SerializeToString,
            google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__keys__pb2.TagKey.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetNamespacedTagKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.resourcemanager.v3.TagKeys/GetNamespacedTagKey',
            google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__keys__pb2.GetNamespacedTagKeyRequest.SerializeToString,
            google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__keys__pb2.TagKey.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateTagKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.resourcemanager.v3.TagKeys/CreateTagKey',
            google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__keys__pb2.CreateTagKeyRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateTagKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.resourcemanager.v3.TagKeys/UpdateTagKey',
            google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__keys__pb2.UpdateTagKeyRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteTagKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.resourcemanager.v3.TagKeys/DeleteTagKey',
            google_dot_cloud_dot_resourcemanager_dot_v3_dot_tag__keys__pb2.DeleteTagKeyRequest.SerializeToString,
            google_dot_longrunning_dot_operations__pb2.Operation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetIamPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.resourcemanager.v3.TagKeys/GetIamPolicy',
            google_dot_iam_dot_v1_dot_iam__policy__pb2.GetIamPolicyRequest.SerializeToString,
            google_dot_iam_dot_v1_dot_policy__pb2.Policy.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetIamPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.resourcemanager.v3.TagKeys/SetIamPolicy',
            google_dot_iam_dot_v1_dot_iam__policy__pb2.SetIamPolicyRequest.SerializeToString,
            google_dot_iam_dot_v1_dot_policy__pb2.Policy.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TestIamPermissions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/google.cloud.resourcemanager.v3.TagKeys/TestIamPermissions',
            google_dot_iam_dot_v1_dot_iam__policy__pb2.TestIamPermissionsRequest.SerializeToString,
            google_dot_iam_dot_v1_dot_iam__policy__pb2.TestIamPermissionsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
