"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2025 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.field_mask_pb2
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.timestamp_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class TagValue(google.protobuf.message.Message):
    """A TagValue is a child of a particular TagKey. This is used to group
    cloud resources for the purpose of controlling them using policies.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    PARENT_FIELD_NUMBER: builtins.int
    SHORT_NAME_FIELD_NUMBER: builtins.int
    NAMESPACED_NAME_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    CREATE_TIME_FIELD_NUMBER: builtins.int
    UPDATE_TIME_FIELD_NUMBER: builtins.int
    ETAG_FIELD_NUMBER: builtins.int
    name: builtins.str
    """Immutable. Resource name for TagValue in the format `tagValues/456`."""
    parent: builtins.str
    """Immutable. The resource name of the new TagValue's parent TagKey.
    Must be of the form `tagKeys/{tag_key_id}`.
    """
    short_name: builtins.str
    """Required. Immutable. User-assigned short name for TagValue. The short name
    should be unique for TagValues within the same parent TagKey.

    The short name must be 63 characters or less, beginning and ending with
    an alphanumeric character ([a-z0-9A-Z]) with dashes (-), underscores (_),
    dots (.), and alphanumerics between.
    """
    namespaced_name: builtins.str
    """Output only. The namespaced name of the TagValue. Can be in the form
    `{organization_id}/{tag_key_short_name}/{tag_value_short_name}` or
    `{project_id}/{tag_key_short_name}/{tag_value_short_name}` or
    `{project_number}/{tag_key_short_name}/{tag_value_short_name}`.
    """
    description: builtins.str
    """Optional. User-assigned description of the TagValue.
    Must not exceed 256 characters.

    Read-write.
    """
    etag: builtins.str
    """Optional. Entity tag which users can pass to prevent race conditions. This
    field is always set in server responses. See UpdateTagValueRequest for
    details.
    """
    @property
    def create_time(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Output only. Creation time."""

    @property
    def update_time(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Output only. Update time."""

    def __init__(
        self,
        *,
        name: builtins.str = ...,
        parent: builtins.str = ...,
        short_name: builtins.str = ...,
        namespaced_name: builtins.str = ...,
        description: builtins.str = ...,
        create_time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        update_time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        etag: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["create_time", b"create_time", "update_time", b"update_time"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["create_time", b"create_time", "description", b"description", "etag", b"etag", "name", b"name", "namespaced_name", b"namespaced_name", "parent", b"parent", "short_name", b"short_name", "update_time", b"update_time"]) -> None: ...

global___TagValue = TagValue

@typing.final
class ListTagValuesRequest(google.protobuf.message.Message):
    """The request message for listing TagValues for the specified TagKey.
    Resource name for TagKey, parent of the TagValues to be listed,
    in the format `tagKeys/123`.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PARENT_FIELD_NUMBER: builtins.int
    PAGE_SIZE_FIELD_NUMBER: builtins.int
    PAGE_TOKEN_FIELD_NUMBER: builtins.int
    parent: builtins.str
    """Required."""
    page_size: builtins.int
    """Optional. The maximum number of TagValues to return in the response. The
    server allows a maximum of 300 TagValues to return. If unspecified, the
    server will use 100 as the default.
    """
    page_token: builtins.str
    """Optional. A pagination token returned from a previous call to
    `ListTagValues` that indicates where this listing should continue from.
    """
    def __init__(
        self,
        *,
        parent: builtins.str = ...,
        page_size: builtins.int = ...,
        page_token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["page_size", b"page_size", "page_token", b"page_token", "parent", b"parent"]) -> None: ...

global___ListTagValuesRequest = ListTagValuesRequest

@typing.final
class ListTagValuesResponse(google.protobuf.message.Message):
    """The ListTagValues response."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TAG_VALUES_FIELD_NUMBER: builtins.int
    NEXT_PAGE_TOKEN_FIELD_NUMBER: builtins.int
    next_page_token: builtins.str
    """A pagination token returned from a previous call to `ListTagValues`
    that indicates from where listing should continue. This is currently not
    used, but the server may at any point start supplying a valid token.
    """
    @property
    def tag_values(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TagValue]:
        """A possibly paginated list of TagValues that are direct descendants of
        the specified parent TagKey.
        """

    def __init__(
        self,
        *,
        tag_values: collections.abc.Iterable[global___TagValue] | None = ...,
        next_page_token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["next_page_token", b"next_page_token", "tag_values", b"tag_values"]) -> None: ...

global___ListTagValuesResponse = ListTagValuesResponse

@typing.final
class GetTagValueRequest(google.protobuf.message.Message):
    """The request message for getting a TagValue."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    """Required. Resource name for TagValue to be fetched in the format
    `tagValues/456`.
    """
    def __init__(
        self,
        *,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name"]) -> None: ...

global___GetTagValueRequest = GetTagValueRequest

@typing.final
class GetNamespacedTagValueRequest(google.protobuf.message.Message):
    """The request message for getting a TagValue by its namespaced name."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    """Required. A namespaced tag value name in the following format:

      `{parentId}/{tagKeyShort}/{tagValueShort}`

    Examples:
    - `42/foo/abc` for a value with short name "abc" under the key with short
      name "foo" under the organization with ID 42
    - `r2-d2/bar/xyz` for a value with short name "xyz" under the key with
       short name "bar" under the project with ID "r2-d2"
    """
    def __init__(
        self,
        *,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name"]) -> None: ...

global___GetNamespacedTagValueRequest = GetNamespacedTagValueRequest

@typing.final
class CreateTagValueRequest(google.protobuf.message.Message):
    """The request message for creating a TagValue."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TAG_VALUE_FIELD_NUMBER: builtins.int
    VALIDATE_ONLY_FIELD_NUMBER: builtins.int
    validate_only: builtins.bool
    """Optional. Set as true to perform the validations necessary for creating the
    resource, but not actually perform the action.
    """
    @property
    def tag_value(self) -> global___TagValue:
        """Required. The TagValue to be created. Only fields `short_name`,
        `description`, and `parent` are considered during the creation request.
        """

    def __init__(
        self,
        *,
        tag_value: global___TagValue | None = ...,
        validate_only: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["tag_value", b"tag_value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["tag_value", b"tag_value", "validate_only", b"validate_only"]) -> None: ...

global___CreateTagValueRequest = CreateTagValueRequest

@typing.final
class CreateTagValueMetadata(google.protobuf.message.Message):
    """Runtime operation information for creating a TagValue."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___CreateTagValueMetadata = CreateTagValueMetadata

@typing.final
class UpdateTagValueRequest(google.protobuf.message.Message):
    """The request message for updating a TagValue."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TAG_VALUE_FIELD_NUMBER: builtins.int
    UPDATE_MASK_FIELD_NUMBER: builtins.int
    VALIDATE_ONLY_FIELD_NUMBER: builtins.int
    validate_only: builtins.bool
    """Optional. True to perform validations necessary for updating the resource,
    but not actually perform the action.
    """
    @property
    def tag_value(self) -> global___TagValue:
        """Required. The new definition of the TagValue. Only fields `description` and
        `etag` fields can be updated by this request. If the `etag` field is
        nonempty, it must match the `etag` field of the existing ControlGroup.
        Otherwise, `ABORTED` will be returned.
        """

    @property
    def update_mask(self) -> google.protobuf.field_mask_pb2.FieldMask:
        """Optional. Fields to be updated."""

    def __init__(
        self,
        *,
        tag_value: global___TagValue | None = ...,
        update_mask: google.protobuf.field_mask_pb2.FieldMask | None = ...,
        validate_only: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["tag_value", b"tag_value", "update_mask", b"update_mask"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["tag_value", b"tag_value", "update_mask", b"update_mask", "validate_only", b"validate_only"]) -> None: ...

global___UpdateTagValueRequest = UpdateTagValueRequest

@typing.final
class UpdateTagValueMetadata(google.protobuf.message.Message):
    """Runtime operation information for updating a TagValue."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___UpdateTagValueMetadata = UpdateTagValueMetadata

@typing.final
class DeleteTagValueRequest(google.protobuf.message.Message):
    """The request message for deleting a TagValue."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    VALIDATE_ONLY_FIELD_NUMBER: builtins.int
    ETAG_FIELD_NUMBER: builtins.int
    name: builtins.str
    """Required. Resource name for TagValue to be deleted in the format
    tagValues/456.
    """
    validate_only: builtins.bool
    """Optional. Set as true to perform the validations necessary for deletion,
    but not actually perform the action.
    """
    etag: builtins.str
    """Optional. The etag known to the client for the expected state of the
    TagValue. This is to be used for optimistic concurrency.
    """
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        validate_only: builtins.bool = ...,
        etag: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["etag", b"etag", "name", b"name", "validate_only", b"validate_only"]) -> None: ...

global___DeleteTagValueRequest = DeleteTagValueRequest

@typing.final
class DeleteTagValueMetadata(google.protobuf.message.Message):
    """Runtime operation information for deleting a TagValue."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___DeleteTagValueMetadata = DeleteTagValueMetadata
