version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "dependabot"
    ignore:
      - dependency-name: "grpcio"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "dependabot"
    groups:
      github-actions:
        patterns:
          - "*"
