# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: osprey/rpc/pigeon/v1/options.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"osprey/rpc/pigeon/v1/options.proto\x12\x14osprey.rpc.pigeon.v1\x1a google/protobuf/descriptor.proto\"\xaf\x01\n\rRoutingConfig\x12\x13\n\x0brequest_key\x18\x01 \x01(\t\x12/\n\x04type\x18\x02 \x01(\x0e\x32!.osprey.rpc.pigeon.v1.RoutingType\x12\x14\n\x0cresponse_key\x18\x03 \x01(\t\x12\x42\n\x12key_extractor_type\x18\x04 \x01(\x0e\x32&.osprey.rpc.pigeon.v1.KeyExtractorType*|\n\x0bRoutingType\x12\x1c\n\x18ROUTING_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n\x18ROUTING_TYPE_ROUND_ROBIN\x10\x01\x12\x17\n\x13ROUTING_TYPE_SCALAR\x10\x02\x12\x18\n\x14ROUTING_TYPE_CHUNKED\x10\x03*P\n\x10KeyExtractorType\x12\x1c\n\x18KEY_EXTRACTOR_TYPE_VALUE\x10\x00\x12\x1e\n\x1aKEY_EXTRACTOR_TYPE_MAP_KEY\x10\x01:f\n\x16\x64\x65\x66\x61ult_routing_config\x12\x1f.google.protobuf.ServiceOptions\x18\x89\x9e\x03 \x01(\x0b\x32#.osprey.rpc.pigeon.v1.RoutingConfig:]\n\x0erouting_config\x12\x1e.google.protobuf.MethodOptions\x18\x8a\x9e\x03 \x01(\x0b\x32#.osprey.rpc.pigeon.v1.RoutingConfigb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'osprey.rpc.pigeon.v1.options_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:
  google_dot_protobuf_dot_descriptor__pb2.ServiceOptions.RegisterExtension(default_routing_config)
  google_dot_protobuf_dot_descriptor__pb2.MethodOptions.RegisterExtension(routing_config)

  DESCRIPTOR._options = None
  _ROUTINGTYPE._serialized_start=272
  _ROUTINGTYPE._serialized_end=396
  _KEYEXTRACTORTYPE._serialized_start=398
  _KEYEXTRACTORTYPE._serialized_end=478
  _ROUTINGCONFIG._serialized_start=95
  _ROUTINGCONFIG._serialized_end=270
# @@protoc_insertion_point(module_scope)
