# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: osprey/rpc/actions/v1/application.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from osprey.rpc.actions.v1 import user_pb2 as osprey_dot_rpc_dot_actions_dot_v1_dot_user__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'osprey/rpc/actions/v1/application.proto\x12\x15osprey.rpc.actions.v1\x1a osprey/rpc/actions/v1/user.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xb0\x01\n\x0b\x41pplication\x12\n\n\x02id\x18\x01 \x01(\x06\x12\x0e\n\x06\x62ot_id\x18\x02 \x01(\x06\x12(\n\x03\x62ot\x18\x03 \x01(\x0b\x32\x1b.osprey.rpc.actions.v1.User\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x1e\n\x16\x65ventual_owner_user_id\x18\x05 \x01(\x06\x12-\n\x07team_id\x18\x06 \x01(\x0b\x32\x1c.google.protobuf.StringValueb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'osprey.rpc.actions.v1.application_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _APPLICATION._serialized_start=166
  _APPLICATION._serialized_end=342
# @@protoc_insertion_point(module_scope)
