"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.timestamp_pb2
import google.protobuf.wrappers_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class CaptchaResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class SigsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    CAPTCHA_SERVICE_FIELD_NUMBER: builtins.int
    SUCCESS_FIELD_NUMBER: builtins.int
    CHALLENGE_TS_FIELD_NUMBER: builtins.int
    ERROR_CODES_FIELD_NUMBER: builtins.int
    SIGS_FIELD_NUMBER: builtins.int
    SOLVE_TOKEN_FIELD_NUMBER: builtins.int
    HOSTNAME_FIELD_NUMBER: builtins.int
    SCORE_FIELD_NUMBER: builtins.int
    SCORE_REASON_FIELD_NUMBER: builtins.int
    SITEKEY_FIELD_NUMBER: builtins.int
    SCOPED_UID_0_FIELD_NUMBER: builtins.int
    SCOPED_UID_1_FIELD_NUMBER: builtins.int
    captcha_service: builtins.str
    success: builtins.bool
    @property
    def challenge_ts(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def error_codes(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def sigs(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    @property
    def solve_token(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def hostname(self) -> google.protobuf.wrappers_pb2.StringValue:
        """HCaptcha and RECaptcha"""

    @property
    def score(self) -> google.protobuf.wrappers_pb2.FloatValue:
        """HCaptcha-only fields"""

    @property
    def score_reason(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def sitekey(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def scoped_uid_0(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def scoped_uid_1(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    def __init__(
        self,
        *,
        captcha_service: builtins.str = ...,
        success: builtins.bool = ...,
        challenge_ts: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        error_codes: collections.abc.Iterable[builtins.str] | None = ...,
        sigs: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        solve_token: google.protobuf.wrappers_pb2.StringValue | None = ...,
        hostname: google.protobuf.wrappers_pb2.StringValue | None = ...,
        score: google.protobuf.wrappers_pb2.FloatValue | None = ...,
        score_reason: collections.abc.Iterable[builtins.str] | None = ...,
        sitekey: google.protobuf.wrappers_pb2.StringValue | None = ...,
        scoped_uid_0: google.protobuf.wrappers_pb2.StringValue | None = ...,
        scoped_uid_1: google.protobuf.wrappers_pb2.StringValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["challenge_ts", b"challenge_ts", "hostname", b"hostname", "scoped_uid_0", b"scoped_uid_0", "scoped_uid_1", b"scoped_uid_1", "score", b"score", "sitekey", b"sitekey", "solve_token", b"solve_token"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["captcha_service", b"captcha_service", "challenge_ts", b"challenge_ts", "error_codes", b"error_codes", "hostname", b"hostname", "scoped_uid_0", b"scoped_uid_0", "scoped_uid_1", b"scoped_uid_1", "score", b"score", "score_reason", b"score_reason", "sigs", b"sigs", "sitekey", b"sitekey", "solve_token", b"solve_token", "success", b"success"]) -> None: ...

global___CaptchaResponse = CaptchaResponse
