# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: osprey/rpc/actions/v1/captcha.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#osprey/rpc/actions/v1/captcha.proto\x12\x15osprey.rpc.actions.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xab\x04\n\x0f\x43\x61ptchaResponse\x12\x17\n\x0f\x63\x61ptcha_service\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x30\n\x0c\x63hallenge_ts\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x13\n\x0b\x65rror_codes\x18\x04 \x03(\t\x12>\n\x04sigs\x18\x05 \x03(\x0b\x32\x30.osprey.rpc.actions.v1.CaptchaResponse.SigsEntry\x12\x31\n\x0bsolve_token\x18\x06 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12.\n\x08hostname\x18\x07 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12*\n\x05score\x18\x08 \x01(\x0b\x32\x1b.google.protobuf.FloatValue\x12\x14\n\x0cscore_reason\x18\t \x03(\t\x12-\n\x07sitekey\x18\n \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x32\n\x0cscoped_uid_0\x18\x0b \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x32\n\x0cscoped_uid_1\x18\x0c \x01(\x0b\x32\x1c.google.protobuf.StringValue\x1a+\n\tSigsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'osprey.rpc.actions.v1.captcha_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CAPTCHARESPONSE_SIGSENTRY._options = None
  _CAPTCHARESPONSE_SIGSENTRY._serialized_options = b'8\001'
  _CAPTCHARESPONSE._serialized_start=128
  _CAPTCHARESPONSE._serialized_end=683
  _CAPTCHARESPONSE_SIGSENTRY._serialized_start=640
  _CAPTCHARESPONSE_SIGSENTRY._serialized_end=683
# @@protoc_insertion_point(module_scope)
