# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: osprey/rpc/actions/v1/channel.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#osprey/rpc/actions/v1/channel.proto\x12\x15osprey.rpc.actions.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"%\n\x17PrivateChannelRecipient\x12\n\n\x02id\x18\x01 \x01(\x06\"\x9d\x01\n\x07\x43hannel\x12\n\n\x02id\x18\x01 \x01(\x06\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\x05\x12\x0f\n\x07is_nsfw\x18\x04 \x01(\x08\x12\x15\n\rmessage_count\x18\x05 \x01(\x05\x12\x42\n\nrecipients\x18\x06 \x03(\x0b\x32..osprey.rpc.actions.v1.PrivateChannelRecipientb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'osprey.rpc.actions.v1.channel_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PRIVATECHANNELRECIPIENT._serialized_start=127
  _PRIVATECHANNELRECIPIENT._serialized_end=164
  _CHANNEL._serialized_start=167
  _CHANNEL._serialized_end=324
# @@protoc_insertion_point(module_scope)
