"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class PrivateChannelRecipient(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    id: builtins.int
    def __init__(
        self,
        *,
        id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["id", b"id"]) -> None: ...

global___PrivateChannelRecipient = PrivateChannelRecipient

@typing.final
class Channel(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    IS_NSFW_FIELD_NUMBER: builtins.int
    MESSAGE_COUNT_FIELD_NUMBER: builtins.int
    RECIPIENTS_FIELD_NUMBER: builtins.int
    id: builtins.int
    name: builtins.str
    type: builtins.int
    is_nsfw: builtins.bool
    message_count: builtins.int
    @property
    def recipients(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PrivateChannelRecipient]: ...
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        name: builtins.str = ...,
        type: builtins.int = ...,
        is_nsfw: builtins.bool = ...,
        message_count: builtins.int = ...,
        recipients: collections.abc.Iterable[global___PrivateChannelRecipient] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["id", b"id", "is_nsfw", b"is_nsfw", "message_count", b"message_count", "name", b"name", "recipients", b"recipients", "type", b"type"]) -> None: ...

global___Channel = Channel
