# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: osprey/rpc/actions/v1/guild.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!osprey/rpc/actions/v1/guild.proto\x12\x15osprey.rpc.actions.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xc1\x03\n\x05Guild\x12\n\n\x02id\x18\x01 \x01(\x06\x12\x30\n\x05owner\x18\x02 \x01(\x0b\x32!.osprey.rpc.actions.v1.GuildOwner\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x31\n\x0b\x64\x65scription\x18\x04 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12/\n\ticon_hash\x18\x05 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x0f\n\x07is_nsfw\x18\x06 \x01(\x08\x12\x12\n\nnsfw_level\x18\x07 \x01(\x05\x12\x14\n\x0cmember_count\x18\x08 \x01(\x05\x12\"\n\x1apremium_subscription_count\x18\t \x01(\x05\x12\x10\n\x08\x66\x65\x61tures\x18\n \x03(\t\x12\x18\n\x10has_public_stage\x18\x0b \x01(\x08\x12\x15\n\rchannel_names\x18\x0c \x03(\t\x12\x12\n\nrole_names\x18\r \x03(\t\x12\x1a\n\x12verification_level\x18\x0e \x01(\x05\x12\x36\n\x08template\x18\x0f \x01(\x0b\x32$.osprey.rpc.actions.v1.GuildTemplate\"\x18\n\nGuildOwner\x12\n\n\x02id\x18\x01 \x01(\x06\"\xeb\x01\n\rGuildTemplate\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x31\n\x0b\x64\x65scription\x18\x03 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x12\n\ncreator_id\x18\x04 \x01(\x06\x12.\n\ncreated_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x17\n\x0fsource_guild_id\x18\x07 \x01(\x06\"t\n\x0bGuildMember\x12\x10\n\x08guild_id\x18\x01 \x01(\x06\x12-\n\tjoined_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x13\n\x0bpermissions\x18\x03 \x01(\x06\x12\x0f\n\x07user_id\x18\x04 \x01(\x06\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'osprey.rpc.actions.v1.guild_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GUILD._serialized_start=126
  _GUILD._serialized_end=575
  _GUILDOWNER._serialized_start=577
  _GUILDOWNER._serialized_end=601
  _GUILDTEMPLATE._serialized_start=604
  _GUILDTEMPLATE._serialized_end=839
  _GUILDMEMBER._serialized_start=841
  _GUILDMEMBER._serialized_end=957
# @@protoc_insertion_point(module_scope)
