"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import google.protobuf.timestamp_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class GuildInvite(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CODE_FIELD_NUMBER: builtins.int
    MAX_AGE_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    MAX_USES_FIELD_NUMBER: builtins.int
    TEMPORARY_FIELD_NUMBER: builtins.int
    CUSTOM_FIELD_NUMBER: builtins.int
    code: builtins.str
    max_age: builtins.int
    max_uses: builtins.int
    temporary: builtins.bool
    custom: builtins.bool
    @property
    def created_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        code: builtins.str = ...,
        max_age: builtins.int = ...,
        created_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        max_uses: builtins.int = ...,
        temporary: builtins.bool = ...,
        custom: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["created_at", b"created_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["code", b"code", "created_at", b"created_at", "custom", b"custom", "max_age", b"max_age", "max_uses", b"max_uses", "temporary", b"temporary"]) -> None: ...

global___GuildInvite = GuildInvite
