"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.wrappers_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class HttpRequestData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class HeadersEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    HEADERS_FIELD_NUMBER: builtins.int
    URL_FIELD_NUMBER: builtins.int
    ENDPOINT_FIELD_NUMBER: builtins.int
    QUERY_STRING_FIELD_NUMBER: builtins.int
    METHOD_FIELD_NUMBER: builtins.int
    API_VERSION_FIELD_NUMBER: builtins.int
    REMOTE_ADDR_FIELD_NUMBER: builtins.int
    REMOTE_ADDR_IS_WHITELISTED_FIELD_NUMBER: builtins.int
    url: builtins.str
    method: builtins.str
    @property
    def headers(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    @property
    def endpoint(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def query_string(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def api_version(self) -> google.protobuf.wrappers_pb2.Int32Value: ...
    @property
    def remote_addr(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def remote_addr_is_whitelisted(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
    def __init__(
        self,
        *,
        headers: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        url: builtins.str = ...,
        endpoint: google.protobuf.wrappers_pb2.StringValue | None = ...,
        query_string: google.protobuf.wrappers_pb2.StringValue | None = ...,
        method: builtins.str = ...,
        api_version: google.protobuf.wrappers_pb2.Int32Value | None = ...,
        remote_addr: google.protobuf.wrappers_pb2.StringValue | None = ...,
        remote_addr_is_whitelisted: google.protobuf.wrappers_pb2.BoolValue | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["api_version", b"api_version", "endpoint", b"endpoint", "query_string", b"query_string", "remote_addr", b"remote_addr", "remote_addr_is_whitelisted", b"remote_addr_is_whitelisted"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["api_version", b"api_version", "endpoint", b"endpoint", "headers", b"headers", "method", b"method", "query_string", b"query_string", "remote_addr", b"remote_addr", "remote_addr_is_whitelisted", b"remote_addr_is_whitelisted", "url", b"url"]) -> None: ...

global___HttpRequestData = HttpRequestData

@typing.final
class Properties(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OS_FIELD_NUMBER: builtins.int
    OS_VERSION_FIELD_NUMBER: builtins.int
    BROWSER_FIELD_NUMBER: builtins.int
    BROWSER_VERSION_FIELD_NUMBER: builtins.int
    BROWSER_USER_AGENT_FIELD_NUMBER: builtins.int
    DEVICE_FIELD_NUMBER: builtins.int
    REFERRER_FIELD_NUMBER: builtins.int
    REFERRING_DOMAIN_FIELD_NUMBER: builtins.int
    RELEASE_CHANNEL_FIELD_NUMBER: builtins.int
    CLIENT_VERSION_FIELD_NUMBER: builtins.int
    CLIENT_BUILD_NUMBER_FIELD_NUMBER: builtins.int
    LOCATION_FIELD_NUMBER: builtins.int
    SYSTEM_LOCALE_FIELD_NUMBER: builtins.int
    CHOSEN_LOCALE_FIELD_NUMBER: builtins.int
    DEVICE_VENDOR_ID_FIELD_NUMBER: builtins.int
    CFDUID_FIELD_NUMBER: builtins.int
    CFDUID_SIGNED_FIELD_NUMBER: builtins.int
    cfduid_signed: builtins.bool
    @property
    def os(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def os_version(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def browser(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def browser_version(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def browser_user_agent(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def device(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def referrer(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def referring_domain(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def release_channel(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def client_version(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def client_build_number(self) -> google.protobuf.wrappers_pb2.Int64Value: ...
    @property
    def location(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def system_locale(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def chosen_locale(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def device_vendor_id(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def cfduid(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    def __init__(
        self,
        *,
        os: google.protobuf.wrappers_pb2.StringValue | None = ...,
        os_version: google.protobuf.wrappers_pb2.StringValue | None = ...,
        browser: google.protobuf.wrappers_pb2.StringValue | None = ...,
        browser_version: google.protobuf.wrappers_pb2.StringValue | None = ...,
        browser_user_agent: google.protobuf.wrappers_pb2.StringValue | None = ...,
        device: google.protobuf.wrappers_pb2.StringValue | None = ...,
        referrer: google.protobuf.wrappers_pb2.StringValue | None = ...,
        referring_domain: google.protobuf.wrappers_pb2.StringValue | None = ...,
        release_channel: google.protobuf.wrappers_pb2.StringValue | None = ...,
        client_version: google.protobuf.wrappers_pb2.StringValue | None = ...,
        client_build_number: google.protobuf.wrappers_pb2.Int64Value | None = ...,
        location: google.protobuf.wrappers_pb2.StringValue | None = ...,
        system_locale: google.protobuf.wrappers_pb2.StringValue | None = ...,
        chosen_locale: google.protobuf.wrappers_pb2.StringValue | None = ...,
        device_vendor_id: google.protobuf.wrappers_pb2.StringValue | None = ...,
        cfduid: google.protobuf.wrappers_pb2.StringValue | None = ...,
        cfduid_signed: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["browser", b"browser", "browser_user_agent", b"browser_user_agent", "browser_version", b"browser_version", "cfduid", b"cfduid", "chosen_locale", b"chosen_locale", "client_build_number", b"client_build_number", "client_version", b"client_version", "device", b"device", "device_vendor_id", b"device_vendor_id", "location", b"location", "os", b"os", "os_version", b"os_version", "referrer", b"referrer", "referring_domain", b"referring_domain", "release_channel", b"release_channel", "system_locale", b"system_locale"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["browser", b"browser", "browser_user_agent", b"browser_user_agent", "browser_version", b"browser_version", "cfduid", b"cfduid", "cfduid_signed", b"cfduid_signed", "chosen_locale", b"chosen_locale", "client_build_number", b"client_build_number", "client_version", b"client_version", "device", b"device", "device_vendor_id", b"device_vendor_id", "location", b"location", "os", b"os", "os_version", b"os_version", "referrer", b"referrer", "referring_domain", b"referring_domain", "release_channel", b"release_channel", "system_locale", b"system_locale"]) -> None: ...

global___Properties = Properties
