# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: osprey/rpc/actions/v1/user.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n osprey/rpc/actions/v1/user.proto\x12\x15osprey.rpc.actions.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xc1\x05\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x06\x12\x13\n\x0bmfa_enabled\x18\x02 \x01(\x08\x12\x0b\n\x03\x62ot\x18\x03 \x01(\x08\x12\x10\n\x08username\x18\x04 \x01(\t\x12\x15\n\rdiscriminator\x18\x05 \x01(\t\x12+\n\x05\x65mail\x18\x06 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x16\n\x0e\x65mail_verified\x18\x07 \x01(\x08\x12+\n\x05phone\x18\x08 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12,\n\x06\x61vatar\x18\t \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x0b\n\x03\x62io\x18\x0b \x01(\t\x12(\n\x02ip\x18\x0c \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x19\n\x11ip_is_whitelisted\x18\r \x01(\x08\x12\x32\n\x0cpremium_type\x18\x0e \x01(\x0b\x32\x1c.google.protobuf.UInt32Value\x12\x31\n\rpremium_until\x18\x0f \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\r\n\x05\x66lags\x18\x10 \x01(\x06\x12\x14\n\x0cpublic_flags\x18\x11 \x01(\x06\x12!\n\x19suspicious_activity_flags\x18\x12 \x01(\x05\x12\x35\n\x0frequired_action\x18\x13 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x1a\n\x12is_unique_username\x18\x14 \x01(\x08\x12\x31\n\x0bglobal_name\x18\x15 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12/\n\thub_email\x18\x16 \x01(\x0b\x32\x1c.google.protobuf.StringValueJ\x04\x08\n\x10\x0bJ\x04\x08\x17\x10\x18\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'osprey.rpc.actions.v1.user_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USER._serialized_start=125
  _USER._serialized_end=830
# @@protoc_insertion_point(module_scope)
