# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: osprey/rpc/etcd_watcherd/v1/etcd_watcherd.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'osprey/rpc/etcd_watcherd/v1/etcd_watcherd.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/osprey/rpc/etcd_watcherd/v1/etcd_watcherd.proto\x12\x1bosprey.rpc.etcd_watcherd.v1\x1a\x1egoogle/protobuf/wrappers.proto\"\x1e\n\x0fWatchKeyRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"?\n\x10WatchKeyResponse\x12+\n\x05value\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\"\'\n\x18WatchKeyRecursiveRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"\x91\x04\n\x19WatchKeyRecursiveResponse\x12T\n\tfull_sync\x18\x01 \x01(\x0b\x32?.osprey.rpc.etcd_watcherd.v1.WatchKeyRecursiveResponse.FullSyncH\x00\x12R\n\x08sync_one\x18\x02 \x01(\x0b\x32>.osprey.rpc.etcd_watcherd.v1.WatchKeyRecursiveResponse.SyncOneH\x00\x12V\n\ndelete_one\x18\x03 \x01(\x0b\x32@.osprey.rpc.etcd_watcherd.v1.WatchKeyRecursiveResponse.DeleteOneH\x00\x1a\x93\x01\n\x08\x46ullSync\x12Y\n\x05items\x18\x01 \x03(\x0b\x32J.osprey.rpc.etcd_watcherd.v1.WatchKeyRecursiveResponse.FullSync.ItemsEntry\x1a,\n\nItemsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a%\n\x07SyncOne\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x1a,\n\tDeleteOne\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x12\n\nprev_value\x18\x02 \x01(\tB\x07\n\x05\x65vent2\x87\x02\n\x13\x45tcdWatcherdService\x12i\n\x08WatchKey\x12,.osprey.rpc.etcd_watcherd.v1.WatchKeyRequest\x1a-.osprey.rpc.etcd_watcherd.v1.WatchKeyResponse0\x01\x12\x84\x01\n\x11WatchKeyRecursive\x12\x35.osprey.rpc.etcd_watcherd.v1.WatchKeyRecursiveRequest\x1a\x36.osprey.rpc.etcd_watcherd.v1.WatchKeyRecursiveResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'osprey.rpc.etcd_watcherd.v1.etcd_watcherd_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WATCHKEYRECURSIVERESPONSE_FULLSYNC_ITEMSENTRY']._loaded_options = None
  _globals['_WATCHKEYRECURSIVERESPONSE_FULLSYNC_ITEMSENTRY']._serialized_options = b'8\001'
  _globals['_WATCHKEYREQUEST']._serialized_start=112
  _globals['_WATCHKEYREQUEST']._serialized_end=142
  _globals['_WATCHKEYRESPONSE']._serialized_start=144
  _globals['_WATCHKEYRESPONSE']._serialized_end=207
  _globals['_WATCHKEYRECURSIVEREQUEST']._serialized_start=209
  _globals['_WATCHKEYRECURSIVEREQUEST']._serialized_end=248
  _globals['_WATCHKEYRECURSIVERESPONSE']._serialized_start=251
  _globals['_WATCHKEYRECURSIVERESPONSE']._serialized_end=780
  _globals['_WATCHKEYRECURSIVERESPONSE_FULLSYNC']._serialized_start=539
  _globals['_WATCHKEYRECURSIVERESPONSE_FULLSYNC']._serialized_end=686
  _globals['_WATCHKEYRECURSIVERESPONSE_FULLSYNC_ITEMSENTRY']._serialized_start=642
  _globals['_WATCHKEYRECURSIVERESPONSE_FULLSYNC_ITEMSENTRY']._serialized_end=686
  _globals['_WATCHKEYRECURSIVERESPONSE_SYNCONE']._serialized_start=688
  _globals['_WATCHKEYRECURSIVERESPONSE_SYNCONE']._serialized_end=725
  _globals['_WATCHKEYRECURSIVERESPONSE_DELETEONE']._serialized_start=727
  _globals['_WATCHKEYRECURSIVERESPONSE_DELETEONE']._serialized_end=771
  _globals['_ETCDWATCHERDSERVICE']._serialized_start=783
  _globals['_ETCDWATCHERDSERVICE']._serialized_end=1046
# @@protoc_insertion_point(module_scope)
