# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: osprey/rpc/common/v1/verdicts.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#osprey/rpc/common/v1/verdicts.proto\x12\x14osprey.rpc.common.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"s\n\x08Verdicts\x12\x11\n\taction_id\x18\x01 \x01(\x04\x12\x13\n\x0b\x61\x63tion_name\x18\x02 \x01(\t\x12\x10\n\x08verdicts\x18\x03 \x03(\t\x12-\n\ttimestamp\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestampb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'osprey.rpc.common.v1.verdicts_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VERDICTS._serialized_start=94
  _VERDICTS._serialized_end=209
# @@protoc_insertion_point(module_scope)
