"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ScanURLRequest(google.protobuf.message.Message):
    """Message to represent a URL scan request"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    URL_FIELD_NUMBER: builtins.int
    url: builtins.str
    """The URL to be scanned"""
    def __init__(
        self,
        *,
        url: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["url", b"url"]) -> None: ...

global___ScanURLRequest = ScanURLRequest

@typing.final
class SuccessDetails(google.protobuf.message.Message):
    """Fields can be added later to this message to provide more information about the scan if needed"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IS_MALICIOUS_FIELD_NUMBER: builtins.int
    is_malicious: builtins.bool
    def __init__(
        self,
        *,
        is_malicious: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["is_malicious", b"is_malicious"]) -> None: ...

global___SuccessDetails = SuccessDetails

@typing.final
class FailureDetails(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    error_message: builtins.str
    def __init__(
        self,
        *,
        error_message: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["error_message", b"error_message"]) -> None: ...

global___FailureDetails = FailureDetails

@typing.final
class SubmittedDetails(google.protobuf.message.Message):
    """Currently empty, but we can add fields later as needed"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___SubmittedDetails = SubmittedDetails

@typing.final
class ScanURLResponse(google.protobuf.message.Message):
    """Message to represent a progress update or final result of a URL scan"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUBMITTED_FIELD_NUMBER: builtins.int
    SUCCESS_FIELD_NUMBER: builtins.int
    FAILURE_FIELD_NUMBER: builtins.int
    @property
    def submitted(self) -> global___SubmittedDetails:
        """The scan request was successfully submitted"""

    @property
    def success(self) -> global___SuccessDetails:
        """The scan was completed successfully"""

    @property
    def failure(self) -> global___FailureDetails:
        """The scan encountered an error"""

    def __init__(
        self,
        *,
        submitted: global___SubmittedDetails | None = ...,
        success: global___SuccessDetails | None = ...,
        failure: global___FailureDetails | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["failure", b"failure", "status_details", b"status_details", "submitted", b"submitted", "success", b"success"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["failure", b"failure", "status_details", b"status_details", "submitted", b"submitted", "success", b"success"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["status_details", b"status_details"]) -> typing.Literal["submitted", "success", "failure"] | None: ...

global___ScanURLResponse = ScanURLResponse
