"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2021 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _SchemaView:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _SchemaViewEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_SchemaView.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    SCHEMA_VIEW_UNSPECIFIED: _SchemaView.ValueType  # 0
    """The default / unset value.
    The API will default to the BASIC view.
    """
    BASIC: _SchemaView.ValueType  # 1
    """Include the name and type of the schema, but not the definition."""
    FULL: _SchemaView.ValueType  # 2
    """Include all Schema object fields."""

class SchemaView(_SchemaView, metaclass=_SchemaViewEnumTypeWrapper):
    """View of Schema object fields to be returned by GetSchema and ListSchemas."""

SCHEMA_VIEW_UNSPECIFIED: SchemaView.ValueType  # 0
"""The default / unset value.
The API will default to the BASIC view.
"""
BASIC: SchemaView.ValueType  # 1
"""Include the name and type of the schema, but not the definition."""
FULL: SchemaView.ValueType  # 2
"""Include all Schema object fields."""
global___SchemaView = SchemaView

class _Encoding:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _EncodingEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Encoding.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    ENCODING_UNSPECIFIED: _Encoding.ValueType  # 0
    """Unspecified"""
    JSON: _Encoding.ValueType  # 1
    """JSON encoding"""
    BINARY: _Encoding.ValueType  # 2
    """Binary encoding, as defined by the schema type. For some schema types,
    binary encoding may not be available.
    """

class Encoding(_Encoding, metaclass=_EncodingEnumTypeWrapper):
    """Possible encoding types for messages."""

ENCODING_UNSPECIFIED: Encoding.ValueType  # 0
"""Unspecified"""
JSON: Encoding.ValueType  # 1
"""JSON encoding"""
BINARY: Encoding.ValueType  # 2
"""Binary encoding, as defined by the schema type. For some schema types,
binary encoding may not be available.
"""
global___Encoding = Encoding

@typing.final
class Schema(google.protobuf.message.Message):
    """A schema resource."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Type:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _TypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Schema._Type.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        TYPE_UNSPECIFIED: Schema._Type.ValueType  # 0
        """Default value. This value is unused."""
        PROTOCOL_BUFFER: Schema._Type.ValueType  # 1
        """A Protocol Buffer schema definition."""
        AVRO: Schema._Type.ValueType  # 2
        """An Avro schema definition."""

    class Type(_Type, metaclass=_TypeEnumTypeWrapper):
        """Possible schema definition types."""

    TYPE_UNSPECIFIED: Schema.Type.ValueType  # 0
    """Default value. This value is unused."""
    PROTOCOL_BUFFER: Schema.Type.ValueType  # 1
    """A Protocol Buffer schema definition."""
    AVRO: Schema.Type.ValueType  # 2
    """An Avro schema definition."""

    NAME_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    DEFINITION_FIELD_NUMBER: builtins.int
    name: builtins.str
    """Required. Name of the schema.
    Format is `projects/{project}/schemas/{schema}`.
    """
    type: global___Schema.Type.ValueType
    """The type of the schema definition."""
    definition: builtins.str
    """The definition of the schema. This should contain a string representing
    the full definition of the schema that is a valid schema definition of
    the type specified in `type`.
    """
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        type: global___Schema.Type.ValueType = ...,
        definition: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["definition", b"definition", "name", b"name", "type", b"type"]) -> None: ...

global___Schema = Schema

@typing.final
class CreateSchemaRequest(google.protobuf.message.Message):
    """Request for the CreateSchema method."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PARENT_FIELD_NUMBER: builtins.int
    SCHEMA_FIELD_NUMBER: builtins.int
    SCHEMA_ID_FIELD_NUMBER: builtins.int
    parent: builtins.str
    """Required. The name of the project in which to create the schema.
    Format is `projects/{project-id}`.
    """
    schema_id: builtins.str
    """The ID to use for the schema, which will become the final component of
    the schema's resource name.

    See https://cloud.google.com/pubsub/docs/admin#resource_names for resource
    name constraints.
    """
    @property
    def schema(self) -> global___Schema:
        """Required. The schema object to create.

        This schema's `name` parameter is ignored. The schema object returned
        by CreateSchema will have a `name` made using the given `parent` and
        `schema_id`.
        """

    def __init__(
        self,
        *,
        parent: builtins.str = ...,
        schema: global___Schema | None = ...,
        schema_id: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["schema", b"schema"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["parent", b"parent", "schema", b"schema", "schema_id", b"schema_id"]) -> None: ...

global___CreateSchemaRequest = CreateSchemaRequest

@typing.final
class GetSchemaRequest(google.protobuf.message.Message):
    """Request for the GetSchema method."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    VIEW_FIELD_NUMBER: builtins.int
    name: builtins.str
    """Required. The name of the schema to get.
    Format is `projects/{project}/schemas/{schema}`.
    """
    view: global___SchemaView.ValueType
    """The set of fields to return in the response. If not set, returns a Schema
    with `name` and `type`, but not `definition`. Set to `FULL` to retrieve all
    fields.
    """
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        view: global___SchemaView.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name", "view", b"view"]) -> None: ...

global___GetSchemaRequest = GetSchemaRequest

@typing.final
class ListSchemasRequest(google.protobuf.message.Message):
    """Request for the `ListSchemas` method."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PARENT_FIELD_NUMBER: builtins.int
    VIEW_FIELD_NUMBER: builtins.int
    PAGE_SIZE_FIELD_NUMBER: builtins.int
    PAGE_TOKEN_FIELD_NUMBER: builtins.int
    parent: builtins.str
    """Required. The name of the project in which to list schemas.
    Format is `projects/{project-id}`.
    """
    view: global___SchemaView.ValueType
    """The set of Schema fields to return in the response. If not set, returns
    Schemas with `name` and `type`, but not `definition`. Set to `FULL` to
    retrieve all fields.
    """
    page_size: builtins.int
    """Maximum number of schemas to return."""
    page_token: builtins.str
    """The value returned by the last `ListSchemasResponse`; indicates that
    this is a continuation of a prior `ListSchemas` call, and that the
    system should return the next page of data.
    """
    def __init__(
        self,
        *,
        parent: builtins.str = ...,
        view: global___SchemaView.ValueType = ...,
        page_size: builtins.int = ...,
        page_token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["page_size", b"page_size", "page_token", b"page_token", "parent", b"parent", "view", b"view"]) -> None: ...

global___ListSchemasRequest = ListSchemasRequest

@typing.final
class ListSchemasResponse(google.protobuf.message.Message):
    """Response for the `ListSchemas` method."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SCHEMAS_FIELD_NUMBER: builtins.int
    NEXT_PAGE_TOKEN_FIELD_NUMBER: builtins.int
    next_page_token: builtins.str
    """If not empty, indicates that there may be more schemas that match the
    request; this value should be passed in a new `ListSchemasRequest`.
    """
    @property
    def schemas(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Schema]:
        """The resulting schemas."""

    def __init__(
        self,
        *,
        schemas: collections.abc.Iterable[global___Schema] | None = ...,
        next_page_token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["next_page_token", b"next_page_token", "schemas", b"schemas"]) -> None: ...

global___ListSchemasResponse = ListSchemasResponse

@typing.final
class DeleteSchemaRequest(google.protobuf.message.Message):
    """Request for the `DeleteSchema` method."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    """Required. Name of the schema to delete.
    Format is `projects/{project}/schemas/{schema}`.
    """
    def __init__(
        self,
        *,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name"]) -> None: ...

global___DeleteSchemaRequest = DeleteSchemaRequest

@typing.final
class ValidateSchemaRequest(google.protobuf.message.Message):
    """Request for the `ValidateSchema` method."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PARENT_FIELD_NUMBER: builtins.int
    SCHEMA_FIELD_NUMBER: builtins.int
    parent: builtins.str
    """Required. The name of the project in which to validate schemas.
    Format is `projects/{project-id}`.
    """
    @property
    def schema(self) -> global___Schema:
        """Required. The schema object to validate."""

    def __init__(
        self,
        *,
        parent: builtins.str = ...,
        schema: global___Schema | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["schema", b"schema"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["parent", b"parent", "schema", b"schema"]) -> None: ...

global___ValidateSchemaRequest = ValidateSchemaRequest

@typing.final
class ValidateSchemaResponse(google.protobuf.message.Message):
    """Response for the `ValidateSchema` method.
    Empty for now.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___ValidateSchemaResponse = ValidateSchemaResponse

@typing.final
class ValidateMessageRequest(google.protobuf.message.Message):
    """Request for the `ValidateMessage` method."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PARENT_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    SCHEMA_FIELD_NUMBER: builtins.int
    MESSAGE_FIELD_NUMBER: builtins.int
    ENCODING_FIELD_NUMBER: builtins.int
    parent: builtins.str
    """Required. The name of the project in which to validate schemas.
    Format is `projects/{project-id}`.
    """
    name: builtins.str
    """Name of the schema against which to validate.

    Format is `projects/{project}/schemas/{schema}`.
    """
    message: builtins.bytes
    """Message to validate against the provided `schema_spec`."""
    encoding: global___Encoding.ValueType
    """The encoding expected for messages"""
    @property
    def schema(self) -> global___Schema:
        """Ad-hoc schema against which to validate"""

    def __init__(
        self,
        *,
        parent: builtins.str = ...,
        name: builtins.str = ...,
        schema: global___Schema | None = ...,
        message: builtins.bytes = ...,
        encoding: global___Encoding.ValueType = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["name", b"name", "schema", b"schema", "schema_spec", b"schema_spec"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["encoding", b"encoding", "message", b"message", "name", b"name", "parent", b"parent", "schema", b"schema", "schema_spec", b"schema_spec"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["schema_spec", b"schema_spec"]) -> typing.Literal["name", "schema"] | None: ...

global___ValidateMessageRequest = ValidateMessageRequest

@typing.final
class ValidateMessageResponse(google.protobuf.message.Message):
    """Response for the `ValidateMessage` method.
    Empty for now.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___ValidateMessageResponse = ValidateMessageResponse
