"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _LabelStatus:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _LabelStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_LabelStatus.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    ADDED: _LabelStatus.ValueType  # 0
    REMOVED: _LabelStatus.ValueType  # 1
    MANUALLY_ADDED: _LabelStatus.ValueType  # 2
    MANUALLY_REMOVED: _LabelStatus.ValueType  # 3

class LabelStatus(_LabelStatus, metaclass=_LabelStatusEnumTypeWrapper): ...

ADDED: LabelStatus.ValueType  # 0
REMOVED: LabelStatus.ValueType  # 1
MANUALLY_ADDED: LabelStatus.ValueType  # 2
MANUALLY_REMOVED: LabelStatus.ValueType  # 3
global___LabelStatus = LabelStatus

class _MutationOperation:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _MutationOperationEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_MutationOperation.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    MUTATION_OPERATION_UNSPECIFIED: _MutationOperation.ValueType  # 0
    MUTATION_OPERATION_ADDED: _MutationOperation.ValueType  # 1
    MUTATION_OPERATION_UPDATED: _MutationOperation.ValueType  # 2
    MUTATION_OPERATION_UNCHANGED: _MutationOperation.ValueType  # 3
    MUTATION_OPERATION_REMOVED: _MutationOperation.ValueType  # 4

class MutationOperation(_MutationOperation, metaclass=_MutationOperationEnumTypeWrapper): ...

MUTATION_OPERATION_UNSPECIFIED: MutationOperation.ValueType  # 0
MUTATION_OPERATION_ADDED: MutationOperation.ValueType  # 1
MUTATION_OPERATION_UPDATED: MutationOperation.ValueType  # 2
MUTATION_OPERATION_UNCHANGED: MutationOperation.ValueType  # 3
MUTATION_OPERATION_REMOVED: MutationOperation.ValueType  # 4
global___MutationOperation = MutationOperation

@typing.final
class LabelReason(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class FeaturesEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    PENDING_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    FEATURES_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    EXPIRES_AT_FIELD_NUMBER: builtins.int
    pending: builtins.bool
    description: builtins.str
    @property
    def features(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    @property
    def created_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def expires_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        pending: builtins.bool = ...,
        description: builtins.str = ...,
        features: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        created_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        expires_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["created_at", b"created_at", "expires_at", b"expires_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["created_at", b"created_at", "description", b"description", "expires_at", b"expires_at", "features", b"features", "pending", b"pending"]) -> None: ...

global___LabelReason = LabelReason

@typing.final
class LabelStateInner(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class ReasonsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> global___LabelReason: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: global___LabelReason | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    STATUS_FIELD_NUMBER: builtins.int
    REASONS_FIELD_NUMBER: builtins.int
    status: global___LabelStatus.ValueType
    @property
    def reasons(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___LabelReason]: ...
    def __init__(
        self,
        *,
        status: global___LabelStatus.ValueType = ...,
        reasons: collections.abc.Mapping[builtins.str, global___LabelReason] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["reasons", b"reasons", "status", b"status"]) -> None: ...

global___LabelStateInner = LabelStateInner

@typing.final
class LabelState(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class ReasonsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> global___LabelReason: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: global___LabelReason | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    STATUS_FIELD_NUMBER: builtins.int
    REASONS_FIELD_NUMBER: builtins.int
    PREVIOUS_STATES_FIELD_NUMBER: builtins.int
    status: global___LabelStatus.ValueType
    @property
    def reasons(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___LabelReason]: ...
    @property
    def previous_states(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___LabelStateInner]: ...
    def __init__(
        self,
        *,
        status: global___LabelStatus.ValueType = ...,
        reasons: collections.abc.Mapping[builtins.str, global___LabelReason] | None = ...,
        previous_states: collections.abc.Iterable[global___LabelStateInner] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["previous_states", b"previous_states", "reasons", b"reasons", "status", b"status"]) -> None: ...

global___LabelState = LabelState

@typing.final
class Labels(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class LabelsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> global___LabelState: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: global___LabelState | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    LABELS_FIELD_NUMBER: builtins.int
    EXPIRES_AT_FIELD_NUMBER: builtins.int
    @property
    def labels(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___LabelState]: ...
    @property
    def expires_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        labels: collections.abc.Mapping[builtins.str, global___LabelState] | None = ...,
        expires_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["expires_at", b"expires_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["expires_at", b"expires_at", "labels", b"labels"]) -> None: ...

global___Labels = Labels

@typing.final
class EntityKey(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TYPE_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    type: builtins.str
    id: builtins.str
    def __init__(
        self,
        *,
        type: builtins.str = ...,
        id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["id", b"id", "type", b"type"]) -> None: ...

global___EntityKey = EntityKey

@typing.final
class Entity(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KEY_FIELD_NUMBER: builtins.int
    LABELS_FIELD_NUMBER: builtins.int
    @property
    def key(self) -> global___EntityKey: ...
    @property
    def labels(self) -> global___Labels: ...
    def __init__(
        self,
        *,
        key: global___EntityKey | None = ...,
        labels: global___Labels | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["key", b"key", "labels", b"labels"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["key", b"key", "labels", b"labels"]) -> None: ...

global___Entity = Entity

@typing.final
class TakeDataRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KEY_FIELD_NUMBER: builtins.int
    key: builtins.str
    def __init__(
        self,
        *,
        key: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["key", b"key"]) -> None: ...

global___TakeDataRequest = TakeDataRequest

@typing.final
class Data(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BYTES_FIELD_NUMBER: builtins.int
    bytes: builtins.bytes
    def __init__(
        self,
        *,
        bytes: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["bytes", b"bytes"]) -> None: ...

global___Data = Data

@typing.final
class TakeDataResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DATA_FIELD_NUMBER: builtins.int
    @property
    def data(self) -> global___Data: ...
    def __init__(
        self,
        *,
        data: global___Data | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["data", b"data"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["data", b"data"]) -> None: ...

global___TakeDataResponse = TakeDataResponse

@typing.final
class GetEntityBatchRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ROUTING_KEY_FIELD_NUMBER: builtins.int
    KEYS_FIELD_NUMBER: builtins.int
    routing_key: builtins.str
    @property
    def keys(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___EntityKey]: ...
    def __init__(
        self,
        *,
        routing_key: builtins.str = ...,
        keys: collections.abc.Iterable[global___EntityKey] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["keys", b"keys", "routing_key", b"routing_key"]) -> None: ...

global___GetEntityBatchRequest = GetEntityBatchRequest

@typing.final
class GetEntityBatchResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESPONSES_FIELD_NUMBER: builtins.int
    @property
    def responses(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___GetEntityResponse]: ...
    def __init__(
        self,
        *,
        responses: collections.abc.Iterable[global___GetEntityResponse] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["responses", b"responses"]) -> None: ...

global___GetEntityBatchResponse = GetEntityBatchResponse

@typing.final
class GetEntityRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ROUTING_KEY_FIELD_NUMBER: builtins.int
    KEY_FIELD_NUMBER: builtins.int
    routing_key: builtins.str
    @property
    def key(self) -> global___EntityKey: ...
    def __init__(
        self,
        *,
        routing_key: builtins.str = ...,
        key: global___EntityKey | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["key", b"key"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["key", b"key", "routing_key", b"routing_key"]) -> None: ...

global___GetEntityRequest = GetEntityRequest

@typing.final
class GetEntityResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ENTITY_FIELD_NUMBER: builtins.int
    @property
    def entity(self) -> global___Entity: ...
    def __init__(
        self,
        *,
        entity: global___Entity | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["entity", b"entity"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["entity", b"entity"]) -> None: ...

global___GetEntityResponse = GetEntityResponse

@typing.final
class EntityMutation(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class FeaturesEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    LABEL_NAME_FIELD_NUMBER: builtins.int
    REASON_NAME_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    PENDING_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    FEATURES_FIELD_NUMBER: builtins.int
    EXPIRES_AT_FIELD_NUMBER: builtins.int
    label_name: builtins.str
    """The label name to apply."""
    reason_name: builtins.str
    """The reason the label was applied, generally this is the label name."""
    status: global___LabelStatus.ValueType
    pending: builtins.bool
    description: builtins.str
    @property
    def features(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    @property
    def expires_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        label_name: builtins.str = ...,
        reason_name: builtins.str = ...,
        status: global___LabelStatus.ValueType = ...,
        pending: builtins.bool = ...,
        description: builtins.str = ...,
        features: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        expires_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["expires_at", b"expires_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["description", b"description", "expires_at", b"expires_at", "features", b"features", "label_name", b"label_name", "pending", b"pending", "reason_name", b"reason_name", "status", b"status"]) -> None: ...

global___EntityMutation = EntityMutation

@typing.final
class ApplyEntityMutationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ROUTING_KEY_FIELD_NUMBER: builtins.int
    KEY_FIELD_NUMBER: builtins.int
    MUTATIONS_FIELD_NUMBER: builtins.int
    routing_key: builtins.str
    @property
    def key(self) -> global___EntityKey: ...
    @property
    def mutations(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___EntityMutation]: ...
    def __init__(
        self,
        *,
        routing_key: builtins.str = ...,
        key: global___EntityKey | None = ...,
        mutations: collections.abc.Iterable[global___EntityMutation] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["key", b"key"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["key", b"key", "mutations", b"mutations", "routing_key", b"routing_key"]) -> None: ...

global___ApplyEntityMutationRequest = ApplyEntityMutationRequest

@typing.final
class ApplyEntityMutationReply(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ADDED_FIELD_NUMBER: builtins.int
    REMOVED_FIELD_NUMBER: builtins.int
    UNCHANGED_FIELD_NUMBER: builtins.int
    DROPPED_FIELD_NUMBER: builtins.int
    @property
    def added(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def removed(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def unchanged(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def dropped(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___EntityMutation]: ...
    def __init__(
        self,
        *,
        added: collections.abc.Iterable[builtins.str] | None = ...,
        removed: collections.abc.Iterable[builtins.str] | None = ...,
        unchanged: collections.abc.Iterable[builtins.str] | None = ...,
        dropped: collections.abc.Iterable[global___EntityMutation] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["added", b"added", "dropped", b"dropped", "removed", b"removed", "unchanged", b"unchanged"]) -> None: ...

global___ApplyEntityMutationReply = ApplyEntityMutationReply

@typing.final
class TokenRangeQuery(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OPAQUE_FIELD_NUMBER: builtins.int
    opaque: builtins.str
    def __init__(
        self,
        *,
        opaque: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["opaque", b"opaque"]) -> None: ...

global___TokenRangeQuery = TokenRangeQuery

@typing.final
class GetTokenRangeQueriesRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___GetTokenRangeQueriesRequest = GetTokenRangeQueriesRequest

@typing.final
class GetTokenRangeQueriesResult(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MAX_QUERY_CONCURRENCY_FIELD_NUMBER: builtins.int
    TOKEN_RANGE_QUERIES_FIELD_NUMBER: builtins.int
    max_query_concurrency: builtins.int
    @property
    def token_range_queries(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TokenRangeQuery]: ...
    def __init__(
        self,
        *,
        max_query_concurrency: builtins.int = ...,
        token_range_queries: collections.abc.Iterable[global___TokenRangeQuery] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["max_query_concurrency", b"max_query_concurrency", "token_range_queries", b"token_range_queries"]) -> None: ...

global___GetTokenRangeQueriesResult = GetTokenRangeQueriesResult

@typing.final
class ScanTokenRangeRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOKEN_RANGE_QUERY_FIELD_NUMBER: builtins.int
    @property
    def token_range_query(self) -> global___TokenRangeQuery: ...
    def __init__(
        self,
        *,
        token_range_query: global___TokenRangeQuery | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["token_range_query", b"token_range_query"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["token_range_query", b"token_range_query"]) -> None: ...

global___ScanTokenRangeRequest = ScanTokenRangeRequest

@typing.final
class ScanTokenRangeResult(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTINUATION_TOKEN_FIELD_NUMBER: builtins.int
    ENTITIES_FIELD_NUMBER: builtins.int
    @property
    def continuation_token(self) -> global___TokenRangeQuery: ...
    @property
    def entities(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Entity]: ...
    def __init__(
        self,
        *,
        continuation_token: global___TokenRangeQuery | None = ...,
        entities: collections.abc.Iterable[global___Entity] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["continuation_token", b"continuation_token"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["continuation_token", b"continuation_token", "entities", b"entities"]) -> None: ...

global___ScanTokenRangeResult = ScanTokenRangeResult

@typing.final
class LabelReasonMutationResult(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OPERATION_FIELD_NUMBER: builtins.int
    PREV_REASON_FIELD_NUMBER: builtins.int
    CURRENT_REASON_FIELD_NUMBER: builtins.int
    operation: global___MutationOperation.ValueType
    @property
    def prev_reason(self) -> global___LabelReason: ...
    @property
    def current_reason(self) -> global___LabelReason: ...
    def __init__(
        self,
        *,
        operation: global___MutationOperation.ValueType = ...,
        prev_reason: global___LabelReason | None = ...,
        current_reason: global___LabelReason | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["current_reason", b"current_reason", "prev_reason", b"prev_reason"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["current_reason", b"current_reason", "operation", b"operation", "prev_reason", b"prev_reason"]) -> None: ...

global___LabelReasonMutationResult = LabelReasonMutationResult

@typing.final
class LabelMutationResult(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class ReasonsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> global___LabelReasonMutationResult: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: global___LabelReasonMutationResult | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    STATUS_FIELD_NUMBER: builtins.int
    OPERATION_FIELD_NUMBER: builtins.int
    REASONS_FIELD_NUMBER: builtins.int
    status: global___LabelStatus.ValueType
    operation: global___MutationOperation.ValueType
    @property
    def reasons(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___LabelReasonMutationResult]: ...
    def __init__(
        self,
        *,
        status: global___LabelStatus.ValueType = ...,
        operation: global___MutationOperation.ValueType = ...,
        reasons: collections.abc.Mapping[builtins.str, global___LabelReasonMutationResult] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["operation", b"operation", "reasons", b"reasons", "status", b"status"]) -> None: ...

global___LabelMutationResult = LabelMutationResult

@typing.final
class ApplyEntityMutationReplyUpdated(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class LabelMutationsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> global___LabelMutationResult: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: global___LabelMutationResult | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    LABEL_MUTATIONS_FIELD_NUMBER: builtins.int
    DROPPED_FIELD_NUMBER: builtins.int
    @property
    def label_mutations(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___LabelMutationResult]: ...
    @property
    def dropped(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___EntityMutation]: ...
    def __init__(
        self,
        *,
        label_mutations: collections.abc.Mapping[builtins.str, global___LabelMutationResult] | None = ...,
        dropped: collections.abc.Iterable[global___EntityMutation] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["dropped", b"dropped", "label_mutations", b"label_mutations"]) -> None: ...

global___ApplyEntityMutationReplyUpdated = ApplyEntityMutationReplyUpdated
