load("@rules_proto//proto:defs.bzl", "proto_library")

package(default_visibility = ["//visibility:public"])

proto_library(
    name = "expr_proto",
    srcs = ["expr.proto"],
    strip_import_prefix = "/proto/",
)
