# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/crypto/tink/aes_gcm.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n google/crypto/tink/aes_gcm.proto\x12\x12google.crypto.tink\"4\n\x0f\x41\x65sGcmKeyFormat\x12\x10\n\x08key_size\x18\x02 \x01(\r\x12\x0f\n\x07version\x18\x03 \x01(\r\"/\n\tAesGcmKey\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x11\n\tkey_value\x18\x03 \x01(\x0c\x42[\n\x1c\x63om.google.crypto.tink.protoP\x01Z0github.com/google/tink/go/proto/aes_gcm_go_proto\xa2\x02\x06TINKPBb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'google.crypto.tink.aes_gcm_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\034com.google.crypto.tink.protoP\001Z0github.com/google/tink/go/proto/aes_gcm_go_proto\242\002\006TINKPB'
  _AESGCMKEYFORMAT._serialized_start=56
  _AESGCMKEYFORMAT._serialized_end=108
  _AESGCMKEY._serialized_start=110
  _AESGCMKEY._serialized_end=157
# @@protoc_insertion_point(module_scope)
