[book]
title = "Osprey Documentation"
authors = ["ROOST"]
language = "en"
src = "."

[build]
build-dir = "./book"
create-missing = false

[output.html]
default-theme = "roost"
preferred-dark-theme = "roost"
additional-css = ["theme/css/roost.css", "theme/css/roost-hljs.css", "theme/css/content.css"]
edit-url-template = "https://github.com/roostorg/osprey/edit/main/docs/{path}"
git-repository-url = "https://github.com/roostorg/osprey"
site-url = "/osprey/"

[output.html.print]
enable = false

[output.html.redirect]
"/integrations.html" = "integration/integrations.html"
"/rules.html" = "rules/index.html"
