name: Integration Tests

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create temp directory for test results
        run: mkdir -p /tmp/test-results

      - name: Pull and build Docker images
        run: |
          docker compose -f docker-compose.yaml -f docker-compose.test.yaml --profile test pull
          docker compose -f docker-compose.yaml -f docker-compose.test.yaml --profile test build

      - name: Run integration tests
        run: ./run-tests.sh --junitxml=/tmp/test-results/junit-pytest.xml

      - name: Clean up Docker containers
        if: always()
        run: docker compose -f docker-compose.yaml -f docker-compose.test.yaml --profile test down --volumes

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: pytest-results
          path: /tmp/test-results/junit-pytest.xml
          retention-days: 30
